config:
  jobTimeout: '180'
  gerritTriggerMap:
    - repository: pytorch-fork
    - repository: pytorch-lightning-fork
    - repository: Habana-Lightning-Plugins
    - repository: pytorch-vision-fork
    - repository: pytorch-integration
  osBuild:
    debian10.10: "on"
    ubuntu18.04: "off"
  dependantComponents:
    - component: deepspeed_fork