config:
  jobTimeout: '180'
  sharedCCacheEnabled: true
  gerritTriggerMap:
    - repository: pytorch-fork
    - repository: pytorch-vision-fork
    - repository: pytorch-integration
    - repository: lightning-habana-fork
  osBuild:
    debian10.10: "on"
    ubuntu18.04: "off"
    tencentos3.1: 'on'
  dependantComponents:
    - component: deepspeed_fork
    - component: pt_next
