// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "_deform_conv2d_backward.h"
#include "convolution_backward_overrideable.h"
#include "ind2ptr.h"
#include "linear_backward.h"
#include "native_group_norm.h"
#include "quantize_per_channel.h"


using habana_helpers::DTypeHelper; // NOLINT(misc-unused-using-decls)
using synapse_helpers::graph; // NOLINT(misc-unused-using-decls)
using torch::jit::Stack;


namespace habana {





struct Gen_convolution_backward_overrideable : ConvolutionBackwardOverrideable {
  Gen_convolution_backward_overrideable(int device_id, c10::ScalarType scalar_type) :
      ConvolutionBackwardOverrideable(device_id, "None", scalar_type, {0, 0, 0}, {}, {}, false) {
        SetOutputMetaFn(ConvolutionOverrideableMetaBwd);
  }
};

struct Gen_native_group_norm : OpBackend {
  Gen_native_group_norm(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "native_group_norm_fwd", scalar_type, {0, 0, 0}, {}, {}, false) {
        SetOutputMetaFn(GroupNormFwdMeta);
        SetFillParams(FillNativeGroupNormParams);
  }
};

struct Gen_linear_backward : OpBackend {
  Gen_linear_backward(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "linear_temp_bwd", scalar_type, {0, 0, 0}, {}, {}, false) {
        SetOutputMetaFn(LinearBackwardMeta);
        SetFillParams(FillLinearBwdParams);
  }
};

struct Gen_quantize_per_channel : OpBackend {
  Gen_quantize_per_channel(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "quantize_per_channel", scalar_type, {0}, {}, {}, false) {
        SetOutputMetaFn(QuantizePerChannelMeta);
        SetFillParams(FillQuantizePerChannelParams);
  }
};

struct Gen_priv_deform_conv2d_backward : DeformConv2dBackward {
  Gen_priv_deform_conv2d_backward(int device_id, c10::ScalarType scalar_type) :
      DeformConv2dBackward(device_id, "None", scalar_type, {0}, {}, {}, false) {
        SetSynapseLayouts({synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::SRCK, synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::WHCN}, {synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::SRCK, synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::WHCN, synapse_helpers::layouts::SynapseLayoutFormat::DONT_CARE});
        SetOutputMetaFn(DeformConv2dBackwardOutputMeta);
  }
};

struct Gen_ind2ptr : OpBackend {
  Gen_ind2ptr(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "ind2ptr", scalar_type, {0}, {}, {}, false) {
        SetOutputMetaFn(Ind2ptrMeta);
        SetFillParams(FillInd2ptrParams);
  }
};



static const auto& kr_gen_9 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::convolution_backward_overrideable", Gen_convolution_backward_overrideable)
.REGISTER_HPU_BACKEND("aten::native_group_norm", Gen_native_group_norm)
.REGISTER_HPU_BACKEND("aten::linear_backward", Gen_linear_backward)
.REGISTER_HPU_BACKEND("quantized_decomposed::quantize_per_channel", Gen_quantize_per_channel)
.REGISTER_HPU_BACKEND("torchvision::_deform_conv2d_backward", Gen_priv_deform_conv2d_backward)
.REGISTER_HPU_BACKEND("torch_sparse::ind2ptr", Gen_ind2ptr)
;




}  // namespace habana

