// Autogenerated file by run_gen_op.py. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>
#include <ATen/core/function_schema.h>
#include "habana_kernels/lazy_kernels.h"
#include "hpu_ops/hpu_op_helper.h"

namespace habana {


at::Tensor ind2ptr(at::Tensor ind, int64_t M);
OUTMETA_DECL(Ind2ptrMeta);
FILL_PARAMS_DECL(FillInd2ptrParams);

}  // namespace habana

