// Autogenerated file by run_gen_op.py. Do not edit directly!

#include <torch/extension.h>
#include <pybind11/stl.h>
#include <pybind11/pybind11.h>
#include <torch/csrc/jit/tensorexpr/tensorexpr_init.h>
#include <torch/csrc/jit/python/pybind_utils.h>
#include "cpu_fallback.h"

using habana_helpers::DTypeHelper;
using namespace torch::jit;


namespace habana {

static CheckNodeWithSharedLayerValidator validator_addbmm("addbmm", AddBMMSharedMeta, habana_helpers::HabanaExecutionMode::COMPILE);
static CheckNodeWithSharedLayerValidator validator_bucketize_Scalar("bucketize.Scalar", "search_sorted_fwd", {1}, {0}, BucketizeMeta, {0, 1}, false, false, false, false);


struct shared_layer_addbmm : SharedLayerOp {
bool func(torch::jit::Stack &stack, bool is_dynamic) {
  if (stack.size() == 5) {
    auto ivalue_arr = torch::jit::last(stack, 5);
    if (ivalue_arr[0].isTensor() && ivalue_arr[1].isTensor() && ivalue_arr[2].isTensor() && ivalue_arr[3].isScalar() && ivalue_arr[4].isScalar() ) {

      c10::IValue self = std::move(peek(stack, 0, 5));
      c10::IValue batch1 = std::move(peek(stack, 1, 5));
      c10::IValue batch2 = std::move(peek(stack, 2, 5));
      c10::IValue beta = std::move(peek(stack, 3, 5));
      c10::IValue alpha = std::move(peek(stack, 4, 5));

      at::Tensor self_base = self.to<at::Tensor>();
      at::Tensor batch1_base = batch1.to<at::Tensor>();
      at::Tensor batch2_base = batch2.to<at::Tensor>();
      at::Scalar beta_base = beta.to<at::Scalar>();
      at::Scalar alpha_base = alpha.to<at::Scalar>();
      auto is_supported = impl(self_base, batch1_base, batch2_base, beta_base, alpha_base, is_dynamic);
      return is_supported;
    }
  }
  return false;
}
private:
bool impl(const at::Tensor & self, const at::Tensor & batch1, const at::Tensor & batch2, const at::Scalar & beta, const at::Scalar & alpha, bool is_dynamic) {
  VAL_CUSTOM_RETURN_IF_UNSUPPORTED_DTYPE(addbmm, is_dynamic, self, batch1, batch2, beta, alpha)

  return true;
}

};

struct shared_layer_bucketize : SharedLayerOp {
bool func(torch::jit::Stack &stack, bool is_dynamic) {
  if (stack.size() == 4) {
    auto ivalue_arr = torch::jit::last(stack, 4);
    if (ivalue_arr[0].isScalar() && ivalue_arr[1].isTensor() && ivalue_arr[2].isBool() && ivalue_arr[3].isBool() ) {

      c10::IValue self = std::move(peek(stack, 0, 4));
      c10::IValue boundaries = std::move(peek(stack, 1, 4));
      c10::IValue out_int32 = std::move(peek(stack, 2, 4));
      c10::IValue right = std::move(peek(stack, 3, 4));

      at::Scalar self_base = self.to<at::Scalar>();
      at::Tensor boundaries_base = boundaries.to<at::Tensor>();
      bool out_int32_base = out_int32.to<bool>();
      bool right_base = right.to<bool>();
      auto is_supported = impl(self_base, boundaries_base, out_int32_base, right_base, is_dynamic);
      return is_supported;
    }
  }
  return false;
}
private:
bool impl(const at::Scalar & self, const at::Tensor & boundaries, bool out_int32, bool right, bool is_dynamic) {
  auto compute_type = DTypeHelper::get_compute_dtype({self, boundaries}, c10::nullopt, DTypeHelper::DtypePromoteVariant::kPromoteToCommon, false/*safe_cast*/);
  static_cast<void>(compute_type);

  VAL_RETURN_IF_UNSUPPORTED_DTYPE2(bucketize, is_dynamic, Scalar, self, boundaries, out_int32, right)

  return true;
}

};





}  // namespace habana

