[project]
requires-python = ">=3.10"

[tool.ruff]
line-length = 120

# Rules: https://docs.astral.sh/ruff/rules
[tool.ruff.lint]
select = ["F","E","W","I","UP","B","C4","EXE","PYI","SIM","ARG","FIX","PL","N","PIE","S", "YTT", "INT", "PERF"]
ignore = [
   "E501", # "Line too long"
   "PLE1205", # "We use custom logger"
   "E722",
   "F811",
   "B023",
   "B028",
   "PLC0415",
   "PLR0911",
   "PLR0912",
   "PLR0913",
   "PLR0915",
   "PLR2004",
   "PLW0602",
   "PLW0603",
   "PLW2901",
   "ARG001",
   "ARG002",
   "ARG003",
   "ARG004",
   "ARG005",
   "FIX001",
   "FIX002",
   "FIX004",
   "N801",
   "N802",
   "N803",
   "N806",
   "N812",
   "N816",
   "N999",
   "S101",
   "S110",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401",
    "E402",
    "F403",
]
"*_C.py" = [
    "F401",
    "F403",
]
".devops/*" = [
    "S603",
    "S607",
]
"*tests/*" = [
    "E741",
    "F841",
    "S101",
    "S108",
    "S311",
]
"*passes.py" = [
    "S105",
]
"pytorch_helpers/habana_dataloader/*" = ["ALL"]
