###############################################################################
# Copyright (C) 2021 HabanaLabs, Ltd.
# All Rights Reserved.
#
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.
#
################################################################################

add_subdirectory(habana_serialization)