###############################################################################
# Copyright (C) 2021-2022 HabanaLabs, Ltd.
# All Rights Reserved.
#
# Unauthorized copying of this file, via any medium is strictly prohibited.
# Proprietary and confidential.
#
################################################################################

set(CMAKE_CXX_STANDARD 17)
add_subdirectory(habana_serialization)
add_subdirectory(tensor_comparator)
