#!/bin/bash
function help()
{
        echo -e "help: resnet50 [arguments]\n"
        echo -e "  -p <data-path>,    --data-path <data_path>      default: '/software/data/pytorch/imagenet/ILSVRC2012_micro/'"
        echo -e "  -m <model>,        --model <model>              default: 'resnet50'"
        echo -e "  -d <device>,       --device <device>            default: 'habana'"
        echo -e "  -b <batch_size>,   --batch-size <batchsize>     default: 128"
        echo -e "  -e <epochs>,       --epochs <epochs>            default: 1"
        echo -e "  -j <workers>,      --workers <workers>          default: 0"
        echo -e "  --print-freq <print_freq>                       default: 1"
        echo -e ""
}

while [ -n "$1" ];
    do
        case $1 in
	-p  | --data-path )
            shift
            __data_path=$1
            ;;
	-m  | --model )
            shift
            __model=$1
            ;;
	-d  | --device )
            shift
            __device=$1
            ;;
	-b  | --batch-size )
            shift
            __batch_size=$1
            ;;
	-e  | --epochs )
            shift
            __epochs=$1
            ;;
	-j  | --workers )
            shift
            __workers=$1
            ;;
	--print-freq )
            shift
            __print_freq=$1
            ;;
        -h  | --help )
            help
            exit 1;
            ;;
        *)
            echo "The parameter $1 is not allowed"
            help
            exit 1;
            ;;
        esac
        shift
    done

DATA_PATH=${__data_path:-'/software/data/pytorch/imagenet/ILSVRC2012_micro/'}
MODEL=${__model:-'resnet50'}
DEVICE=${__device:-'habana'}
BATCH_SIZE=${__batch_size:-128}
EPOCHS=${__epochs:-1}
WORKERS=${__workers:-0}
PRINT_FREQ=${__print_freq:-1}


printf "*** Starting training...\n\n"
PT_HPU_LOG_MOD_MASK=FFFF PT_HPU_LOG_TYPE_MASK=1 python resnet/train.py \
	--data-path=${DATA_PATH} \
	--model=${MODEL} \
	--device=${DEVICE} \
	--batch-size=${BATCH_SIZE} \
	--epochs=${EPOCHS} \
	--workers=${WORKERS} \
	--print-freq=${PRINT_FREQ}
