#!/bin/bash
function help()
{
        echo -e "help: resnet50 [arguments]\n"
        echo -e "  -p <data-path>,    --data-path <data_path>      default: '/software/data/pytorch/imagenet/ILSVRC2012_micro/'"
        echo -e "  -m <model>,        --model <model>              default: 'resnet50'"
        echo -e "  -d <device>,       --device <device>            default: 'habana'"
        echo -e "  -b <batch_size>,   --batch-size <batchsize>     default: 128"
        echo -e "                     --mode <mode>                default: trace mode. Possible values: trace, eager"
        echo -e "                     --data-type <data type>      default: fp32. Possible values: fp32, bf16"
        echo -e "  -e <epochs>,       --epochs <epochs>            default: 1"
        echo -e "  --print-freq <print_freq>                       default: 1"
        echo -e ""
        echo -e "Usage example:"
        echo -e "./demo_resnet --data-type bf16 --mode eager  --batch-size 64"
        echo -e "./demo_resnet --data-type fp32 --mode trace  --batch-size 128"
}

create_hcl_config()
{
        hcl_type=$1
        world_size=$2
        hcl_config_file=$3
        TMPPATH="/tmp"
        echo "{" > ${hcl_config_file}
        echo "    \"HCL_PORT\" : 5332," >> ${hcl_config_file}
        echo "    \"HCL_TYPE\" : \"${hcl_type}\"," >> ${hcl_config_file}
        if [ ${hcl_type} == 'BACK_2_BACK' ]; then
               echo "    \"DISABLED_PORTS\" : \"[0,1,2,3,5,6,7,8,9]\"," >> ${hcl_config_file}
        fi
        echo "    \"HCL_COUNT\" : ${world_size}" >> ${hcl_config_file}
        echo "}" >> ${hcl_config_file}
}
setup_env()
{
        world_size=$1
        backend=$2
        hcl_type=$3
        export PT_HPU_LOG_MOD_MASK=FFFF
        export PT_HPU_LOG_TYPE_MASK=1
        if [ ${world_size} -le 1 ]; then
                return
        fi
        export TEMP_DIR="/tmp"
        hcl_config_file="${TEMP_DIR}/hcl_config.json"
        create_hcl_config ${hcl_type} ${world_size} ${hcl_config_file}
        export HCL_CONFIG_PATH=${hcl_config_file}
        export PT_ENABLE_HABANA_STREAMSYNC=0
        export BACKEND=${backend}
        export WORLD_SIZE=${world_size}
}

while [ -n "$1" ];
    do
        case $1 in
	-p  | --data-path )
            shift
            __data_path=$1
            ;;
	-m  | --model )
            shift
            __model=$1
            ;;
	-d  | --device )
            shift
            __device=$1
            ;;
	-b  | --batch-size )
            shift
            __batch_size=$1
            ;;
	      --data-type )
            shift
            __dtype=$1
            ;;
	    --mode )
            shift
            __mode=$1
            ;;
	-e  | --epochs )
            shift
            __epochs=$1
            ;;
	-j  | --workers )
            shift
            __workers=$1
            ;;
	--print-freq )
            shift
            __print_freq=$1
            ;;
        -w |--world-size )
            shift
            __world_size=$1
            ;;
        -c |--comm-backend )
            shift
            __comm_backend=$1
            ;;

        -h  | --help )
            help
            exit 1;
            ;;
        *)
            echo "The parameter $1 is not allowed"
            help
            exit 1;
            ;;
        esac
        shift
    done

DATA_PATH=${__data_path:-'/software/data/pytorch/imagenet/ILSVRC2012_micro/'}
MODEL=${__model:-'resnet50'}
DEVICE=${__device:-'habana'}
BATCH_SIZE=${__batch_size:-128}
EPOCHS=${__epochs:-1}
WORKERS=${__workers:-0}
PRINT_FREQ=${__print_freq:-1}
WORLD_SIZE=${__world_size:-1}
COMMUNICATIN_BACKEND=${__comm_backend:-'hcl'}
INTERPRETER="python"

if [[ $0 == *dist* ]] && [ ${WORLD_SIZE} -eq 1 ]; then
    WORLD_SIZE=8
fi

setup_env ${WORLD_SIZE} ${COMMUNICATIN_BACKEND} "HLS1"
if [ ${WORLD_SIZE} -gt 1 ]; then
    INTERPRETER="python -um torch.distributed.launch --nproc_per_node=${WORLD_SIZE} --use_env"
fi

if [ -n "$__mode" ]; then
    if [ "$__mode" == "trace" ]; then
       MODE="--run-trace-mode"
    elif [ "$__mode" == "eager" ]; then
       MODE=""
    else
       echo "Invalid mode:"$__mode""
       help
       exit 1
    fi
else
    MODE="--run-trace-mode"
    __mode="trace"
fi

SCRIPT_FULL_PATH=$(realpath $0)
SCRIPT_DIR_PATH=$(dirname ${SCRIPT_FULL_PATH})

if [ -n "$__dtype" ]; then
    if [ "$__dtype" == "bf16" ]; then
       DTYPE="--hmp"
       DTYPE+=" --hmp-bf16=$SCRIPT_DIR_PATH/configs/ops_bf16_Resnet.txt"
       DTYPE+=" --hmp-fp32=$SCRIPT_DIR_PATH/configs/ops_fp32_Resnet.txt"
    elif [ "$__dtype" == "fp32" ]; then
       DTYPE=""
    else
       echo "Invalid data type:"$__dtype""
       help
       exit 1
    fi
else
    DTYPE=""
    __dtype="fp32"
fi


echo -e "Train ResNet with below parameters:"
echo -e "Model: ${MODEL}"
echo -e "batch_size: ${BATCH_SIZE}"
echo -e "epochs: ${EPOCHS}"
echo -e "data_type: "${__dtype}""
echo -e "Mode: $__mode"
echo -e "world_size: ${WORLD_SIZE}"

printf "*** Starting training...\n\n"
(set -x;  ${INTERPRETER} resnet/train.py \
	--data-path=${DATA_PATH} \
	--model=${MODEL} \
	--device=${DEVICE} \
	--batch-size=${BATCH_SIZE} \
	--epochs=${EPOCHS} \
	--workers=${WORKERS} \
	--print-freq=${PRINT_FREQ} \
    $MODE \
    $DTYPE)
