// Autogenerated file by gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "hpu_ops/backend/reduction_template.h"
#include "prod.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Genprod_int_out : ReductionBackendTemplate {
  Genprod_int_out(int device_id, c10::ScalarType scalar_type) :
      ReductionBackendTemplate(device_id, "reduce_prod_multi_dim_fwd", scalar_type, {}, {}, {}, true) {
        SetReductionVarsIndices(1, 2, 3);
        if (GET_ENV_FLAG_NEW(PT_HPU_LAZY_MODE) != 1) SetOutputMetaFn(ReductionMeta<1, 2, 3>);
  }
};



static const auto& kr_gen_6 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::prod.int_out", Genprod_int_out)
;




}  // namespace habana

