// Autogenerated file by gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "hpu_ops/backend/reduction_template.h"
#include "clone.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Genclone : OpBackend {
  Genclone(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "identity", scalar_type, {0}, {}, {}, false) {
        setNoComputeFlag();
        SetOutputMetaFn(CloneMeta);
  }
};



static const auto& kr_gen_6 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::clone", Genclone)
;




}  // namespace habana

