// Autogenerated file by run_gen_op.py. Do not edit directly!
#include "hpu_ops/cpu_fallback.h"
#include "hpu_ops/op_validator.h"
#include "hpu_ops/op_logger.h"
#include "common/dump_args.h"
#include "habana_eager/eager_exec.h"
#include "habana_eager/ops/eager_op.h"
#include "habana_eager/ops/override_fns.h"
//NOLINTBEGIN(hicpp-deprecated-headers,modernize-deprecated-headers)
#include "ind2ptr.h"
//NOLINTEND(hicpp-deprecated-headers,modernize-deprecated-headers)


using habana_helpers::DTypeHelper; // NOLINT(misc-unused-using-decls)
using synapse_helpers::graph; // NOLINT(misc-unused-using-decls)
using torch::jit::Stack;


namespace habana {

static CheckNodeWithSharedLayerValidator validator_ind2ptr("ind2ptr", "ind2ptr", {0}, {}, Ind2ptrMeta, {}, false, false, false, false);


at::Tensor ind2ptr(at::Tensor ind, int64_t M) {
  PT_EAGER_TRACE;
  PT_OP_INFO("ind2ptr: ", DUMP_2ARGS(ind, M));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  VAL_FAIL_CUSTOM_IF_UNSUPPORTED_DTYPE(ind2ptr, true, ind, M)

  eager::EagerOp<at::Tensor> hpu_op{"torch_sparse::ind2ptr", {ind, M}};
  hpu_op.SetOutputMetaFn(Ind2ptrMeta);
  hpu_op.set_eager_op_info({eager::eagerOpKind::OutOfPlace, "torch_sparse::ind2ptr", require_h2d, require_st, decltype(eager::EagerOpMetaData::out_indices_){}});
  return hpu_op.call();
}





static const auto& kr_gen_torch_sparse = KernelRegistry()
;

TORCH_LIBRARY_IMPL(torch_sparse, HPU, m) {
  m.impl("ind2ptr", habana::ind2ptr);

}



}  // namespace habana

