// Autogenerated file by run_gen_op.py. Do not edit directly!
#include "hpu_ops/cpu_fallback.h"
#include "hpu_ops/op_validator.h"
#include "hpu_ops/op_logger.h"
#include "common/dump_args.h"
#include "habana_eager/eager_exec.h"
#include "habana_eager/ops/eager_op.h"
#include "habana_eager/ops/override_fns.h"
//NOLINTBEGIN(hicpp-deprecated-headers,modernize-deprecated-headers)
#include "eq.h"
//NOLINTEND(hicpp-deprecated-headers,modernize-deprecated-headers)


using habana_helpers::DTypeHelper; // NOLINT(misc-unused-using-decls)
using synapse_helpers::graph; // NOLINT(misc-unused-using-decls)
using torch::jit::Stack;


namespace habana {

static CheckNodeWithSharedLayerValidator validator_eq_Scalar_out("eq.Scalar_out", "equal_fwd", {-1}, {1}, CompareMeta, {0, 1}, false, false, false, true);


at::Tensor & eq_Scalar_out(const at::Tensor & self, const at::Scalar & other, at::Tensor & out) {
  PT_EAGER_TRACE;
  PT_OP_INFO("eq_out: ", DUMP_3ARGS(self, other, out));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  auto compute_type = DTypeHelper::get_compute_dtype({self, other}, out, DTypeHelper::DtypePromoteVariant::kPromoteToCommon, false/*safe_cast*/);
  static_cast<void>(compute_type);

  VAL_FALLBACK_IF_UNSUPPORTED_DTYPE2(eq, Scalar_out, true, self, other, out)

  eager::EagerOp<at::Tensor &> hpu_op{"aten::eq", {self, other, out}};
  hpu_op.set_scalar_types({compute_type});
  hpu_op.SetOutputMetaFn(CompareMeta);
  hpu_op.set_eager_op_info({eager::eagerOpKind::InplaceOut, "aten::eq", require_h2d, require_st, 1});
  return hpu_op.call(out);
}





static const auto& kr_gen_8 = KernelRegistry()
;

TORCH_LIBRARY_IMPL(aten, HPU, m) {
  m.impl("eq.Scalar_out", habana::eq_Scalar_out);

}



}  // namespace habana

