launchers:
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_cpp_suite
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_py_suite_lazy
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_py_suite_compile
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_py_suite_eager
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_sim_cpp_suite
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_sim_py_suite_lazy
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_sim_py_suite_compile
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_sim_py_suite_eager
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi3_sim_cpp_suite
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi3_sim_py_suite_compile
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi3_sim_py_suite_eager
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_asic_topology_functionality
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
  - repository: lightning-habana-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_topology_functionality
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
  - repository: lightning-habana-fork
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_topology_group_1
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
  - repository: lightning-habana-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_topology_group_2
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
  - repository: lightning-habana-fork
- testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi_sim_pt_small_models_test
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi2_sim_pt_small_models_test
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi_sim_pt_distributed_ci
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi2_sim_pt_distributed_ci
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_distributed
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_promote_training_suite
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
  - repository: pytorch-vision-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_promote_training_suite
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
  - repository: pytorch-vision-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_single_op_dynamic
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
  - repository: pytorch-vision-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_promote_compile
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
  - repository: pytorch-vision-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_promote_compile
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
  - repository: pytorch-vision-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_promote_compile
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
  - repository: pytorch-vision-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_promote_eager
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
  - repository: pytorch-vision-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_promote_eager
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
  - repository: pytorch-vision-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_precommit_compile_dynamic
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
  - repository: pytorch-vision-fork
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_promote_training_suite_dtype
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_lightning_habana_uts
  silentMode: false
  gerritTriggerMap:
  - repository: lightning-habana-fork
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_asic_lightning_habana_uts
  silentMode: false
  gerritTriggerMap:
  - repository: lightning-habana-fork
- testToLaunch: pt_next/Test_dependent_Build_pt_next_u22
  gerritTriggerMap:
  - repository: pytorch-integration
# - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_promote_eager_2.n
#   silentMode: false
#   gerritTriggerMap:
#   - repository: pytorch-integration
#   - repository: pytorch-vision-fork
# - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_promote_eager_2.n
#   silentMode: false
#   gerritTriggerMap:
#   - repository: pytorch-integration
#   - repository: pytorch-vision-fork
