launchers:
- testToLaunch: Test_pytorch_gaudi_sim_cpp
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: asic_gaudi_pytorch_perf_tests---t-dg
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: asic_gaudi_pytorch_sbs_tests---t-dg
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: sim_gaudi_pytorch_single_op_tests---t-dg
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: asic_gaudi_pytorch_topology_tests---t-dg
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
  - repository: jenkins_files
    isStable: true
    files:
      - "asic_gaudi_pytorch_topology_tests---t-dg.jenkinsfile"
- testToLaunch: gaudi_pytorch_distributed_tests---t-dg
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
  - repository: jenkins_files
    isStable: true
    files:
      - "gaudi_pytorch_distributed_tests---t-dg.jenkinsfile"
- testToLaunch: Test_pytorch_gaudi_sim_single_op_dynamic_tests
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
  - repository: jenkins_files
    isStable: true
    files:
    - 'sim_pytorch_single_op_tests---t-dg.jenkinsfile'
- testToLaunch: Test_pytorch_gaudi2_sim_single_op_dynamic_tests
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
  - repository: jenkins_files
    isStable: true
    files:
    - 'sim_pytorch_single_op_tests---t-dg.jenkinsfile'
- testToLaunch: Test_pytorch_gaudi2_sim_single_op
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: Test_pytorch_gaudi2_asic_smoke_topology
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: Test_pytorch_gaudi2_asic_perf
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: Test_pytorch_greco_sim_cpp
  silentMode: true
  gerritTriggerMap:
  - repository: jenkins_files
    isStable: true
    files:
    - 'sim_pytorch_tests---t-dg.jenkinsfile'
- testToLaunch: Test_pytorch_gaudi2_sim_cpp
  silentMode: true
  gerritTriggerMap:
  - repository: jenkins_files
    isStable: true
    files:
    - 'sim_pytorch_tests---t-dg.jenkinsfile'
