launchers:
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_cpp_suite
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
# Test_pytorch_modules_gaudi2_asic_cpp_suite to be replaced by Test_pytorch_modules_gaudi2_sim_cpp_suite - https://jira.habana-labs.com/browse/SW-124229
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_cpp_suite
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_asic_topology
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_topology
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi_sim_pt_small_models_test
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi2_sim_pt_small_models_test
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi_sim_pt_distributed_ci
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi2_sim_pt_distributed_ci
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_distributed
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_distributed
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_distributed
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_promote_training_suite
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_promote_training_suite
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_single_op_dynamic
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_promote_compile
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_promote_compile
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_promote_compile
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_promote_eager
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_promote_eager
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_promote_training_suite_dtype
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_8cards_ptl_fw_uts
  silentMode: true
  gerritTriggerMap:
  - repository: pytorch-lightning-fork
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_asic_8cards_ptl_fw_uts
  silentMode: true
  gerritTriggerMap:
  - repository: pytorch-lightning-fork
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_ptl_plugin_uts
  silentMode: true
  gerritTriggerMap:
  - repository: Habana-Lightning-Plugins
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_asic_ptl_plugin_uts
  silentMode: true
  gerritTriggerMap:
  - repository: Habana-Lightning-Plugins
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_8cards_lightning_habana_uts
  silentMode: true
  gerritTriggerMap:
  - repository: lightning-habana-fork
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_asic_8cards_lightning_habana_uts
  silentMode: true
  gerritTriggerMap:
  - repository: lightning-habana-fork
