launchers:
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_greco_sim_cpp_suite
  silentMode: true
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_cpp_suite
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: asic_gaudi_pytorch_sbs_tests---t-dg
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_single_op
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: asic_gaudi_pytorch_topology_tests---t-dg
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
  - repository: jenkins_files
    isStable: true
    files:
      - "asic_gaudi_pytorch_topology_tests---t-dg.jenkinsfile"
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_distributed
  silentMode: false
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_single_op_dynamic
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_single_op_dynamic
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_single_op
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: Test_pytorch_gaudi2_asic_smoke_topology
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: Test_pytorch_gaudi2_asic_perf
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_cpp_suite
  silentMode: true
  gerritTriggerMap:
  - repository: pytorch-fork
  - repository: pytorch-lightning-fork
  - repository: pytorch-vision-fork
  - repository: pytorch-integration
- testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi2_sim_test
  silentMode: true
  gerritTriggerMap:
    - repository: pytorch-fork
    - repository: pytorch-integration