// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "eq.h"
#include "squeeze.h"


using habana_helpers::DTypeHelper; // NOLINT(misc-unused-using-decls)
using synapse_helpers::graph; // NOLINT(misc-unused-using-decls)
using torch::jit::Stack;


namespace habana {





struct Gen_squeeze_dims : SqueezeDims {
  Gen_squeeze_dims(int device_id, c10::ScalarType scalar_type) :
      SqueezeDims(device_id, "squeeze", scalar_type, {0}, {}, {}, false) {
        SetOutputMetaFn(SqueezeDimsMeta);
  }
};

struct Gen_eq_Scalar_out : OpBackend {
  Gen_eq_Scalar_out(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "equal_fwd", scalar_type, {}, {}, {1}, true) {
        SetOutputMetaFn(CompareMeta);
        EnableTypePromotion();
        HandleBoolInputs();
  }
};



static const auto& kr_gen_6 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::squeeze.dims", Gen_squeeze_dims)
.REGISTER_HPU_BACKEND("aten::eq.Scalar_out", Gen_eq_Scalar_out)
;




}  // namespace habana

