// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/cpu_fallback.h"
#include "hpu_ops/op_validator.h"
#include "hpu_ops/op_logger.h"
#include "common/dump_args.h"
#include "habana_kernels/lazy_kernels_declarations.h"
#include "habana_kernels/lazy_kernels.h"
#include "habana_lazy/hpu_stage_submission.h"
using habana_lazy::LazyOp;

//NOLINTBEGIN(hicpp-deprecated-headers,modernize-deprecated-headers)
#include "eq.h"
#include "squeeze.h"
//NOLINTEND(hicpp-deprecated-headers,modernize-deprecated-headers)


using habana_helpers::DTypeHelper; // NOLINT(misc-unused-using-decls)
using synapse_helpers::graph; // NOLINT(misc-unused-using-decls)
using torch::jit::Stack;


namespace habana {

CheckNodeWithSharedLayerValidator validator_eq_Scalar_out("eq.Scalar_out", "equal_fwd", {-1}, {1}, CompareMeta, {0, 1}, false, false, false, true);


at::Tensor squeeze_dims(const at::Tensor & self, at::IntArrayRef dim) {
  PT_LAZY_OP_TRACE;
  PT_LAZY_TRACE;
  PT_OP_INFO("squeeze: ", DUMP_2ARGS(self, dim));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  HPU_SUPPORTED_DTYPES(({at::kBFloat16, at::kFloat, at::kInt, at::kFloat8_e5m2, at::kFloat8_e4m3fn, at::kDouble}))
  FALLBACK_IF_UNSUPPORTED_DTYPE2(self, squeeze, dims, self, dim)

  return habana_lazy::squeeze_dims_hpu_lazy(self, dim);
}

at::Tensor & eq_Scalar_out(const at::Tensor & self, const at::Scalar & other, at::Tensor & out) {
  PT_LAZY_OP_TRACE;
  PT_LAZY_TRACE;
  PT_OP_INFO("eq_out: ", DUMP_3ARGS(self, other, out));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  auto compute_type = DTypeHelper::get_compute_dtype({self, other}, out, DTypeHelper::DtypePromoteVariant::kPromoteToCommon, false/*safe_cast*/);
  static_cast<void>(compute_type);

  VAL_FALLBACK_IF_UNSUPPORTED_DTYPE2(eq, Scalar_out, false, self, other, out)

  LazyOp<at::Tensor &> hpu_op{"aten::eq", {self, other, out}};
  hpu_op.set_scalar_types({compute_type});
  hpu_op.SetOutputMetaFn(CompareMeta);
  RUN_INPLACE_MAYBE_WITH_ACC_THREAD(eq_out, hpu_op, out);
}





static const auto& kr_gen_6 = KernelRegistry()
;

TORCH_LIBRARY_IMPL(aten, HPU, m) {
  m.impl("squeeze.dims", habana::squeeze_dims);
  m.impl("eq.Scalar_out", habana::eq_Scalar_out);

}



}  // namespace habana

