// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/cpu_fallback.h"
#include "hpu_ops/op_validator.h"
#include "hpu_ops/op_logger.h"
#include "common/dump_args.h"
#include "habana_kernels/lazy_custom_op_declarations.h"
#include "habana_kernels/lazy_kernels.h"
#include "habana_lazy/hpu_stage_submission.h"
using habana_lazy::LazyOp;
using habana_lazy::GraphHashBuilder;

#include "ind2ptr.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {

CheckNodeWithSharedLayerValidator validator_ind2ptr("ind2ptr", "ind2ptr", {0}, {}, Ind2ptrMeta, {}, false, false, false, false);


at::Tensor ind2ptr(at::Tensor ind, int64_t M) {
  PT_LAZY_OP_TRACE;
  PT_LAZY_TRACE;
  PT_OP_INFO("ind2ptr: ", DUMP_2ARGS(ind, M));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  VAL_FAIL_CUSTOM_IF_UNSUPPORTED_DTYPE(ind2ptr, false, ind, M)

  LazyOp<at::Tensor> hpu_op{"torch_sparse::ind2ptr", {ind, M}};
  hpu_op.SetOutputMetaFn(Ind2ptrMeta);
  RUN_MAYBE_WITH_ACC_THREAD(ind2ptr, hpu_op);
}





static const auto& kr_gen__torch_sparse = KernelRegistry()
;

TORCH_LIBRARY_IMPL(torch_sparse, HPU, m) {
  m.impl("ind2ptr", habana::ind2ptr);

}



}  // namespace habana

