// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/cpu_fallback.h"
#include "hpu_ops/op_validator.h"
#include "hpu_ops/op_logger.h"
#include "common/dump_args.h"
#include "habana_kernels/lazy_kernels_declarations.h"
#include "habana_kernels/lazy_kernels.h"
#include "habana_lazy/hpu_stage_submission.h"
using habana_lazy::LazyOp;
using habana_lazy::GraphHashBuilder;

#include "eq.h"
#include "isfinite.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {

CheckNodeWithSharedLayerValidator validator_eq_Tensor_out("eq.Tensor_out", "equal_fwd", {-1}, {}, CompareMeta, {0, 1}, false, false, false, true);


at::Tensor & eq_out(const at::Tensor & self, const at::Tensor & other, at::Tensor & out) {
  PT_LAZY_OP_TRACE;
  PT_LAZY_TRACE;
  PT_OP_INFO("eq_out: ", DUMP_3ARGS(self, other, out));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  auto compute_type = DTypeHelper::get_compute_dtype({self, other}, out, DTypeHelper::DtypePromoteVariant::kPromoteToCommon, false/*safe_cast*/);
  static_cast<void>(compute_type);

  VAL_FALLBACK_IF_UNSUPPORTED_DTYPE2(eq, Tensor_out, false, self, other, out)

  LazyOp<at::Tensor &> hpu_op{"aten::eq", {self, other, out}};
  hpu_op.set_scalar_types({compute_type});
  hpu_op.SetOutputMetaFn(CompareMeta);
  RUN_INPLACE_MAYBE_WITH_ACC_THREAD(eq_out, hpu_op, out);
}

at::Tensor isfinite(const at::Tensor & self) {
  PT_LAZY_OP_TRACE;
  PT_LAZY_TRACE;
  PT_OP_INFO("isfinite: ", DUMP_ARG(self));

  [[maybe_unused]] bool require_h2d = false;
  [[maybe_unused]] bool require_st = false;

  HPU_SUPPORTED_DTYPES(({at::kBFloat16, at::kFloat, at::kHalf, at::kInt, at::kDouble}))
  FALLBACK_IF_UNSUPPORTED_DTYPE(self, isfinite, self)

  LazyOp<at::Tensor> hpu_op{"aten::isfinite", {self}};
  RUN_MAYBE_WITH_ACC_THREAD(isfinite, hpu_op);
}





static const auto& kr_gen_7 = KernelRegistry()
;

TORCH_LIBRARY_IMPL(aten, HPU, m) {
  m.impl("eq.Tensor_out", static_cast<at::Tensor & (*)(const at::Tensor &, const at::Tensor &, at::Tensor &)>(&habana::eq_out));
  m.impl("isfinite", static_cast<at::Tensor (*)(const at::Tensor &)>(&habana::isfinite));

}



}  // namespace habana

