// Autogenerated file by gen_op.py. Do not edit directly!

#include <torch/extension.h>
#include <pybind11/stl.h>
#include <pybind11/pybind11.h>
#include <torch/csrc/jit/tensorexpr/tensorexpr_init.h>
#include <torch/csrc/jit/python/pybind_utils.h>
#include <tuple>
#include "cpu_fallback.h"

using habana_helpers::DTypeHelper;
using namespace torch::jit;


namespace habana {

static CheckNodeWithSharedLayerValidator validator_elu("elu", "elu_fwd", nullptr, nullptr, false, false, false, false, false, SupportedDtypes({{{{-1, {at::ScalarType::BFloat16, at::ScalarType::Float, at::ScalarType::Half, at::ScalarType::Double}}}}}));


struct shared_layer_elu : SharedLayerOp {
bool func(torch::jit::Stack &stack, bool is_dynamic) {
  if (stack.size() == 4) {
    auto ivalue_arr = torch::jit::last(stack, 4);
    if (ivalue_arr[0].isTensor() && ivalue_arr[1].isScalar() && ivalue_arr[2].isScalar() && ivalue_arr[3].isScalar() ) {

    	c10::IValue self = std::move(peek(stack, 0, 4));
      c10::IValue alpha = std::move(peek(stack, 1, 4));
      c10::IValue scale = std::move(peek(stack, 2, 4));
      c10::IValue input_scale = std::move(peek(stack, 3, 4));
      
      at::Tensor self_base = self.to<at::Tensor>();
      at::Scalar alpha_base = alpha.to<at::Scalar>();
      at::Scalar scale_base = scale.to<at::Scalar>();
      at::Scalar input_scale_base = input_scale.to<at::Scalar>();
      auto is_supported = impl(self_base, alpha_base, scale_base, input_scale_base, is_dynamic);
      return is_supported;
    }
  }
  return false;
}
private:
bool impl(const at::Tensor & self, const at::Scalar & alpha, const at::Scalar & scale, const at::Scalar & input_scale, bool is_dynamic) {
  VAL_RETURN_IF_UNSUPPORTED_DTYPE(self, elu, is_dynamic, self, alpha, scale, input_scale)

  return true;
}

};





}  // namespace habana

