/******************************************************************************
 * Copyright (C) 2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 *
 ******************************************************************************
 */

#include <ATen/ExpandUtils.h>
#include <perf_lib_layer_params.h>
#include <torch/script.h>
#include <memory>

#include "habana_device/HPUCheck.h"
#include "habana_device/hpu_cached_devices.h"
#include "habana_helpers/tensor_utils.h"
#include "habana_helpers/unused_macro.h"
#include "habana_kernels/kernel_utils.h"
#include "habana_kernels/resize.h"
#include "habana_kernels/simple_generic_kernel.h"

using namespace torch;

/**********************************************************************
*@brief Changes dimensions of the input tensor as per specified dimension.
*This is done by adding dummy x1 dimensions. Eg: NC -> NCHW is done by
* resizing to NxCx1x1. Resizing is done inplace
@param input - Tensor, 2D/3D/4D, float/bf16
@param num_out_dim - uint, Range ~[2,4]
***********************************************************************/

void batch_norm_resize(Tensor& input, uint num_out_dim) {
  auto num_in_dim = input.dim();

  auto shape = DimVector(input.sizes());
  auto tht_input = input.unsafeGetTensorImpl();

  if (num_out_dim >= num_in_dim) {
    for (uint cnt = 0; cnt < (num_out_dim - num_in_dim); cnt++) {
      shape.push_back(1);
    }

    THHTensor_resizeNd(tht_input, num_out_dim, shape.data(), nullptr);
  } else {
    // Remove the additional x1 dimensions
    std::vector<int64_t> new_shape;
    for (uint cnt = 0; cnt < num_out_dim; cnt++) {
      new_shape.push_back(shape[cnt]);
    }

    THHTensor_resizeNd(tht_input, num_out_dim, new_shape.data(), nullptr);
  }
}

/**********************************************************************
*@brief Pushes the optional tensor to device if defined.Otherwise,
* create an empty device tensor
@param input - Optional 1D tensor
@param size - size of 1D tensor. used in case the tensor is not defined
@param device - Device param
@param output - 1D HPU tensor
**********************************************************************/

inline Tensor get_batch_norm_optional_tensors(
    const Tensor& input,
    uint size,
    Device device) {
  Tensor output;
  if (input.defined() == true) {
    output = input.to(DeviceType::HABANA);
  } else {
    output = at::empty(
        {size}, TensorOptions().dtype(c10::ScalarType::Float).device(device));
  }
  return output;
}

/*******************************************************************
*@brief Implements forward pass for batch norm
*INPUTS
@param input - IFM, 2D/3D/4D, bf16/FP32, NHWC
@param weight - Gamma in PyT, 1D, FP32, C (optional)
@param bias - beta in PyT, 1D, FP32, C (optional)
@param running_mean - Filtered mean 1D, FP32, C (optional)
@param running_var - Filtered variance, 1D, FP32, C (optional)
@param momentum - Update factor, float
@param eps - float (for numerical stability during
divisions)
*OUTPUTS
@param output - OFM, 2D/3D/4D, bf16/FP32, NHWC
@param running_mean_out - Updated filtered mean 1D, FP32, C
@param running_var_out - Updated filtered variance 1D, FP32, C
*UNUSED variables will be enabled later once evaluation/inference mode is
*implemented
*******************************************************************/

std::tuple<Tensor, Tensor, Tensor> batch_norm_hpu(
    const Tensor& input,
    const Tensor& weight,
    const Tensor& bias,
    const Tensor& running_mean,
    const Tensor& running_var,
    bool training,
    double momentum,
    double eps) {
  LOG_FUNC_BEGIN;

  auto num_input_dim = input.dim();

  TORCH_CHECK(num_input_dim > 1, "Expected range of input dimensions is [2,4]");

  // Resize input to 4D to match TPC kernel requirement.
  auto input_resize = input;
  batch_norm_resize(input_resize, 4);

  // Permute to match synapse layout
  auto input_nhwc = input_resize.permute({0, 2, 3, 1});

  // The following tensors are autogenerated by pytorch. Hence need to be
  // pushed to device first. The below operations can be removed in graph
  // mode when the intermediate tensors lives in the device
  // AFAIK, in training mode, all the optional tensors are received.
  // Nevertheless, if we don't receive the optional tensors from PyT, create
  // empty ones to satify TPC kernel input constraints

  Tensor wt_hpu =
      get_batch_norm_optional_tensors(weight, input.sizes()[1], input.device());

  Tensor bias_hpu =
      get_batch_norm_optional_tensors(bias, input.sizes()[1], input.device());

  Tensor running_mean_hpu = get_batch_norm_optional_tensors(
      running_mean, input.sizes()[1], input.device());

  Tensor running_var_hpu = get_batch_norm_optional_tensors(
      running_var, input.sizes()[1], input.device());

  auto current_mean =
      at::empty(running_mean_hpu.sizes(), running_mean_hpu.options());
  auto current_istd =
      at::empty(running_mean_hpu.sizes(), running_mean_hpu.options());

  auto output_nhwc = at::empty(input_nhwc.sizes(), input_nhwc.options());
  std::vector<const at::Tensor*> pt_outputs{&output_nhwc};

  if (training == true) {
    std::vector<const at::Tensor*> pt_inputs{
        &input_nhwc,
        &wt_hpu,
        &bias_hpu,
    };

    Tensor running_mean_hpu_in, running_var_hpu_in, residualAdd;

    if (running_mean.defined()) {
      running_mean_hpu_in =
          at::empty(running_mean_hpu.sizes(), running_mean_hpu.options());

      running_var_hpu_in =
          at::empty(running_var_hpu.sizes(), running_var_hpu.options());

      residualAdd = at::empty(input_nhwc.sizes(), input_nhwc.options());

      // This residual add is dummy tensor to match the API requirements
      pt_inputs.push_back(&residualAdd);

      // running mean and running var cannot be in input and output list
      // simultaneously. create a copy
      habana_helpers::copy_data_within_device(
          running_mean_hpu, running_mean_hpu_in);

      habana_helpers::copy_data_within_device(
          running_var_hpu, running_var_hpu_in);

      pt_inputs.push_back(&running_mean_hpu_in);
      pt_inputs.push_back(&running_var_hpu_in);

      pt_outputs.push_back(&running_mean_hpu);
      pt_outputs.push_back(&running_var_hpu);

      pt_outputs.push_back(&current_mean);
      pt_outputs.push_back(&current_istd);
    }

    // synapse uses expAvgfactor = 1 - momentum
    struct synCudBnExParams param = {synBnOps::BN_OPS_BN,
                                     static_cast<float>(1 - momentum),
                                     static_cast<float>(eps)};

    synapse_simple_generic_kernel(
        pt_outputs,
        pt_inputs,
        "cud_bn_fwd_ex",
        &param,
        sizeof(param),
        SynapsePassType::NO_PASS);
  } else {
    // training=false - Evaluation mode
    std::vector<const at::Tensor*> pt_inputs{
        &input_nhwc,
        &bias_hpu,
        &wt_hpu,
        &running_mean_hpu,
        &running_var_hpu,
    };

    struct ns_BatchNormKernel::Params param;
    param.threshold.f = 0.0;
    param.momentum = momentum;
    param.epsilon = eps;

    synapse_simple_generic_kernel(
        pt_outputs,
        pt_inputs,
        "batch_norm_inf",
        &param,
        sizeof(param),
        SynapsePassType::NO_PASS);
  }

  // NHWC -> NCHW to match PyT layout
  auto output = output_nhwc.permute({0, 3, 1, 2});

  // Resize output
  batch_norm_resize(output, num_input_dim);

  LOG_FUNC_END;

  return std::make_tuple(output, current_mean, current_istd);
}

/*******************************************************************
*@brief Implements backward pass for batch norm
*INPUTS
@param grad_out - output gradient tensor, 2D/3D/4D, bf16/FP32, NHWC
@param input - IFM, 2D/3D/4D, bf16/FP32, NHWC
@param weight - Gamma in PyT, 1D, FP32, C (optional)
@param running_mean - Filtered mean 1D, FP32, C (optional)
@param running_var - Filtered variance, 1D, FP32, C (optional)
@param save_mean - saved mean from fwd pass, 1D, FP32, C
@param save_invstd - saved inverse variance from fwd pass, 1D, FP32, C

*OUTPUTS
@param grad_in - input gradient tensor, 2D/3D/4D, bf16/FP32, NHWC
@param grad_gamma - gradient of weight 1D, FP32, C
@param grad_beta - gradient of bias 1D, FP32, C
*UNUSED variables will be enabled later once evaluation/inference mode is
*implemented
*******************************************************************/
std::tuple<Tensor, Tensor, Tensor> batch_norm_bwd_hpu(
    Tensor& grad_out,
    Tensor& input,
    Tensor& weight,
    UNUSED Tensor& running_mean,
    UNUSED Tensor& running_var,
    Tensor& save_mean,
    Tensor& save_invstd,
    bool train,
    double eps,
    UNUSED bool output_mask[3]) {
  LOG_FUNC_BEGIN;

  auto num_input_dim = input.dim();

  TORCH_CHECK(num_input_dim > 1, "Expected range of input dimensions is [2,4]");
  TORCH_CHECK(
      num_input_dim == grad_out.dim(),
      "Grad out dimension not matching that of input");

  // Resize input and grad in to 4D to match TPC kernel requirement.
  auto input_resize = input;
  batch_norm_resize(input_resize, 4);

  auto grad_out_resize = grad_out;
  batch_norm_resize(grad_out_resize, 4);

  // Permute to match synapse layout
  auto input_nhwc = input_resize.permute({0, 2, 3, 1});
  auto grad_out_nhwc = grad_out_resize.permute({0, 2, 3, 1});

  Tensor wt_hpu =
      get_batch_norm_optional_tensors(weight, input.sizes()[1], input.device());
  Tensor bias_hpu = at::zeros(wt_hpu.sizes(), wt_hpu.options());
  Tensor save_mean_hpu = get_batch_norm_optional_tensors(
      save_mean, input.sizes()[1], input.device());
  Tensor save_invstd_hpu = get_batch_norm_optional_tensors(
      save_invstd, input.sizes()[1], input.device());

  std::vector<const at::Tensor*> pt_inputs{
      &input_nhwc,
      &grad_out_nhwc,
      &wt_hpu,
      &bias_hpu,
      &save_mean_hpu,
      &save_invstd_hpu,
  };

  // Prepare output tensor vector
  auto grad_in_nhwc = at::empty(input_nhwc.sizes(), input_nhwc.options());
  auto grad_beta = at::empty(wt_hpu.sizes(), wt_hpu.options());
  auto grad_gamma = at::empty(wt_hpu.sizes(), wt_hpu.options());

  std::vector<const at::Tensor*> pt_outputs{
      &grad_in_nhwc, &grad_gamma, &grad_beta};

  struct synCudBnExParams param = {
      synBnOps::BN_OPS_BN, 0, static_cast<float>(eps)};

  synapse_simple_generic_kernel(
      pt_outputs,
      pt_inputs,
      "cud_bn_bwd_ex",
      &param,
      sizeof(param),
      SynapsePassType::NO_PASS);

  // NHWC -> NCHW to match PyT layout
  auto grad_in = grad_in_nhwc.permute({0, 3, 1, 2});

  // Resize output
  batch_norm_resize(grad_in, num_input_dim);

  LOG_FUNC_END;

  return std::make_tuple(grad_in, grad_gamma, grad_beta);
}

static auto registry =
    torch::RegisterOperators()
        .op(torch::RegisterOperators::options()
                .schema(
                    "aten::native_batch_norm(Tensor input, Tensor? weight, Tensor? bias, Tensor? running_mean, Tensor? running_var, bool training, float momentum, float eps) -> (Tensor, Tensor, Tensor)")
                .impl_unboxedOnlyKernel<
                    decltype(batch_norm_hpu),
                    &batch_norm_hpu>(DispatchKey::HABANATensorId)
                .aliasAnalysis(c10::AliasAnalysisKind::FROM_SCHEMA))
        .op(torch::RegisterOperators::options()
                .schema(
                    "aten::native_batch_norm_backward(Tensor grad_out, Tensor input, Tensor? weight, Tensor? running_mean, Tensor? running_var, Tensor? save_mean, Tensor? save_invstd, bool train, float eps, bool[3] output_mask) -> (Tensor, Tensor, Tensor)")
                .impl_unboxedOnlyKernel<
                    decltype(batch_norm_bwd_hpu),
                    &batch_norm_bwd_hpu>(DispatchKey::HABANATensorId)
                .aliasAnalysis(c10::AliasAnalysisKind::FROM_SCHEMA));
