/******************************************************************************
 * Copyright (C) 2020 HabanaLabs, Ltd.
 * All Rights Reserved.
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 *
 ******************************************************************************
 */
#pragma once
#include <ATen/ExpandUtils.h>
#include <torch/script.h>

// Class wrapping functions that override functions RegistrationDeclarations.h
// Registration of ops other than custom ones will be autogenerated by
// scripts/gen.py for all the static member functions of this class.

struct hpu_wrap {
  static at::Tensor _copy_from_and_resize(
      const at::Tensor& self,
      const at::Tensor& dst);
  static at::Tensor& silu_out(const at::Tensor& self, at::Tensor& out);
  static at::Tensor cumsum(
      const at::Tensor& self,
      int64_t dim,
      c10::optional<at::ScalarType> dtype);
  inline static at::Tensor& linspace_out(
      const at::Scalar& start,
      const at::Scalar& end,
      c10::optional<int64_t> steps,
      at::Tensor& out);
  static at::Tensor silu(const at::Tensor& self);
  static at::Tensor silu_backward(
      const at::Tensor& grad,
      const at::Tensor& self);
  static at::Tensor isnan(const at::Tensor& self);
  static at::Tensor empty(
      at::IntArrayRef size,
      c10::optional<at::ScalarType> dtype,
      c10::optional<at::Layout> layout,
      c10::optional<at::Device> device,
      c10::optional<bool> pin_memory,
      c10::optional<at::MemoryFormat> optional_memory_format);
  static at::Tensor empty_strided(
      at::IntArrayRef size,
      at::IntArrayRef stride,
      c10::optional<at::ScalarType> dtype,
      c10::optional<at::Layout> layout,
      c10::optional<at::Device> device,
      c10::optional<bool> pin_memory);
  static at::Tensor& fill_(at::Tensor& self, const at::Scalar& value);
  static at::Tensor _to_copy(
      const at::Tensor& self,
      c10::optional<at::ScalarType> dtype,
      c10::optional<at::Layout> layout,
      c10::optional<at::Device> device,
      c10::optional<bool> pin_memory,
      bool non_blocking,
      c10::optional<at::MemoryFormat> memory_format);
  static at::Tensor& copy_(
      at::Tensor& self,
      const at::Tensor& src,
      bool non_blocking);
  static at::Tensor _reshape_alias(
      const at::Tensor& self,
      at::IntArrayRef size,
      at::IntArrayRef stride);
  static at::Tensor as_strided(
      const at::Tensor& self,
      at::IntArrayRef size,
      at::IntArrayRef stride,
      c10::optional<int64_t> storage_offset);
  static at::Tensor& set_(
      at::Tensor& self,
      at::Storage source,
      int64_t storage_offset,
      at::IntArrayRef size,
      at::IntArrayRef stride);
  static at::Tensor& zero_(at::Tensor& self);
  static ::std::tuple<at::Tensor, at::Tensor> sort(
      const at::Tensor& self,
      int64_t dim,
      bool descending);
  static at::Tensor add(
      const at::Tensor& self,
      const at::Tensor& other,
      const at::Scalar& alpha);
  static at::Tensor add(
      const at::Tensor& self,
      const at::Scalar& other,
      const at::Scalar& alpha);
  static at::Tensor view(const at::Tensor& self, at::IntArrayRef size);
  static at::Tensor addcmul(
      const at::Tensor& self,
      const at::Tensor& tensor1,
      const at::Tensor& tensor2,
      const at::Scalar& alpha);
  static at::Tensor& addcmul_(
      at::Tensor& self,
      const at::Tensor& tensor1,
      const at::Tensor& tensor2,
      const at::Scalar& alpha);
  static at::Tensor addcdiv(
      const at::Tensor& self,
      const at::Tensor& tensor1,
      const at::Tensor& tensor2,
      const at::Scalar& alpha);
  static at::Tensor& addcdiv_(
      at::Tensor& self,
      const at::Tensor& tensor1,
      const at::Tensor& tensor2,
      const at::Scalar& alpha);
  static at::Tensor& add_(
      at::Tensor& self,
      const at::Scalar& other,
      const at::Scalar& alpha);
  static at::Tensor& add_(
      at::Tensor& self,
      const at::Tensor& other,
      const at::Scalar& alpha);
  static at::Tensor sub(
      const at::Tensor& self,
      const at::Tensor& other,
      const at::Scalar& alpha);
  static at::Tensor& sub_(
      at::Tensor& self,
      const at::Tensor& other,
      const at::Scalar& alpha);
  static at::Tensor sub(
      const at::Tensor& self,
      const at::Scalar& other,
      const at::Scalar& alpha);
  static at::Tensor& sub_(
      at::Tensor& self,
      const at::Scalar& other,
      const at::Scalar& alpha);
  static at::Tensor rsub(
      const at::Tensor& self,
      const at::Scalar& other,
      const at::Scalar& alpha);
  static at::Tensor& mul_(at::Tensor& self, const at::Tensor& other);
  static at::Tensor& mul_out(

      const at::Tensor& self,
      const at::Tensor& other,
      at::Tensor& out);
  static at::Tensor mul(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor mul(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor& mul_(at::Tensor& self, const at::Scalar& other);
  static at::Tensor div(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor& div_out(

      const at::Tensor& self,
      const at::Tensor& other,
      at::Tensor& result);
  static at::Tensor& div_(at::Tensor& self, const at::Tensor& other);
  static at::Tensor div(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor& div_(at::Tensor& self, const at::Scalar& other);
  static at::Tensor floor_divide(
      const at::Tensor& self,
      const at::Tensor& other);
  static at::Tensor pow(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor& pow_(at::Tensor& self, const at::Tensor& other);
  static at::Tensor pow(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor& pow_(at::Tensor& self, const at::Scalar& other);
  static at::Tensor pow(const at::Scalar& other, const at::Tensor& self);
  static at::Tensor maximum(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor minimum(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor gt(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor gt(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor& eq_out(

      const at::Tensor& self,
      const at::Tensor& other,
      at::Tensor& output);
  static at::Tensor eq(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor eq(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor ne(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor ne(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor all(const at::Tensor& self);
  static at::Tensor all(const at::Tensor& self, int64_t dim, bool keepdim);
  static at::Tensor lt(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor lt(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor ge(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor ge(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor le(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor le(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor convolution_overrideable(
      const at::Tensor& input,
      const at::Tensor& weight,
      const c10::optional<at::Tensor>& bias_opt,
      at::IntArrayRef stride,
      at::IntArrayRef padding,
      at::IntArrayRef dilation,
      bool transposed,
      at::IntArrayRef output_padding,
      int64_t groups);
  static ::std::tuple<at::Tensor, at::Tensor, at::Tensor>
  convolution_backward_overrideable(
      const at::Tensor& grad_output,
      const at::Tensor& input,
      const at::Tensor& weight,
      at::IntArrayRef stride,
      at::IntArrayRef padding,
      at::IntArrayRef dilation,
      bool transposed,
      at::IntArrayRef output_padding,
      int64_t groups,
      ::std::array<bool, 3> output_mask);
  static at::Tensor constant_pad_nd(
      const at::Tensor& self,
      at::IntArrayRef pad,
      const at::Scalar& value);
  static at::Tensor embedding(
      const at::Tensor& weight,
      const at::Tensor& indices,
      int64_t padding_idx,
      bool scale_grad_by_freq,
      bool sparse);
  static at::Tensor embedding_dense_backward(
      const at::Tensor& grad,
      const at::Tensor& indices,
      int64_t num_weights,
      int64_t padding_idx,
      bool scale_grad_by_freq);
  static at::Tensor& masked_fill_(
      at::Tensor& self,
      const at::Tensor& mask,
      const at::Tensor& value);
  static at::Tensor& masked_fill_(
      at::Tensor& self,
      const at::Tensor& mask,
      const at::Scalar& value);
  static at::Tensor masked_select(
      const at::Tensor& self,
      const at::Tensor& mask);
  static at::Tensor& masked_select_out(
      const at::Tensor& self,
      const at::Tensor& mask,
      at::Tensor& out);
  static at::Tensor& masked_scatter_(
      at::Tensor& self,
      const at::Tensor& mask,
      const at::Tensor& source);
  static at::Tensor gather(
      const at::Tensor& self,
      int64_t dim_,
      const at::Tensor& index,
      bool sparse_grad);
  static at::Tensor& scatter_(
      at::Tensor& self,
      int64_t dim_,
      const at::Tensor& index,
      const at::Tensor& src);
  static at::Tensor& scatter_(
      at::Tensor& self,
      int64_t dim_,
      const at::Tensor& index,
      const at::Scalar& value);
  static at::Tensor scatter(
      const at::Tensor& self,
      int64_t dim_,
      const at::Tensor& index,
      const at::Tensor& src);
  static at::Tensor scatter_add(
      const at::Tensor& self,
      int64_t dim_,
      const at::Tensor& index,
      const at::Tensor& src);
  static at::Tensor& scatter_add_(
      at::Tensor& self,
      int64_t dim_,
      const at::Tensor& index,
      const at::Tensor& src);
  inline static at::Tensor& index_add_(
      at::Tensor& self,
      int64_t dim_,
      const at::Tensor& indices,
      const at::Tensor& source,
      const at::Scalar& alpha);
  inline static at::Tensor& index_add_(
      at::Tensor& self,
      int64_t dim_,
      const at::Tensor& indices,
      const at::Tensor& source);
  static at::Tensor index_put(
      const at::Tensor& self,
      const c10::List<c10::optional<at::Tensor>>& indices,
      const at::Tensor& value,
      bool accumulate);
  static at::Tensor index(
      const at::Tensor& self,
      const c10::List<c10::optional<at::Tensor>>& indices);
  static at::Tensor& _index_put_impl_(
      at::Tensor& self,
      const c10::List<c10::optional<at::Tensor>>& indices,
      const at::Tensor& value,
      const bool accumulate,
      const bool unsafe);
  static at::Tensor& index_put_(
      at::Tensor& self,
      const c10::List<c10::optional<at::Tensor>>& indices,
      const at::Tensor& value,
      bool accumulate);
  static at::Tensor index_select(
      const at::Tensor& self,
      int64_t dim,
      const at::Tensor& index);
  static at::Tensor slice(
      const at::Tensor& self,
      int64_t dim,
      c10::optional<int64_t> start,
      c10::optional<int64_t> end,
      int64_t step);
  static at::Tensor select(const at::Tensor& self, int64_t dim, int64_t index);
  static at::Tensor select_backward(
      const at::Tensor& grad,
      at::IntArrayRef input_sizes,
      int64_t dim,
      int64_t index);
  static at::Tensor& arange_out(
      const at::Scalar& start,
      const at::Scalar& end,
      const at::Scalar& step,
      at::Tensor& output);
  static at::Tensor nonzero(const at::Tensor& self);
  static at::Tensor& nonzero_out(const at::Tensor& self, at::Tensor& out);
  static at::Tensor mm(const at::Tensor& mat1, const at::Tensor& mat2);
  static at::Tensor baddbmm(
      const at::Tensor& self,
      const at::Tensor& mat1,
      const at::Tensor& mat2,
      const at::Scalar& beta,
      const at::Scalar& alpha);
  static at::Tensor& baddbmm_out(
      const at::Tensor& self,
      const at::Tensor& mat1,
      const at::Tensor& mat2,
      const at::Scalar& beta,
      const at::Scalar& alpha,
      at::Tensor& out);
  static at::Tensor& baddbmm_(
      at::Tensor& self,
      const at::Tensor& mat1,
      const at::Tensor& mat2,
      const at::Scalar& beta,
      const at::Scalar& alpha);
  static at::Tensor addmm(
      const at::Tensor& self,
      const at::Tensor& mat1,
      const at::Tensor& mat2,
      const at::Scalar& beta,
      const at::Scalar& alpha);
  static at::Tensor& bmm_out(
      const at::Tensor& self,
      const at::Tensor& mat2,
      at::Tensor& out);
  static at::Tensor bmm(const at::Tensor& self, const at::Tensor& mat2);
  static at::Tensor dot(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor mv(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor _s_where(
      const at::Tensor& condition,
      const at::Tensor& self,
      const at::Tensor& other);
  static ::std::tuple<at::Tensor, at::Tensor> nll_loss_forward(
      const at::Tensor& self,
      const at::Tensor& target,
      const c10::optional<at::Tensor>& weight_opt,
      int64_t reduction,
      int64_t ignore_index);
  static at::Tensor nll_loss_backward(
      const at::Tensor& grad_output,
      const at::Tensor& self,
      const at::Tensor& target,
      const c10::optional<at::Tensor>& weight_opt,
      int64_t reduction,
      int64_t ignore_index,
      const at::Tensor& total_weight);
  static ::std::tuple<at::Tensor, at::Tensor> nll_loss2d_forward(
      const at::Tensor& self,
      const at::Tensor& target,
      const c10::optional<at::Tensor>& weight_opt,
      int64_t reduction,
      int64_t ignore_index);
  static at::Tensor nll_loss2d_backward(
      const at::Tensor& grad_output,
      const at::Tensor& self,
      const at::Tensor& target,
      const c10::optional<at::Tensor>& weight_opt,
      int64_t reduction,
      int64_t ignore_index,
      const at::Tensor& total_weight);
  static at::Tensor mse_loss(
      const at::Tensor& self,
      const at::Tensor& target,
      int64_t reduction);
  static at::Tensor mse_loss_backward(
      const at::Tensor& grad_output,
      const at::Tensor& self,
      const at::Tensor& target,
      int64_t reduction);
  static at::Tensor kl_div(
      const at::Tensor& input,
      const at::Tensor& target,
      int64_t reduction,
      bool log_target);
  static at::Tensor kl_div_backward(
      const at::Tensor& grad,
      const at::Tensor& input,
      const at::Tensor& target,
      int64_t reduction,
      bool log_target);
  static at::Tensor binary_cross_entropy(
      const at::Tensor& self,
      const at::Tensor& target,
      const c10::optional<at::Tensor>& weight_opt,
      int64_t reduction);
  static at::Tensor binary_cross_entropy_backward(
      const at::Tensor& grad_output,
      const at::Tensor& self,
      const at::Tensor& target,
      const c10::optional<at::Tensor>& weight_opt,
      int64_t reduction);
  static at::Tensor binary_cross_entropy_with_logits(
      const at::Tensor& self,
      const at::Tensor& target,
      const c10::optional<at::Tensor>& weight,
      const c10::optional<at::Tensor>& pos_weight,
      int64_t reduction);
  static ::std::tuple<at::Tensor, at::Tensor, at::Tensor> native_batch_norm(
      const at::Tensor& input,
      const c10::optional<at::Tensor>& weight_opt,
      const c10::optional<at::Tensor>& bias_opt,
      const c10::optional<at::Tensor>& running_mean_opt,
      const c10::optional<at::Tensor>& running_var_opt,
      bool training,
      double momentum,
      double eps);
  static ::std::tuple<at::Tensor, at::Tensor, at::Tensor>
  native_batch_norm_backward(
      const at::Tensor& grad_out,
      const at::Tensor& input,
      const c10::optional<at::Tensor>& weight_opt,
      const c10::optional<at::Tensor>& running_mean_opt,
      const c10::optional<at::Tensor>& running_var_opt,
      const c10::optional<at::Tensor>& save_mean_opt,
      const c10::optional<at::Tensor>& save_invstd_opt,
      bool train,
      double eps,
      ::std::array<bool, 3> output_mask);
  static ::std::tuple<at::Tensor, at::Tensor, at::Tensor> native_layer_norm(
      const at::Tensor& input,
      at::IntArrayRef normalized_shape,
      const c10::optional<at::Tensor>& weight,
      const c10::optional<at::Tensor>& bias,
      double eps);
  static ::std::tuple<at::Tensor, at::Tensor, at::Tensor>
  native_layer_norm_backward(
      const at::Tensor& grad_out,
      const at::Tensor& input,
      at::IntArrayRef normalized_shape,
      const at::Tensor& mean,
      const at::Tensor& rstd,
      const c10::optional<at::Tensor>& weight,
      const c10::optional<at::Tensor>& bias,
      ::std::array<bool, 3> output_mask);
  static at::Tensor norm(const at::Tensor& self, const at::Scalar& p = 2);
  static at::Tensor norm(
      const at::Tensor& self,
      const c10::optional<at::Scalar>& p,
      at::IntArrayRef dim,
      bool keepdim);
  static at::Tensor norm(
      const at::Tensor& self,
      const c10::optional<at::Scalar>& p,
      at::IntArrayRef dim,
      bool keepdim,
      at::ScalarType dtype);
  static at::Tensor instance_norm(
      const at::Tensor& input,
      const c10::optional<at::Tensor>& weight,
      const c10::optional<at::Tensor>& bias,
      const c10::optional<at::Tensor>& running_mean,
      const c10::optional<at::Tensor>& running_var,
      bool use_input_stats,
      double momentum,
      double eps,
      bool cudnn_enabled);
  static ::std::tuple<at::Tensor, at::Tensor> max_pool2d_with_indices(
      const at::Tensor& input,
      at::IntArrayRef kernel_size,
      at::IntArrayRef stride,
      at::IntArrayRef padding,
      at::IntArrayRef dilation,
      bool ceil_mode);
  at::Tensor& max_pool2d_with_indices_backward_out(
      const at::Tensor& grad_output,
      const at::Tensor& self,
      at::IntArrayRef kernel_size,
      at::IntArrayRef stride,
      at::IntArrayRef padding,
      at::IntArrayRef dilation,
      bool ceil_mode,
      const at::Tensor& indices,
      at::Tensor& grad_input);
  static at::Tensor max_pool2d_with_indices_backward(
      const at::Tensor& grad_output,
      const at::Tensor& input,
      at::IntArrayRef kernel_size,
      at::IntArrayRef stride,
      at::IntArrayRef padding,
      at::IntArrayRef dilation,
      bool ceil_mode,
      const at::Tensor& indices);
  static at::Tensor avg_pool2d(
      const at::Tensor& input,
      at::IntArrayRef kernel_size,
      at::IntArrayRef stride,
      at::IntArrayRef padding,
      bool ceil_mode,
      bool count_include_pad,
      c10::optional<int64_t> divisor_override);
  static at::Tensor& avg_pool2d_backward_out(
      const at::Tensor& grad_output,
      const at::Tensor& self,
      at::IntArrayRef kernel_size,
      at::IntArrayRef stride,
      at::IntArrayRef padding,
      bool ceil_mode,
      bool count_include_pad,
      c10::optional<int64_t> divisor_override,
      at::Tensor& grad_input);
  static at::Tensor avg_pool2d_backward(
      const at::Tensor& grad_output,
      const at::Tensor& input,
      at::IntArrayRef kernel_size,
      at::IntArrayRef stride,
      at::IntArrayRef padding,
      bool ceil_mode,
      bool count_include_pad,
      c10::optional<int64_t> divisor_override);
  static at::Tensor adaptive_avg_pool2d(
      const at::Tensor& self,
      at::IntArrayRef output_size);
  static at::Tensor& uniform_(
      at::Tensor& self,
      double from = 0,
      double to = 1,
      c10::optional<at::Generator> gen = {});
  static at::Tensor& normal_(
      at::Tensor& self,
      double mean = 0,
      double std = 1,
      c10::optional<at::Generator> gen = {});
  static at::Tensor bernoulli(
      const at::Tensor& self,
      c10::optional<at::Generator> gen);
  static at::Tensor& bernoulli_(
      at::Tensor& self,
      double p,
      c10::optional<at::Generator> gen);
  static ::std::tuple<at::Tensor, at::Tensor> _fused_dropout(
      const at::Tensor& self,
      double p,
      c10::optional<at::Generator> gen);
  static at::Tensor dropout(const at::Tensor& input, double p, bool train);
  static at::Tensor& randperm_out(
      int64_t n,
      c10::optional<at::Generator> generator,
      at::Tensor& out);
  static at::Tensor repeat(const at::Tensor& self, at::IntArrayRef repeats);
  static at::Tensor sum(
      const at::Tensor& self,
      at::IntArrayRef dim,
      bool keepdim,
      c10::optional<at::ScalarType> dtype);
  static at::Tensor& sum_out(
      const at::Tensor& self,
      at::IntArrayRef dim,
      bool keepdim,
      c10::optional<at::ScalarType> dtype,
      at::Tensor& output);
  static at::Tensor mean(
      const at::Tensor& self,
      at::IntArrayRef dim,
      bool keepdim,
      c10::optional<at::ScalarType> dtype);
  static at::Tensor& mean_out(
      const at::Tensor& self,
      at::IntArrayRef dim,
      bool keepdim,
      c10::optional<at::ScalarType> dtype,
      at::Tensor& output);
  static at::Tensor sum(
      const at::Tensor& self,
      c10::optional<at::ScalarType> dtype);
  static at::Tensor mean(
      const at::Tensor& self,
      c10::optional<at::ScalarType> dtype);
  static at::Tensor prod(
      const at::Tensor& self,
      c10::optional<at::ScalarType> dtype);
  static at::Tensor prod(
      const at::Tensor& self,
      int64_t dim,
      bool keepdim,
      c10::optional<at::ScalarType> dtype);
  static at::Tensor argmax(
      const at::Tensor& self,
      c10::optional<int64_t> dim,
      bool keepdim);
  static ::std::tuple<at::Tensor, at::Tensor, at::Tensor> _unique2(
      const at::Tensor& self,
      bool sorted,
      bool return_inverse,
      bool return_counts);
  static ::std::tuple<at::Tensor, at::Tensor> max(
      const at::Tensor& self,
      int64_t dim,
      bool keepdim);
  static at::Tensor max(const at::Tensor& self);
  static at::Tensor min(const at::Tensor& self);
  static at::Tensor& any_out(
      const at::Tensor& self,
      int64_t dim,
      bool keepdim,
      at::Tensor& output);
  static at::Tensor any(const at::Tensor& self, int64_t dim, bool keepdim);
  static at::Tensor any(const at::Tensor& self);
  static at::Tensor clone(
      const at::Tensor& self,
      c10::optional<at::MemoryFormat> memory_format);
  static at::Tensor cat(const at::TensorList tensors, int64_t dim_ = 0);
  static at::Tensor& cat_out(
      const at::TensorList tensors,
      int64_t dim_,
      at::Tensor& result);
  static at::Tensor transpose(
      const at::Tensor& self,
      int64_t dim0_,
      int64_t dim1_);
  static at::Tensor t(const at::Tensor& self);
  static at::Tensor permute(const at::Tensor& self, at::IntArrayRef dims_);
  static at::Tensor expand(
      const at::Tensor& self,
      at::IntArrayRef size,
      bool implicit);
  static ::std::vector<at::Tensor> split_with_sizes(
      const at::Tensor& self,
      at::IntArrayRef split_sizes,
      int64_t dim);
  static at::Tensor threshold_backward(
      const at::Tensor& grad_output,
      const at::Tensor& self,
      const at::Scalar& threshold);
  static ::std::tuple<at::Tensor&, at::Tensor&> topk_out(
      const at::Tensor& self,
      int64_t k,
      int64_t dim_,
      bool largest,
      bool sorted,
      at::Tensor& values,
      at::Tensor& indices);
  static ::std::tuple<at::Tensor, at::Tensor> topk(
      const at::Tensor& self,
      int64_t k,
      int64_t dim,
      bool largest,
      bool sorted);
  static at::Tensor elu(
      const at::Tensor& self,
      const at::Scalar& alpha,
      const at::Scalar& scale,
      const at::Scalar& input_scale);
  static at::Tensor& elu_(
      at::Tensor& self,
      const at::Scalar& alpha,
      const at::Scalar& scale,
      const at::Scalar& input_scale);
  static at::Tensor relu(const at::Tensor& input);
  static at::Tensor& relu_(at::Tensor& self);
  static at::Tensor& leaky_relu_(
      at::Tensor& self,
      const at::Scalar& negative_slope);
  static at::Tensor leaky_relu_backward(
      const at::Tensor& grad_output,
      const at::Tensor& self,
      const at::Scalar& negative_slope,
      bool self_is_result);
  static at::Tensor leaky_relu(
      const at::Tensor& self,
      const at::Scalar& negative_slope);
  static at::Tensor sigmoid(const at::Tensor& input);
  static at::Tensor sigmoid_backward(
      const at::Tensor& grad_in,
      const at::Tensor& input);
  static at::Tensor& hardsigmoid_(at::Tensor& self);
  static at::Tensor hardsigmoid(const at::Tensor& self);
  static at::Tensor hardsigmoid_backward(
      const at::Tensor& grad_output,
      const at::Tensor& self);
  static at::Tensor sqrt(const at::Tensor& input);
  static at::Tensor tanh(const at::Tensor& input);
  static at::Tensor& tanh_(at::Tensor& self);
  static at::Tensor& tanh_out(const at::Tensor& self, at::Tensor& out);
  static at::Tensor tanh_backward(
      const at::Tensor& grad_in,
      const at::Tensor& input);
  static at::Tensor gelu(const at::Tensor& self);
  static at::Tensor gelu_backward(
      const at::Tensor& grad,
      const at::Tensor& self);

  static at::Tensor& erf_(at::Tensor& self);
  static at::Tensor erf(const at::Tensor& self);
  static at::Tensor& exp_(at::Tensor& self);
  static at::Tensor exp(const at::Tensor& self);
  static at::Tensor& neg_out(const at::Tensor& input, at::Tensor& result);
  static at::Tensor& reciprocal_(at::Tensor& self);
  static at::Tensor reciprocal(const at::Tensor& self);
  static at::Tensor& reciprocal_out(const at::Tensor& self, at::Tensor& result);
  static at::Tensor clamp_min(const at::Tensor& self, const at::Scalar& min);
  static at::Tensor& clamp_(
      at::Tensor& self,
      const c10::optional<at::Scalar>& min,
      const c10::optional<at::Scalar>& max);
  static at::Tensor clamp(
      const at::Tensor& self,
      const c10::optional<at::Scalar>& min,
      const c10::optional<at::Scalar>& max);
  static at::Tensor abs(const at::Tensor& self);
  static at::Tensor& abs_(at::Tensor& self);
  static at::Tensor neg(const at::Tensor& self);
  static at::Tensor sin(const at::Tensor& self);
  static at::Tensor cos(const at::Tensor& self);
  static at::Tensor ones_like(
      const at::Tensor& self,
      c10::optional<at::ScalarType> dtype,
      c10::optional<at::Layout> layout,
      c10::optional<at::Device> device,
      c10::optional<bool> pin_memory,
      c10::optional<at::MemoryFormat> memory_format);
  static at::Tensor one_hot(const at::Tensor& self, int64_t num_classes);
  static at::Tensor _log_softmax(
      const at::Tensor& self,
      const int64_t dim,
      const bool half_to_float);
  inline static at::Tensor _log_softmax_backward_data(
      const at::Tensor& grad,
      const at::Tensor& output,
      int64_t dim,
      const at::Tensor& input);
  static at::Tensor softmax(
      const at::Tensor& self,
      int64_t dim,
      c10::optional<at::ScalarType> dtype);
  static at::Tensor _softmax(
      const at::Tensor& self,
      int64_t dim,
      const bool half_to_float);
  static at::Tensor _softmax_backward_data(
      const at::Tensor& grad,
      const at::Tensor& output,
      int64_t dim,
      at::ScalarType input_dtype);
  static at::Tensor _masked_scale(
      const at::Tensor& self,
      const at::Tensor& mask,
      double scale);
  static at::Scalar _local_scalar_dense(const at::Tensor& self);
  static at::Tensor floor(const at::Tensor& self);
  static at::Tensor& floor_(at::Tensor& self);
  static at::Tensor matmul(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor round(const at::Tensor& self);
  static at::Tensor& round_(at::Tensor& self);
  static at::Tensor rsqrt(const at::Tensor& self);
  static at::Tensor& rsqrt_(at::Tensor& self);
  static at::Tensor isfinite(const at::Tensor& self);
  static at::Tensor log(const at::Tensor& self);
  static at::Tensor& log_(at::Tensor& self);
  static at::Tensor log2(const at::Tensor& self);
  static at::Tensor& log2_(at::Tensor& self);
  static ::std::vector<at::Tensor> unbind(const at::Tensor& self, int64_t dim);
  static at::Tensor stack(at::TensorList tensors, int64_t dim);
  static at::Tensor& stack_out(
      at::TensorList tensors,
      int64_t dim,
      at::Tensor& out);
  static at::Tensor alias(const at::Tensor& self);
  static at::Tensor _unsafe_view(const at::Tensor& self, at::IntArrayRef size);
  static at::Tensor squeeze(const at::Tensor& self);
  static at::Tensor squeeze(const at::Tensor& self, int64_t dim);
  static at::Tensor& squeeze_(at::Tensor& self);
  static at::Tensor& squeeze_(at::Tensor& self, int64_t dim);
  static at::Tensor unsqueeze(const at::Tensor& self, int64_t dim);
  static at::Tensor& unsqueeze_(at::Tensor& self, int64_t dim);
  static const at::Tensor& as_strided_(
      const at::Tensor& self,
      at::IntArrayRef size,
      at::IntArrayRef stride,
      c10::optional<int64_t> storage_offset);

  static ::std::vector<at::Tensor> split(
      const at::Tensor& self,
      int64_t split_size,
      int64_t dim);
  static at::Tensor& bitwise_and_out(
      const at::Tensor& self,
      const at::Tensor& other,
      at::Tensor& out);
  /*static at::Tensor& bitwise_and_out(
      at::Tensor& out,
      const at::Tensor& self,
      at::Scalar other);*/
  static at::Tensor& bitwise_or_out(
      const at::Tensor& self,
      const at::Tensor& other,
      at::Tensor& out);
  static at::Tensor& bitwise_xor_out(
      const at::Tensor& self,
      const at::Tensor& other,
      at::Tensor& out);
  static at::Tensor& bitwise_not_out(const at::Tensor& self, at::Tensor& out);
  static at::Tensor upsample_nearest2d(
      const at::Tensor& input,
      c10::optional<at::IntArrayRef> output_size,
      c10::optional<at::ArrayRef<double>> scale_factors);
  static at::Tensor upsample_nearest2d_backward(
      const at::Tensor& grad_output,
      c10::optional<at::IntArrayRef> output_size,
      at::IntArrayRef input_size,
      c10::optional<at::ArrayRef<double>> scale_factors);
  static at::Tensor upsample_nearest3d(
      const at::Tensor& input,
      c10::optional<at::IntArrayRef> output_size,
      c10::optional<at::ArrayRef<double>> scale_factors);
  static at::Tensor upsample_nearest3d_backward(
      const at::Tensor& grad_output,
      c10::optional<at::IntArrayRef> output_size,
      at::IntArrayRef input_size,
      c10::optional<at::ArrayRef<double>> scale_factors);
  static at::Tensor remainder(const at::Tensor& self, const at::Tensor& other);
  static at::Tensor remainder(const at::Tensor& self, const at::Scalar& other);
  static at::Tensor& remainder_(at::Tensor& self, const at::Tensor& other);
  static at::Tensor& remainder_(at::Tensor& self, const at::Scalar& other);
  static at::Tensor& remainder_out(
      const at::Tensor& self,
      const at::Tensor& other,
      at::Tensor& result);
  static at::Tensor& remainder_out(
      const at::Tensor& self,
      const at::Scalar& other,
      at::Tensor& result);
  static at::Tensor flip(const at::Tensor& self, at::IntArrayRef dims);
  static at::Tensor diag(const at::Tensor& self, int64_t diagonal);
  static at::Tensor& diag_out(
      const at::Tensor& self,
      int64_t diagonal,
      at::Tensor& out);
  static bool is_pinned(
      const at::Tensor& self,
      c10::optional<c10::Device> device);
  static at::Tensor pin_memory(
      const at::Tensor& self,
      c10::optional<c10::Device> device);
  static at::Tensor _pin_memory(
      const at::Tensor& self,
      c10::optional<c10::Device> device);
};

std::tuple<at::Tensor&, at::Tensor&>
optimizer_sparse_sgd_with_valid_count_hpu_wrap(
    const at::Tensor& gradients,
    at::Tensor& weights_in,
    at::Tensor& moments_in,
    const at::Tensor& indices,
    const at::Tensor& learning_rate,
    const at::Tensor& valid_count_tensor,
    float mom,
    bool nesterov);
std::tuple<at::Tensor&, at::Tensor&>
optimizer_sparse_adagrad_with_valid_count_hpu_wrap(
    const at::Tensor& gradients,
    at::Tensor& weights_in,
    at::Tensor& moments_in,
    const at::Tensor& indices,
    const at::Tensor& learning_rate,
    const at::Tensor& valid_count_tensor);
void optimizer_adamw_hpu_wrap(
    const at::TensorList& gradient_vec,
    at::TensorList& weight_vec,
    at::TensorList& exp_avg_vec,
    at::TensorList& exp_avg_sq_vec,
    at::Tensor& lr_t,
    at::Tensor& neg_step_t,
    const float beta1,
    const float beta2,
    const float epsilon,
    const float weight_decay);
at::Tensor fused_norm_hpu_wrap(
    std::vector<at::Tensor>& grad,
    const at::Tensor& max_norm,
    float norm_type = 2.0);
at::Tensor& optimizer_adagrad_hpu_wrap(
    const at::TensorList& gradients,
    at::TensorList& weights,
    at::TensorList& variances,
    const at::Tensor& epoch_num,
    at::Tensor& lr,
    const float wd,
    const float lrd,
    const float epsilon);
at::Tensor& optimizer_sgd_hpu_wrap(
    const at::TensorList& gradients,
    at::TensorList& weights,
    at::Tensor& lr,
    const float wd,
    const float mom,
    const float damp,
    const bool nesterov);
at::Tensor& optimizer_sgd_momentum_hpu_wrap(
    const at::TensorList& gradients,
    at::TensorList& weights,
    at::TensorList& momentum,
    const at::Tensor& epoch_num,
    at::Tensor& lr,
    const float wd,
    const float mom,
    const float damp,
    const bool nesterov);
at::Tensor embedding_bag_sum_hpu_wrap(
    const at::Tensor& input,
    const at::Tensor& indices,
    const at::Tensor& offsets,
    const at::Tensor& valid_count,
    int64_t kernel_mode);
at::Tensor& embedding_bag_sum_bwd_out_kernel_mode_hpu_wrap(
    at::Tensor& out,
    const at::Tensor& input,
    const at::Tensor& indices,
    const at::Tensor& offsets,
    const at::Tensor& valid_count,
    int64_t kernel_mode);
at::Tensor gather2d_hpu_wrap(
    const at::Tensor& input,
    const at::Tensor& indices,
    int64_t validCount);
at::Tensor optimizer_lamb_fused_norm_hpu_wrap(
    const std::vector<at::Tensor>& grad,
    float max_grad_norm);
std::tuple<
    std::vector<at::Tensor>,
    std::vector<at::Tensor>,
    std::vector<at::Tensor>>
optimizer_lamb_phase1_hpu_wrap(
    const std::vector<at::Tensor>& gradient_vec,
    std::vector<at::Tensor>& weight_vec,
    std::vector<at::Tensor>& exp_avg_vec,
    std::vector<at::Tensor>& exp_avg_sq_vec,
    const at::Tensor& clip_global_grad_norm,
    const int grad_averaging,
    const float lr,
    const float beta1,
    const float beta2,
    const float epsilon,
    const int step,
    const int bias_correction,
    const float weight_decay);
void optimizer_lamb_phase2_hpu_wrap(
    std::vector<at::Tensor>& weight_vec,
    const std::vector<at::Tensor>& adam_norm_vec,
    const std::vector<at::Tensor>& weight_norm_vec,
    const std::vector<at::Tensor>& adam_step_vec,
    const std::vector<at::Tensor>& trust_ratio_vec,
    const float step,
    const float weight_decay,
    const int use_lamb);
at::Tensor habana_nms_hpu_wrap(
    const at::Tensor& boxes,
    const at::Tensor& scores,
    float iou_threshold,
    float score_threshold);
at::Tensor batched_nms_hpu_wrap(
    const at::Tensor& boxes,
    const at::Tensor& scores,
    const at::Tensor& indices,
    float iou_threshold);
at::Tensor torchvision_nms_hpu_wrap(
    const at::Tensor& boxes,
    const at::Tensor& scores,
    double iou_threshold);
namespace vision {
namespace ops {
at::Tensor roi_align_fwd_wrap(
    const at::Tensor& images,
    const at::Tensor& rois,
    double spatial_scale,
    int64_t output_h,
    int64_t output_w,
    int64_t sampling_ratio,
    bool aligned);
at::Tensor roi_align_bwd_wrap(
    const at::Tensor& grad_out,
    const at::Tensor& rois,
    double spatial_scale,
    int64_t output_h,
    int64_t output_w,
    int64_t bs,
    int64_t ch,
    int64_t h,
    int64_t w,
    int64_t sampling_ratio,
    bool aligned);
} // namespace ops
} // namespace vision
