import torch
from typing import Optional, Union, List

_device_t = Union[torch.device, str, int, None]

def init() -> None: ...
def is_available() -> bool: ...
def device_count() -> int: ...
def get_device_type() -> int: ...
def is_initialized() -> bool: ...
def get_device_name(device: Optional[_device_t] = None) -> str: ...
def current_device() -> int: ...
def synchronize() -> None: ...
def is_bf16_available() -> bool: ...
def get_device_capability() -> str: ...
def get_device_properties(device: Optional[_device_t] = None) -> str: ...
def can_device_access_peer(device: _device_t, peer_device: _device_t) -> bool: ...
def get_arch_list() -> List[str]: ...
def get_gencode_flags() -> str: ...
