import torch
from typing import Optional, Union
_device_t = Union[torch.device, str, int, None]

def init() -> None: ...
def is_available() -> bool: ...
def device_count() -> int: ...
def get_device_type() -> int: ...
def is_initialized() -> bool: ...
def get_device_name(device: Optional[_device_t] = None) -> str: ...
def current_device() -> int: ...
def synchronize() -> None: ...
