#!/usr/bin/env bash
###############################################################################
# Copyright (C) 2024 Habana Labs, Ltd. an Intel Company
# All Rights Reserved.
#
# Unauthorized copying of this file or any element(s) within it, via any medium
# is strictly prohibited.
# This file contains Habana Labs, Ltd. proprietary and confidential information
# and is subject to the confidentiality and license agreements under which it
# was provided.
#
###############################################################################

# If iceccd can't connect to a scheduler, make sure you're docker running with --net=host.
iceccd --nice 10 -u icecc -b /var/cache/icecc -d -m 0 -p 10246 -N "${HOSTNAME}"-manylinux

# shellcheck source=../entrypoint
exec entrypoint "$@"
