// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "eq.h"
#include "isfinite.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Geneq_Scalar_out : OpBackend {
  Geneq_Scalar_out(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "equal_fwd", scalar_type, {}, {}, {1}, true) {
        SetOutputMetaFn(CompareMeta);
        EnableTypePromotion();
        HandleBoolInputs();
  }
};

struct Genisfinite : _IsFiniteInfNan {
  Genisfinite(int device_id, c10::ScalarType scalar_type) :
      _IsFiniteInfNan(device_id, "isfinite_fwd", scalar_type, {0}, {}, {}, false) {
  }
};



static const auto& kr_gen_6 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::eq.Scalar_out", Geneq_Scalar_out)
.REGISTER_HPU_BACKEND("aten::isfinite", Genisfinite)
;




}  // namespace habana

