// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "bucketize.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Genbucketize_Scalar : OpBackend {
  Genbucketize_Scalar(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "search_sorted_fwd", scalar_type, {1}, {}, {0}, false) {
        SetOutputMetaFn(BucketizeMeta);
        SetFillParams(FillBucketizeParams);
        SetTpcInputOrder({1, 0});
        EnableTypePromotion();
  }
};



static const auto& kr_gen_2 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::bucketize.Scalar", Genbucketize_Scalar)
;




}  // namespace habana

