// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "__ilshift__.h"
#include "_foreach_add.h"
#include "_fused_dropout.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Gen__ilshift___Scalar : OpBackend {
  Gen__ilshift___Scalar(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "bitshift_fwd", scalar_type, {}, {0}, {1}, false) {
        SetFillParams(FillLeftShiftParams);
  }
};

struct Gen_foreach_add__Scalar : ForeachBinary {
  Gen_foreach_add__Scalar(int device_id, c10::ScalarType scalar_type) :
      ForeachBinary(device_id, "add_fwd", scalar_type, {}, {0}, {}, false) {
  }
};

struct Gen_fused_dropout : FusedNativeDropout {
  Gen_fused_dropout(int device_id, c10::ScalarType scalar_type) :
      FusedNativeDropout(device_id, "None", scalar_type, {0, 0}, {}, {}, false) {
        SetOutputMetaFn(FusedNativeDropoutMeta);
        SetFillParams(FillFusedNativeDropoutParams);
  }
};



static const auto& kr_gen_0 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::__ilshift__.Scalar", Gen__ilshift___Scalar)
.REGISTER_HPU_BACKEND("aten::_foreach_add_.Scalar", Gen_foreach_add__Scalar)
.REGISTER_HPU_BACKEND("aten::_fused_dropout", Gen_fused_dropout)
.REGISTER_HPU_BACKEND("hpu::_fused_dropout", Gen_fused_dropout)
;



TORCH_LIBRARY_FRAGMENT(hpu, m) {
  static_cast<void>(m);
  m.def("_fused_dropout(Tensor self, float p, Tensor? seed) -> (Tensor, Tensor)");

}
}  // namespace habana

