// Autogenerated file by run_gen_op.py. Do not edit directly!
/**
* Copyright (c) 2021-2024 Intel Corporation
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#include <ATen/ATen.h>
#include <ATen/NativeFunctions.h>
#include <torch/library.h>
#include "hpu_ops/autocast_helpers.h"

namespace at::autocast {
namespace {


TORCH_LIBRARY_IMPL(aten, AutocastHPU, m) {
  Hpu_KERNEL(isfinite, "isfinite", at::Tensor(const at::Tensor &))
  Hpu_KERNEL(upsample_bicubic2d, "upsample_bicubic2d.vec", at::Tensor(const at::Tensor &, at::OptionalIntArrayRef, bool, ::std::optional<at::ArrayRef<double>>))
}

} // namespace
} // namespace at::autocast

