#!/usr/bin/env python
# ##############################################################################
# Copyright (C) 2021-2023 Habana Labs, Ltd. an Intel Company
# All Rights Reserved.
#
# Unauthorized copying of this file or any element(s) within it, via any medium
# is strictly prohibited.
# This file contains Habana Labs, Ltd. proprietary and confidential information
# and is subject to the confidentiality and license agreements under which it
# was provided.
#
# ##############################################################################
from __future__ import print_function

from abc import ABC, abstractmethod
import argparse
import collections.abc
import lark
import json
import os
import re
import sys
import yaml
import torch
from collections import defaultdict
from yaml import Loader
from packaging.version import Version

# Temporary flag, remove libraries are split
_IS_EAGER = os.environ.get("PT_HPU_EAGER_OPS", "0").lower() in ["1", "true"]


def namedtuple_with_defaults(typename, field_names, default_values=()):
    ntuple = collections.namedtuple(typename, field_names)
    ntuple.__new__.__defaults__ = (None,) * len(ntuple._fields)
    if isinstance(default_values, collections.abc.Mapping):
        prototype = ntuple(**default_values)
    else:
        prototype = ntuple(*default_values)
    ntuple.__new__.__defaults__ = tuple(prototype)
    return ntuple


FuncDef = namedtuple_with_defaults("FuncDef", "cpp_sig, aten_sig, dispatch, default")

OpGen = namedtuple_with_defaults(
    "OpGen",
    "tree, xtree, rwxtree, func, xfunc, op_frontend, op_backend, cname, sig, rwsig, cppsig, funsig, mapsig, aten_sig, dispatch, default, ctxop, opgroup, fc_params",
)

_GRAMMAR = r"""
    start: type fnname "(" params ")"
    type: CONST? core_type refspec?
    fnname: CNAME
    refspec: REF
           | PTR
    core_type: template
        | TNAME
    template: TNAME "<" typelist ">"
    typelist: type
            | type "," typelist
    REF: "&"
    PTR: "*"
    CONST: "const"
    TNAME: /[a-zA-Z0-9_:]+/
    HEXNUMBER: /0x[0-9a-fA-F]+/
    params: param
          | param "," params
    param: type param_name param_defval?
    param_name: CNAME

    param_defval: "=" init_value
    init_value: "true"
              | "false"
              | "{}"
              | NUMBER
              | SIGNED_NUMBER
              | HEXNUMBER
              | ESCAPED_STRING

    %import common.CNAME -> CNAME
    %import common.NUMBER -> NUMBER
    %import common.SIGNED_NUMBER -> SIGNED_NUMBER
    %import common.ESCAPED_STRING -> ESCAPED_STRING
    %import common.WS
    %ignore WS
    """

_PARSER = lark.Lark(_GRAMMAR, parser="lalr", propagate_positions=True)

_XPARSER = lark.Lark(
    _GRAMMAR, parser="lalr", propagate_positions=True, keep_all_tokens=True
)

# List of non-leaf ops we want to override both forward + backward.
# TODO(https://github.com/pytorch/pytorch/issues/39959)
_FN_AUTOGRAD_HPU = set(
    [
        "matmul(Tensor, Tensor) -> Tensor",
        "softmax(Tensor, int64_t, c10::optional<ScalarType>) -> Tensor",
        "dropout(Tensor, double, bool) -> Tensor",
        "linear(Tensor, Tensor, c10::optional<Tensor>) -> Tensor"
    ]
)

_TYPE_NSMAP = {
    "Tensor": "at::Tensor",
    "TensorList": "at::TensorList",
    "Scalar": "at::Scalar",
    "Storage": "at::Storage",
    "IntList": "at::IntList",
    "IntArrayRef": "at::IntArrayRef",
    "OptionalIntArrayRef": "at::OptionalIntArrayRef",
    "ArrayRef": "at::ArrayRef",
    "Generator": "at::Generator",
    "Layout": "at::Layout",
    "ScalarType": "at::ScalarType",
    "TensorOptions": "at::TensorOptions",
    "SparseTensorRef": "at::SparseTensorRef",
    "Device": "c10::Device",
    "optional": "c10::optional",
    "MemoryFormat": "at::MemoryFormat",
    "QScheme": "at::QScheme",
    "ConstQuantizerPtr": "at::ConstQuantizerPtr",
    "Dimname": "at::Dimname",  # namedtensor-only
    "DimnameList": "at::DimnameList",  # namedtensor-only
    "ITensorListRef": "at::ITensorListRef",
    "OptionalSymIntArrayRef": "at::OptionalSymIntArrayRef",
    "SymInt": "c10::SymInt",
}

_H_HEADER = """// Autogenerated file by {gen}. Do not edit directly!

#pragma once
#include <ATen/Tensor.h>

#include "hpu_ops/hpu_op_helper.h"
#include "habana_kernels/lazy_kernels.h"

namespace habana {{
{op_backend_classes}
{op_frontend_classes}
{header_decls}
}}  // namespace habana
"""

def torch_library_fragment(custom_schema_regs):
  if custom_schema_regs:
    return "TORCH_LIBRARY_FRAGMENT(hpu, m) {\n" \
        "  static_cast<void>(m);\n" \
        f"{custom_schema_regs}\n" \
        "}"
  return ""

def torch_library_impl(torch_regs):
  if torch_regs:
    return "TORCH_LIBRARY_IMPL(aten, HPU, m) {\n" \
        f"{torch_regs}\n" \
        "}\n"
  return ""

_CPP_HEADER = """// Autogenerated file by {gen}. Do not edit directly!
{header_inclusions}

using habana_helpers::DTypeHelper;
using habana_lazy::LazyOp;
using habana_lazy::GraphHashBuilder;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {{

{dtype_defs}

{funcs}

{op_backend}

static const auto& kr_gen_{file_idx} = KernelRegistry()
{kr_regs};

{torch_regs}

{custom_schema_regs}
}}  // namespace habana
"""

_OPCLASS_HEADER = """struct {cname} : {op_backend_class} {{
  {cname}(int device_id, c10::ScalarType scalar_type) :
      {op_backend_class}(device_id, \"{guid}_\", scalar_type, {{{out_ids}}}, {{{inplace_ids}}}, {{{scalar_ids}}}, {is_out_fn}) {{{ctor_extra_calls}
  }}{custom_handler}
}};
"""

_CUSTOM_HANDLER = """

  void CustomHandler(graph &g, Stack& stack) override {{
    static_cast<void>(g);
    static_cast<void>(stack);
    {body}
  }}"""

_FILL_PARAMS = """[](const at::Stack& stack, size_t& size) {{
            using T = {ns_param};
            size = sizeof(T);
            return std::make_shared<T>(T{{{args}}});
        }}"""


_DEVICE_STR_TO_ENUM = {
    -1: "-1",
    "Gaudi": "synDeviceGaudi",
    "Gaudi2": "synDeviceGaudi2",
    "Greco": "synDeviceGreco",
    "Gaudi3": "synDeviceGaudi3",
}


_AUTOCAST_TEMPLATE = """// Autogenerated file by {gen}. Do not edit directly!
/******************************************************************************
 * Copyright (C) 2022 Habana Labs, Ltd. an Intel Company
 * All Rights Reserved.
 *
 * Unauthorized copying of this file or any element(s) within it, via any medium
 * is strictly prohibited.
 * This file contains Habana Labs, Ltd. proprietary and confidential information
 * and is subject to the confidentiality and license agreements under which it
 * was provided.
 *
 *******************************************************************************
 */

#include "pytorch_helpers/habana_helpers/pt_version_check.h"

#if IS_PYTORCH_FORK_AT_LEAST(1, 0)

#include <ATen/ATen.h>
#include <ATen/NativeFunctions.h>
#include <torch/library.h>
#include "hpu_ops/autocast_helpers.h"

namespace at {{
namespace autocast {{
namespace {{

using tuple_2_tensors = std::tuple<Tensor, Tensor>;
using tuple_3_tensors = std::tuple<Tensor, Tensor, Tensor>;
using tuple_4_tensors = std::tuple<Tensor, Tensor, Tensor, Tensor>;
using tuple_5_tensors = std::tuple<Tensor, Tensor, Tensor, Tensor, Tensor>;
using tuple_6_tensors = std::tuple<Tensor, Tensor, Tensor, Tensor, Tensor, Tensor>;
using tuple_4_tensors_int64 = std::tuple<at::Tensor,at::Tensor,at::Tensor,at::Tensor,int64_t>;
using tuple_2_tensors_double_int64 = std::tuple<at::Tensor,at::Tensor,double,int64_t>;
using tuple_3_tensors_vector = std::tuple<at::Tensor,at::Tensor,at::Tensor,::std::vector<at::Tensor>>;
using tuple_double_int64 = std::tuple<double,int64_t>;
using tuple_tensor_vector = std::tuple<at::Tensor,::std::vector<at::Tensor>>;
using tuple_vector_tensor = std::tuple<::std::vector<at::Tensor>,at::Tensor>;
using tuple_tensor_2_vectors = std::tuple<at::Tensor,::std::vector<at::Tensor>,::std::vector<at::Tensor>>;

TORCH_LIBRARY_IMPL(_, AutocastHPU, m) {{
  m.fallback(torch::CppFunction::makeFallthrough());
}}

TORCH_LIBRARY_IMPL(aten, AutocastHPU, m) {{
{ops_registrations}
}}

}} // namespace
}} // namespace autocast
}} // namespace at

#endif
"""

class OpValidatorGenerator(ABC):
    """
    Class describing how to generate code for given op_validator
    """
    def __init__(self, ctxop : "Op"):
        self._ctxop = ctxop

    @abstractmethod
    def can_generate(self):
        """
        Returns information if generator can generate code.

        Some generators depends on additional data in YAML file.
        This method can check if all data is present and generator
        is usable.
        """

    @abstractmethod
    def get_fallback_if_prefix(self):
        """
        Returns prefix name for FALLBACK_IF macro family. This is temporary solutions allowing
        to coexists old way and new way begin developed. The proof-of-concept being
        developed uses own family of macros having POC_ prefix in its name
        """

    @abstractmethod
    def get_validator_data_def(self, isoutfn):
        """
        Returns dtypes line to be added to CPP file
        """

    @abstractmethod
    def get_validator_inline_data_def(self):
        """
        Returns dtypes line to be added to CPP file inside function
        """

    @abstractmethod
    def get_inputs_to_generate_macro(self, xs):
        """
        Returns a list of arguments to which we should generate macro FALLBACK_IF.

        It is helper. The old method generated macro per tensor while the new method
        want to generate only one macro. This method is a helper to control this behaviour.
        """

class UseDtypesOpValidatorGenerator(OpValidatorGenerator):
    def get_fallback_if_prefix(self):
        return ""

    def can_generate(self):
        dtypes = self._ctxop.get_dtypes()
        return dtypes is not None

    def get_validator_data_def(self, _isoutfn):
        return ""

    def get_validator_inline_data_def(self):
        dtypes = self._ctxop.get_dtypes()
        return generate_dtype_macro(dtypes)

    def get_inputs_to_generate_macro(self, xs):
        return xs

class CheckNodeWithSharedLayerValidatorGenerator(OpValidatorGenerator):
    def get_fallback_if_prefix(self):
        return "VAL_"

    def can_generate(self):
        return True

    def get_validator_inline_data_def(self):
        return ""

    def get_validator_data_def(self, isoutfn):
        def is_inplace():
            if ctxop.get_inplace_ids() != []: return True
            return ctxop.opname.split(".")[0].endswith("_")

        def generate_supported_dtypes(dtypes):
            if type(dtypes) is dict:
                if 'Greco' in dtypes:
                    dtypes = dtypes['Greco']
                else:
                    dtypes = []
            assert type(dtypes) is list, f"Cannot handle dtypes for {ctxop.opname}"
            dtypes = set(dtypes)
            if "Float" in dtypes:
                dtypes.add("Double")
            if "Int" in dtypes:
                dtypes.add("Long")
            if "Char" in dtypes:
                dtypes.add("Bool")

            dtypes = map(lambda x: f"at::ScalarType::{x}", dtypes)
            dtypes = ", ".join(dtypes)
            return 'SupportedDtypes({{{{-1, {' + dtypes + '}}}}})'
            return 'SupportedDtypes(std::unordered_map<int, std::unordered_set<at::ScalarType>>({{-1, {' + dtypes + '}}}))'

        ctxop = self._ctxop
        opname = ctxop.opname
        opname = ctxop.opname.replace(".", "_")

        if ctxop.get_guid() is None:
            raise Exception(f"Invalid specification for op {opname}: selected op_validator requires `guid` in specification")

        arg_opname = f'"{opname}"'
        arg_guid = f'"{ctxop.get_guid()}"'
        arg_output_shape = ctxop.get_custom_output_shape()
        arg_fill_params = ctxop.get_custom_fill_params()
        arg_type_promotion = 'false'
        arg_promote_int_to_float = 'false' # str(ctxop.promote_int_to_float()).lower()
        arg_safe_cast_check = str(ctxop.safe_cast_check()).lower()
        arg_isinplace = str(is_inplace()).lower()
        arg_isoutfn = str(isoutfn).lower()
        arg_dtypes = generate_supported_dtypes(ctxop.get_dtypes())

        if arg_output_shape is None:
            arg_output_shape = 'nullptr'
        if arg_fill_params is None:
            arg_fill_params = 'nullptr'

        # Rebase
        if arg_safe_cast_check == 'none':
            arg_safe_cast_check = 'false'

        constructor_args = [arg_opname, arg_guid, arg_output_shape, arg_fill_params, arg_type_promotion, arg_promote_int_to_float, arg_safe_cast_check, arg_isinplace, arg_isoutfn, arg_dtypes]
        constructor_args = ', '.join(constructor_args)

        return f'static CheckNodeWithSharedLayerValidator validator_{opname}({constructor_args});\n';

    def get_inputs_to_generate_macro(self, xs):
        return xs[0:1]


class Op(object):
    def __init__(self, opname, op):
        self.op = op
        self.opname = opname

    def get_guid(self):
        return self.op.get("guid", None)

    def get_dtypes(self):
        return self.op.get("dtypes", None)

    def get_tpc_param(self):
        return self.op.get("tpc_param", None)

    def get_layouts(self):
        return self.op.get("layouts", [])

    def get_synapse_layouts(self):
        return self.op.get("synapse_layouts", [])

    def get_op_backend_class(self):
        op_backend_class = self.op.get("op_backend", None)
        if op_backend_class:
            return op_backend_class
        elif self.get_op_template():
            if self.get_op_template() == "reduction":
                return "ReductionBackendTemplate"
            assert "Unknown template: {}".format(self.get_op_template())
        return "OpBackend"

    def get_op_frontend_class(self):
        op_frontend_class = self.op.get("op_frontend", None)
        if op_frontend_class:
            return op_frontend_class
        elif self.get_op_template():
            if self.get_op_template() == "reduction":
                return "ReductionFrontendTemplate"
            assert "Unknown template: {}".format(self.get_op_template())

        return "LazyOp"

    def get_op_template(self):
        return self.op.get("op_template", None)

    def get_custom_fill_params(self):
        return self.op.get("custom_fill_params", None)

    def get_custom_output_shape(self):
        if self.op.get("broadcast", False):
            assert (
                self.op.get("custom_output_shape", None) is None
            ), "broadcast will insert custom_output_shape, so no need to define it."
            return "BinaryOutputShape"

        return self.op.get("custom_output_shape", None)

    def get_inplace_ids(self):
        return self.op.get("inplace_ids", [])

    def get_out_ids(self):
        return self.op.get("out_ids", [])

    def get_scalar_ids(self):
        return self.op.get("scalar_ids", [])

    def force_default(self):
        return self.op.get("force_default", None)

    def promote_to_common_type(self):
        return self.op.get("promote_to_common_type", [])

    def promote_int_to_float(self):
        return self.op.get("promote_int_to_float", [])

    def safe_cast_check(self):
        return self.op.get("safe_cast_check", None)

    def custom_schema(self):
        args = self.op.get("schema_args", None)
        if args:
            return self.opname + args

    def get_fallback_check(self):
        return self.op.get("fallback_check", [])

    def get_override_fn(self):
        return self.op.get("override_fn", None)

    def get_acc_thread(self):
        return self.op.get("acc_thread", False)

    def get_out_dtype(self):
        return self.op.get("out_dtype", None)

    def get_op_validator_generator(self) -> OpValidatorGenerator:
        op_validator = self.op.get("op_validator")
        if op_validator is None: op_validator = 'use-dtypes'
        mapping = {
            "use-dtypes" : UseDtypesOpValidatorGenerator,
            "check-node-with-shared-layer" : CheckNodeWithSharedLayerValidatorGenerator
        }
        assert op_validator in mapping.keys(), f"op_validator can be set only to {mapping.keys()}, not {op_validator} [TODO: custom]"
        result = mapping[op_validator](self)
        if not result.can_generate():
            return None
        return result

class Context(object):
    def __init__(self, functions, yamlfile):
        with open(functions, "r") as ff:
            self.functions_data = ff.read()

        with open(yamlfile, "r") as ff:
            self.op_data = yaml.load(ff.read(), Loader=Loader)

    def get_function(self, name):
        if self.functions_data.find(" {}(".format(name)) >= 0:
            return "at::{}".format(name + "f" if is_out_fn(name) else name)

    def get_op(self, opname):
        return Op(opname, self.op_data[opname])


class StringEmit(object):
    def __init__(self, sref):
        self.sref = sref
        self.sval = ""
        self.pos = -1

    def __repr__(self):
        return self.sval

    def advance(self, t):
        start = t.column - 1
        end = t.end_column - 1
        pos = self.pos if self.pos >= 0 else start
        if start > pos:
            self.sval += self.sref[pos:start]
        self.sval += t.value
        self.pos = end

    def skip(self, t):
        self.pos = last_match(t) if self.pos >= 0 else -1

    def append(self, s):
        self.sval += s
        self.pos = -1


def first_match(t):
    if isinstance(t, lark.lexer.Token):
        return t.column - 1
    assert isinstance(t, lark.tree.Tree)
    return first_match(t.children[0])


def last_match(t):
    if isinstance(t, lark.lexer.Token):
        return t.end_column - 1
    assert isinstance(t, lark.tree.Tree)
    return last_match(t.children[-1])


def for_every_token(t, fn):
    if isinstance(t, lark.lexer.Token):
        fn(t)
    else:
        assert isinstance(t, lark.tree.Tree)
        for c in t.children:
            for_every_token(c, fn)


def emit_string(t, emit, emit_fn):
    status = emit_fn(t)
    if status > 0:

        def do_emit(tok):
            emit.advance(tok)

        for_every_token(t, do_emit)
    elif status == 0:
        if isinstance(t, lark.lexer.Token):
            emit.advance(t)
        else:
            assert isinstance(t, lark.tree.Tree)
            for c in t.children:
                emit_string(c, emit, emit_fn)
    else:
        emit.skip(t)


def typed_child(t, n, ttype):
    assert isinstance(t, lark.tree.Tree)
    assert n < len(t.children)
    c = t.children[n]
    assert isinstance(c, lark.tree.Tree)
    assert c.data == ttype, t.pretty()
    return c


def rewrite_sig(tree, orig_sig, emit_fn=lambda x: 0):
    emit = StringEmit(orig_sig)
    emit_string(tree, emit, emit_fn)
    return str(emit)


def rewrite_signature(sig, tmap):
    def rewrite(t):
        if t.type == "TNAME":
            new_type = tmap.get(t.value, None)
            if new_type is not None:
                t.value = new_type

    def emit_fn(t):
        if isinstance(t, lark.lexer.Token):
            return 0
        return -1 if t.data == "param_defval" else 0

    xtree = _XPARSER.parse(sig)
    for_every_token(xtree, rewrite)
    return rewrite_sig(xtree, sig, emit_fn=emit_fn)


def create_stdfunc_sig(tree, orig_sig):
    def emit_fn(t):
        if isinstance(t, lark.lexer.Token):
            return 0
        return -1 if t.data == "param_name" else 0

    emit = StringEmit(orig_sig)
    # Emit full function return type.
    emit_string(typed_child(tree, 0, "type"), emit, emit_fn)
    emit.append("(")
    # Emit parameter list w/out parameter names.
    emit_string(typed_child(tree, 3, "params"), emit, emit_fn)
    emit.append(")")
    return str(emit)


def create_map_sig(tree, orig_sig):
    def emit_fn(t):
        if isinstance(t, lark.lexer.Token):
            return -1 if t.type in ["CONST", "REF", "PTR"] else 0
        return -1 if t.data in ["param_name", "param_defval"] else 0

    emit = StringEmit(orig_sig)
    # Emit full function return type.
    emit_string(typed_child(tree, 1, "fnname"), emit, emit_fn)
    emit.append("(")
    # Emit parameter list w/out parameter names.
    emit_string(typed_child(tree, 3, "params"), emit, emit_fn)
    emit.append(") -> ")
    emit_string(typed_child(tree, 0, "type"), emit, emit_fn)
    return str(emit)


def type_core(t):
    assert isinstance(t, lark.tree.Tree)
    for c in t.children:
        if isinstance(c, lark.tree.Tree) and c.data == "core_type":
            c = c.children[0]
            if isinstance(c, lark.lexer.Token):
                return c.value
            assert isinstance(c, lark.tree.Tree) and c.data == "template"
            return c.children[0].value
    raise RuntimeError("Not a type tree: {}".format(t))


def type_is_const(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[0]
    return isinstance(c, lark.lexer.Token) and c.value == "const"


def type_is_refptr(t, kind):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[-1]
    if not isinstance(c, lark.tree.Tree) or c.data != "refspec":
        return False
    c = c.children[0]
    return isinstance(c, lark.lexer.Token) and c.value == kind


def extract_list(t, l):
    assert isinstance(t, lark.tree.Tree)
    l.append(t.children[0])
    if len(t.children) == 2:
        c = t.children[1]
        if isinstance(c, lark.tree.Tree) and c.data == t.data:
            extract_list(c, l)
    return l


def get_template_type_list(t):
    assert isinstance(t, lark.tree.Tree)
    # Skipping type qualifiers if exists.
    # E.g. const c10::optional<T>
    for c in t.children:
        if isinstance(c, lark.tree.Tree) and c.data == "core_type":
            break
    c = c.children[0]
    assert isinstance(c, lark.tree.Tree) and c.data == "template"
    types = []
    return extract_list(c.children[1], types)


def get_function_name(t):
    assert isinstance(t, lark.tree.Tree)
    fname = t.children[1]
    assert isinstance(fname, lark.tree.Tree)
    assert fname.data == "fnname"
    return fname.children[0].value


def is_out_fn(fname):
    return fname.endswith("_out")


def get_function_signature(t, orig_sig, namefn):
    emit = StringEmit(orig_sig)
    # Emit full function return type.
    emit_string(typed_child(t, 0, "type"), emit, lambda t: 0)
    fnname = typed_child(t, 1, "fnname").children[0]
    xfname = namefn(fnname.value)
    emit.append(" {}(".format(xfname))
    # Emit parameter list w/out parameter names.
    emit_string(typed_child(t, 3, "params"), emit, lambda t: 0)
    emit.append(")")
    return str(emit), fnname.value, xfname


def get_parameters(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[2]
    assert isinstance(c, lark.tree.Tree)
    assert c.data == "params"
    params = []
    extract_list(c, params)
    return params


def param_name(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[1]
    assert isinstance(c, lark.tree.Tree)
    assert c.data == "param_name"
    token = c.children[0]
    assert isinstance(token, lark.lexer.Token)
    return token.value


def param_type(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[0]
    assert isinstance(c, lark.tree.Tree)
    return c


def get_return_type_str(t, orig_sig):
    assert isinstance(t, lark.tree.Tree)
    fname = t.children[1]
    assert isinstance(fname, lark.tree.Tree)
    assert fname.data == "fnname"
    token = fname.children[0]
    assert isinstance(token, lark.lexer.Token)
    return orig_sig[0 : token.column - 2]


def generate_entry_debug_code(t, fname, params):
    # Emits debug code for a given intercepted function.
    code = "  PT_OP_TRACE;\n"
    code += "  PT_LAZY_TRACE;\n"
    code += '  PT_OP_INFO("HpuOp {} :"'.format(fname)
    for p in params:
        ptype = param_type(p)
        pname = param_name(p)
        code += ', " {}=", to_string({})'.format(pname, pname)
    code += ");\n\n"
    return code


def fallback_if_unsupported(tinputs, opname, overload, param_vars, check_per_tensor, fallback_if_prefix):
    code = ""
    for t in tinputs:
        code += "  {}FALLBACK_IF_UNSUPPORTED_DTYPE{}{}({}, {}, {}{})\n".format(
            fallback_if_prefix,
            "_PER_TENSOR" if check_per_tensor else "",
            "2" if overload else "",
            t,
            opname,
            overload + ", " if overload else "",
            ", ".join(param_vars),
        )
    return code


def frontend(
    ctxop,
    tfetcher,
    fn,
    fname,
    aten_sig,
    rtype,
    param_vars,
    meta_vars,
    lazyop_call_args,
    sig,
):
    ns = "hpu" if ctxop.custom_schema() else "aten"
    aten_opname = get_aten_opname(aten_sig)
    opname = aten_opname.split(".")[0]
    overload = aten_opname.split(".")[1] if len(aten_opname.split(".")) > 1 else None
    schema_fn = ns + "::" + opname
    op_frontend_class = ctxop.get_op_frontend_class()
    code = ""

    # TODO safe cast check should be done for out variants without type promotion too
    # https://jira.habana-labs.com/browse/SW-111202
    promote_to_common_type = ctxop.promote_to_common_type()
    promote_int_to_float = ctxop.promote_int_to_float()
    is_reduction = ctxop.get_op_template() == "reduction"
    safe_cast_check = ctxop.safe_cast_check()

    promote_types = promote_to_common_type or promote_int_to_float
    use_compute_type = promote_types or is_reduction

    if use_compute_type:
        dtype_helper_inputs = []
        if promote_types:
            assert (not promote_to_common_type) ^ (
                not promote_int_to_float
            ), "Either one of promote_to_common_type or promote_int_to_float but not both can be defined."

            if promote_int_to_float:
                variant = "PromoteIntToFloat"
                dtype_helper_inputs = promote_int_to_float
            else:
                variant = "PromoteToCommon"
                dtype_helper_inputs = promote_to_common_type
        else:
            variant = "Reduction"
            dtype_helper_inputs = ["self"]

        safe_cast = is_inplace_or_out_op(fname)
        if safe_cast_check is not None:
            assert (
                safe_cast
            ), f"safe_cast_check cannot check for non inplace/non out variant, op={fname}"
            assert (
                safe_cast_check is False
            ), f"safe_cast_check is true by default for inplace/out variant, op={fname}"
            safe_cast = safe_cast_check

        code += (
            f"  auto&& compute_type = "
            f"DTypeHelper::get_compute_dtype({{{', '.join(dtype_helper_inputs)}}}, "
            f'{lazyop_call_args if lazyop_call_args else "c10::nullopt"}, '
            f"DTypeHelper::DtypePromoteVariant::k{variant}, "
            f"{str(safe_cast).lower()}/*safe_cast*/"
            f'{", dtype" if "dtype" in param_vars else ""});\n'
            f"  static_cast<void>(compute_type);\n\n"
        )

    dtypes = ctxop.get_dtypes()
    op_validator_generator = ctxop.get_op_validator_generator()
    if op_validator_generator:
        fallback_if_prefix = op_validator_generator.get_fallback_if_prefix()
        code += op_validator_generator.get_validator_inline_data_def()

        # Check with compute_type when using compute_type
        if use_compute_type:
            code += (
                "  {}FALLBACK_IF_UNSUPPORTED_DTYPE{}(compute_type, {}, {}{})\n".format(
                    fallback_if_prefix,
                    "2" if overload else "",
                    opname,
                    overload + ", " if overload else "",
                    ", ".join(param_vars),
                )
            )
        else:
            tinputs = tfetcher.get_tensors()
            if is_out_fn(fname) and len(tinputs) > 1:
                tinputs = tinputs[:-1]

            check_per_tensor = False
            if isinstance(dtypes, dict):
                if any(p in dtypes.keys() for p in param_vars):
                    check_per_tensor = True
                elif any(isinstance(x, dict) for x in dtypes.values()):
                    check_per_tensor = True
            code += fallback_if_unsupported(
                tinputs, opname, overload, param_vars, check_per_tensor, fallback_if_prefix
            )
        code += "\n"

    fallback_check = ctxop.get_fallback_check()
    if fallback_check:
        fallback_check_fname = fallback_check[0]
        args = fallback_check[1:]
        code += "  FALLBACK_IF_UNSUPPORTED_INPUTS{}({}({}), {}, {}{})\n".format(
            "2" if overload else "",
            fallback_check_fname,
            ", ".join(args),
            opname,
            overload + ", " if overload else "",
            ", ".join(param_vars),
        )

    is_eager_op_supported = False
    if is_eager_op(fname, rtype, sig) and op_frontend_class == "LazyOp":
        is_eager_op_supported = True
        op_frontend_class = "eager::EagerOp"


    if ctxop.get_override_fn():
        code += "  return habana_lazy::{}({})".format(
            ctxop.get_override_fn(), ", ".join(param_vars)
        )
    else:
        out_dtype = ctxop.get_out_dtype()
        if out_dtype:
            code += '  TORCH_CHECK(out.scalar_type() == at::k{}, "{} does not support non-{} outputs")\n'.format(
                out_dtype, aten_opname, out_dtype
            )

        code += '  {}<{}> hpu_op{{"{}", {{{}}}'.format(
            op_frontend_class, rtype, schema_fn, ", ".join(param_vars)
        )

        output_shape_fn = ctxop.get_custom_output_shape()
        if output_shape_fn:
            code += ", {}".format(output_shape_fn)
        elif ctxop.get_op_template() == "reduction":
            dim = "dim" if "dim" in param_vars else "{}"
            keepdim = "keepdim" if "keepdim" in param_vars else "false"
            code += ", ReductionOutputShape(self, {}, {})".format(dim, keepdim)
        code += "};\n"

        if use_compute_type:
            code += "  hpu_op.set_scalar_type(compute_type);\n"

        if ctxop.get_op_frontend_class() == "ReductionFrontendTemplate":
            code += "  hpu_op.SetReductionVarsIndices({});\n".format(
                ", ".join(extract_reduction_vars_indices(param_vars))
            )

        if is_acc_thread_supported(fname, ctxop, rtype, sig) and not is_eager_op_supported:
            if is_inplace_or_out_op(fname):
                if rtype.startswith("::std::tuple<at::Tensor"):
                    code += "  auto tuple = {};\n".format(lazyop_call_args)
                    code += "  RUN_INPLACE_TUPLE_MAYBE_WITH_ACC_THREAD({}, hpu_op, tuple)".format(
                        fname
                    )
                elif rtype == "void" and "TensorList" in sig:
                    assert (
                        sig.count("TensorList") == 1
                    ), f"Only 1 TensorList input supported for inplace ops. Sig: {sig}"
                    code += "  RUN_TENSOR_LIST_INPLACE_MAYBE_WITH_ACC_THREAD({}, hpu_op, {})".format(
                        fname, param_vars[0]
                    )
                elif rtype.startswith("const at::Tensor"):
                    code += "  RUN_CONST_INPLACE_MAYBE_WITH_ACC_THREAD({}, hpu_op, {})".format(
                        fname, lazyop_call_args
                    )
                else:
                    code += (
                        "  RUN_INPLACE_MAYBE_WITH_ACC_THREAD({}, hpu_op, {})".format(
                            fname, lazyop_call_args
                        )
                    )
            else:
                if rtype.startswith("::std::tuple<at::Tensor"):
                    code += "  RUN_TUPLE_MAYBE_WITH_ACC_THREAD({}, hpu_op)".format(
                        fname
                    )
                elif "TensorList" in sig:
                    if sig.count("TensorList") == 1:
                        code += "  RUN_TENSOR_LIST_MAYBE_WITH_ACC_THREAD({}, hpu_op, {})".format(
                            fname, param_vars[0]
                        )
                    elif sig.count("TensorList") == 2:
                        code += "  RUN_TENSOR_LIST2_MAYBE_WITH_ACC_THREAD({}, hpu_op, {})".format(
                            fname, f"{param_vars[0]}, {param_vars[1]}"
                        )
                        pass
                    else:
                        raise Exception(
                            f"Only up to 2 TensorList inputs are supported. Sig: {sig}"
                        )
                else:
                    code += "  RUN_MAYBE_WITH_ACC_THREAD({}, hpu_op)".format(fname)
        else:
            code += "  {}hpu_op.call({})".format(
                "" if rtype == "void" else "return ", lazyop_call_args
            )
    return code + ";\n}"


def bitwise_ops_alt_guid(guid):
    logical_guid = guid.replace("bitwise_", "")
    code = (
        "if (ScalarType() == at::kBool) {{\n"
        '      SetGuid("{}_i8");\n'
        "    }}".format(logical_guid)
    )

    return code


# HACK: Construct tensor from options
def tril_triu_without_tensor():
    # row, col, offset, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_mem
    code = (
        "auto options = at::TensorOptions(at::kHPU).dtype(stack[3].toOptional<c10::ScalarType>());\n"
        "    at::Tensor t = at::empty(ComputeOutputShapes(stack, true)[0], options);\n"
        "    stack.emplace_back(t);"
    )
    return code


def get_op_backend_class_impl(ctxop, fname, cname, num_out_tensors, param_vars):
    guid = ctxop.get_guid()
    out_ids = ctxop.get_out_ids()
    inplace_ids = ctxop.get_inplace_ids()
    scalar_ids = ctxop.get_scalar_ids()
    custom_fill_params = ctxop.get_custom_fill_params()
    tpc_param = ctxop.get_tpc_param()
    op_backend_class = ctxop.get_op_backend_class()
    output_shape_fn = ctxop.get_custom_output_shape()
    promote_type = ctxop.promote_to_common_type()
    promote_int_to_float = ctxop.promote_int_to_float()

    assert (not out_ids) ^ (not inplace_ids) ^ is_out_fn(fname), (
        "`out_ids` or `inplace_ids` should not be defined for {}".format(fname)
        if is_out_fn(fname)
        else "Either `out_ids` or `inplace_ids` should be defined for {}".format(fname)
    )

    scalar_ids_set = set(scalar_ids)
    err_ids = scalar_ids_set.intersection(out_ids if len(out_ids) else inplace_ids)
    assert (
        len(err_ids) == 0
    ), "Input(s) at {} cannot be both scalar and tensor for {}.".format(err_ids, fname)

    out_ids = ", ".join([str(o) for o in out_ids])
    inplace_ids = ", ".join([str(i) for i in inplace_ids])
    scalar_ids = ", ".join([str(s) for s in scalar_ids])

    if fname.startswith("bitwise_"):
        custom_handler = _CUSTOM_HANDLER.format(body=bitwise_ops_alt_guid(guid))
    elif fname == "tril_indices" or fname == "triu_indices":
        custom_handler = _CUSTOM_HANDLER.format(body=tril_triu_without_tensor())
    else:
        custom_handler = ""

    ctor_extra_calls = []
    layouts = ctxop.get_layouts()
    if len(layouts):
        assert len(layouts) == 2, "Define both input and output layouts."
        assert len(layouts[0]), "Input layouts size should be atleast 1."
        assert len(layouts[1]), "Output layouts size should be atleast 1."
        in_layouts = ", ".join(["LayoutFormat::" + l for l in layouts[0]])
        out_layouts = ", ".join(["LayoutFormat::" + l for l in layouts[1]])
        ctor_extra_calls.append(
            "SetLayouts({{{}}}, {{{}}});".format(in_layouts, out_layouts)
        )
    synapse_layouts = ctxop.get_synapse_layouts()
    if len(synapse_layouts):
        assert len(synapse_layouts) == 2, "Define both input and output layouts."
        assert len(synapse_layouts[0]), "Input layouts size should be atleast 1."
        assert len(synapse_layouts[1]), "Output layouts size should be atleast 1."
        in_layouts = ", ".join(
            [
                "synapse_helpers::layouts::SynapseLayoutFormat::" + l
                for l in synapse_layouts[0]
            ]
        )
        out_layouts = ", ".join(
            [
                "synapse_helpers::layouts::SynapseLayoutFormat::" + l
                for l in synapse_layouts[1]
            ]
        )
        ctor_extra_calls.append(
            "SetSynapseLayouts({{{}}}, {{{}}});".format(in_layouts, out_layouts)
        )

    if is_out_fn(fname) and num_out_tensors > 1:
        ctor_extra_calls.append("SetNumOutTensors({});".format(num_out_tensors))

    if output_shape_fn:
        ctor_extra_calls.append("SetComputeOutputShapes({});".format(output_shape_fn))

    if custom_fill_params:
        ctor_extra_calls.append("SetFillParams({});".format(custom_fill_params))

    if tpc_param:
        assert (
            custom_fill_params is None
        ), "Should not define both `tpc_param` and `custom_fill_params` for {}".format(
            fname
        )
        params = []
        for param_data in tpc_param["params"]:
            if len(param_data):
                idx, cast_type = param_data
                params.append("stack[{}].toScalar().to<{}>()".format(idx, cast_type))
            else:
                params.append("{}")
        fill_params = _FILL_PARAMS.format(
            ns_param=tpc_param["name"], args=", ".join(params)
        )
        ctor_extra_calls.append("SetFillParams({});".format(fill_params))

    if promote_type:
        ctor_extra_calls.append("EnableTypePromotion();")
    elif promote_int_to_float:
        ctor_extra_calls.append("PromoteIntToFloat();")

    if ctxop.get_op_backend_class() == "ReductionBackendTemplate":
        ctor_extra_calls.append(
            "SetReductionVarsIndices({});".format(
                ", ".join(extract_reduction_vars_indices(param_vars))
            )
        )

    return _OPCLASS_HEADER.format(
        op_backend_class=op_backend_class,
        cname=cname,
        guid=guid,
        out_ids=out_ids,
        inplace_ids=inplace_ids,
        scalar_ids=scalar_ids,
        is_out_fn=str(is_out_fn(fname)).lower(),
        ctor_extra_calls="".join(["\n" + " " * 8 + c for c in ctor_extra_calls]),
        custom_handler=custom_handler,
    )


class TensorFetcher(object):
    def __init__(self, var_name):
        self.var_name = var_name
        self.tvar_name = "{}_tensors".format(self.var_name)
        self.optvar_name = "{}_opt".format(var_name)
        self.toptvar_name = "{}_tensors".format(self.optvar_name)
        self.tensors = []
        self.opt_tensors = []
        self.writeable = []

    def add(self, name, writeable):
        if writeable:
            self.writeable.append(len(self.tensors))
        self.tensors.append(name)
        return "{}[{}]".format(self.var_name, len(self.tensors) - 1)

    def add_opt(self, name):
        self.opt_tensors.append(name)
        return "{}[{}]".format(self.optvar_name, len(self.opt_tensors) - 1)

    def get_tensors(self):
        return self.tensors

    def get_opt_tensors(self):
        return self.opt_tensors

    def generate_meta_fetches(self):
        code = ""
        code += "  std::vector<at::Tensor> {} = {{{}}};\n".format(
            self.tvar_name, ", ".join(self.tensors)
        )
        code += ("  auto {} = habana::GetMetaTensorList({});\n").format(
            self.var_name, self.tvar_name
        )
        # Handles conversion of c10::optional<at::Tensor> if exists
        if self.opt_tensors:
            code += "  std::vector<c10::optional<at::Tensor>> {} = {{{}}};\n".format(
                self.toptvar_name, ", ".join(self.opt_tensors)
            )
            code += ("  auto {} = habana::GetMetaOptTensorList({});\n").format(
                self.optvar_name, self.toptvar_name
            )
        return code


def extract_reduction_vars_indices(param_vars):
    reduction_vars_indices = ["c10::nullopt", "c10::nullopt", "c10::nullopt"]
    for i, var in enumerate(param_vars):
        i = str(i)
        if var == "dim":
            reduction_vars_indices[0] = i
        elif var == "keepdim":
            reduction_vars_indices[1] = i
        elif var == "dtype":
            reduction_vars_indices[2] = i

    return reduction_vars_indices


def is_acc_thread_supported(opname, ctxop, rtype, sig):
    if ctxop.get_override_fn():
        return ctxop.get_acc_thread()  # only custom lazy func ops that are supported
    else:
        return (
            rtype.startswith("at::Tensor")  # regular, in-place, _out ops
            or rtype.startswith(
                "const at::Tensor"
            )  # only resize_ op so far, handled as inplace/out (shape change)
            or rtype.startswith("::std::tuple<at::Tensor")  # tuple ops
            or "TensorList" in sig  # TensorList ops
        )

# helper function to determine if op supports eager::EagerOp
def is_eager_op(fname, rtype, sig):
    if not _IS_EAGER:
        return False

    if is_inplace_or_out_op(fname):
        if rtype.startswith("::std::tuple<at::Tensor"):
            return False
        elif rtype == "void" and "TensorList" in sig:
            return False
        elif rtype.startswith("const at::Tensor"):
            return False
        else:
            return True
    else:
        if rtype.startswith("::std::tuple<at::Tensor"):
            return False
        elif "TensorList" in sig:
            return False
        elif rtype == "bool":
            return False
        else:
            return True


def is_inplace_or_out_op(opname):
    if opname.endswith("_out"):
        return True
    if opname.startswith("__"):  # shift specific ops
        return opname.startswith("__i")  # inplace shift ops start with 'i' in name
    else:
        return opname.endswith("_")


def generate_code(ctx, tree, rwxtree, fname, aten_sig, sig, rwsig, funsig, params):
    opname = get_aten_opname(aten_sig)
    ctxop = ctx.get_op(opname)
    op_frontend = "{} {{\n".format(sig)
    op_frontend += generate_entry_debug_code(tree, fname, params)

    tfetcher = TensorFetcher("metatens")
    rtype = get_return_type_str(rwxtree, rwsig)
    if not is_acc_thread_supported(fname, ctxop, rtype, sig):
        op_frontend += "  habana_lazy::NoAccThread no_acc_thread;\n"
    param_vars = []
    meta_param_vars = []
    call_args = []
    fc_params = []
    fc = ctxop.get_fallback_check()

    for i, p in enumerate(params):
        ptype = param_type(p)
        cptype = type_core(ptype)
        pname = param_name(p)

        param_vars.append(pname)

        if cptype == "TensorList":
            xname = "l_{}".format(pname)
            meta_param_vars.append(xname)
        elif cptype == "TensorOptions":
            gcode, xname = rewrite_tensor_options(fname, pname)
            meta_param_vars.append(xname)
        elif cptype == "c10::optional":
            wrapped_type = type_core(get_template_type_list(ptype)[0])
            if wrapped_type == "Tensor":
                xname = tfetcher.add_opt(pname)
                meta_param_vars.append(xname)
            else:
                meta_param_vars.append(pname)
        elif cptype != "Tensor":
            meta_param_vars.append(pname)
        elif type_is_const(ptype):
            xname = tfetcher.add(pname, False)
            meta_param_vars.append(xname)
        else:
            assert cptype == "Tensor"
            xname = tfetcher.add(pname, True)
            meta_param_vars.append(xname)
            call_args.append(pname)

        if rtype == "void":
            if cptype == "TensorList" or cptype == "Tensor":
                call_args.append(pname)
        elif rtype == "const at::Tensor &" and cptype == "Tensor":
            call_args.append(pname)

        if fc and pname in fc[1:]:
            param_types = re.findall(r"([^(,)]+)(?!.*\()", funsig)
            fc_params.append("{} {}".format(param_types[i].strip(), pname))

    fn = ctx.get_function(fname)

    assert len(fc) == 0 or len(fc_params) + 1 == len(
        fc
    ), "Cannot find all params specified for {}.".format(fc[0])

    lazyop_call_args = ""
    if len(call_args):
        lazyop_call_args = "{}".format(", ".join(call_args))
        if type_core(tree.children[0]) == "::std::tuple":
            lazyop_call_args = "{}({})".format(rtype, lazyop_call_args)
    op_frontend += frontend(
        ctxop,
        tfetcher,
        fn,
        fname,
        aten_sig,
        rtype,
        param_vars,
        meta_param_vars,
        lazyop_call_args,
        sig,
    )

    if ctxop.get_override_fn():
        op_backend = None
        op_backend_class = None

        skip_check = (
            ctxop.get_op_frontend_class() == "LazyOp"
            and ctxop.get_op_backend_class() == "OpBackend"
        )
        # Allow reuse of reduction template for cpu fallback checks with override_fn
        skip_check |= (
            ctxop.get_op_template() is not None
            and ctxop.get_op_template() == "reduction"
        )
        assert (
            skip_check
        ), "{} has defined override_fn, it cannot take op_frontend or op_backend".format(
            opname
        )
    else:
        op_backend_class = "Gen{}".format(opname.replace(".", "_"))
        op_backend = get_op_backend_class_impl(
            ctxop, fname, op_backend_class, len(call_args), param_vars
        )

    return op_frontend, op_backend, op_backend_class, ctxop, fc_params


def get_aten_opname(aten_sig):
    return aten_sig.split("(")[0].split("::")[1]


def get_op_group(opname):
    opgroup = opname.split(".")[0]
    is_dunder = opgroup.startswith("__") and opgroup.endswith("__")
    if not is_dunder and opgroup.endswith("_"):
        opgroup = opgroup[:-1]
    return opgroup


def get_hpu_wrapper(fndef, ctx):
    tree = _PARSER.parse(fndef.cpp_sig)
    xtree = _XPARSER.parse(fndef.cpp_sig)
    mapsig = create_map_sig(xtree, fndef.cpp_sig)
    rwsig = rewrite_signature(fndef.cpp_sig, _TYPE_NSMAP)
    rwxtree = _XPARSER.parse(rwsig)
    params = get_parameters(tree)
    aten_sig = fndef.aten_sig
    funsig = create_stdfunc_sig(rwxtree, rwsig)

    def gen_fnname(x):
        return "{}".format(x)

    op_frontend = None
    op_backend = None
    cname = None
    ctxop = None
    fc_params = None
    opname = get_aten_opname(aten_sig)
    opgroup = get_op_group(opname)
    sig, fname, xfname = get_function_signature(rwxtree, rwsig, gen_fnname)

    if opname in ctx.op_data:
        if not fndef.dispatch:
            print("{} has dispatch=False".format(opname))

        op_frontend, op_backend, cname, ctxop, fc_params = generate_code(
            ctx, tree, rwxtree, fname, aten_sig, sig, rwsig, funsig, params
        )

        # Use default flag from pytorch when force_default is not defined or in eager flow
        if ctxop.force_default() is None or _IS_EAGER:
            default = fndef.default
        else:
            default = ctxop.force_default()
            if default == fndef.default:
                print("No need to force it to False for {}".format(opname))

        if default:
            print("{} has default={}".format(opname, default))

    return OpGen(
        tree=tree,
        xtree=xtree,
        rwxtree=rwxtree,
        func=fname,
        xfunc=xfname,
        op_frontend=op_frontend,
        op_backend=op_backend,
        cname=cname,
        sig=fndef.cpp_sig,
        rwsig=rwsig,
        cppsig=sig,
        mapsig=mapsig,
        funsig=funsig,
        aten_sig=aten_sig,
        dispatch=fndef.dispatch,
        default=fndef.default,
        ctxop=ctxop,
        opgroup=opgroup,
        fc_params=fc_params,
    )


def is_tensor_api(fndef):
    fndef = fndef.replace("at::", "")
    fndef = fndef.replace("c10::Device", "Device")
    m = re.search(r"\bTensor\b", fndef)
    return m is not None, fndef


def create_funcdef(fndef, jdata):
    fields = json.loads(jdata)
    return FuncDef(
        cpp_sig=fndef,
        aten_sig=fields["schema"],
        dispatch=fields.get("dispatch", "False") == "True",
        default=fields.get("default", "False") == "True",
    )


def extract_functions(path):
    functions = []
    errors = []

    for line in open(path, "r"):
        m = re.match(r"\s*([^\s].*); //\s+(.*)", line)
        if not m:
            continue
        fndef = m.group(1)
        try:
            _XPARSER.parse(fndef)
            functions.append(create_funcdef(fndef, m.group(2)))
        except Exception as e:
            if is_tensor_api(fndef)[0]:
                errors.append((fndef, str(e)))
                print('Error parsing "{}": {}'.format(fndef, e), file=sys.stderr)
    return functions, errors


def get_mapsig_key(mapsig):
    # PyTorch generates std::tuple<> without space among the tuple types,
    # which would require special understanding in the string rewriter.
    # Since we are using this as simple key, we can just string the spaces.
    return mapsig.replace(" ", "")


def parse_local_overrides(path):
    functions = []
    fndef = None
    in_namespace_hpu_ver = False
    for line in open(path, "r"):
        line = line.strip()
        if line == "namespace hpu_wrap {":
            in_namespace_hpu_ver = True
        elif line == "} // namespace hpu_wrap":
            in_namespace_hpu_ver = False
        elif in_namespace_hpu_ver:
            if not fndef:
                m = re.match(r"([_a-zA-Z:\(].*);", line)
                if m:
                    functions.append(m.group(1))
                    continue
                m = re.match(r"([_a-zA-Z:\(].*)", line)
                if m:
                    fndef = m.group(1)
            else:
                fndef = "{} {}".format(fndef, line)
                if fndef.endswith(";"):
                    functions.append(fndef[:-1])
                    fndef = None
    assert fndef is None

    overrides = {}
    for fndef in functions:
        # Discard hpu_wrap functions which are not ATEN.
        is_tensor, fndef = is_tensor_api(fndef)
        if is_tensor:
            try:
                xtree = _XPARSER.parse(fndef)
            except lark.UnexpectedToken:
                print("Unable to parse fndef:", fndef)
                raise
            mapsig_key = get_mapsig_key(create_map_sig(xtree, fndef))
            overrides[mapsig_key] = fndef
    return overrides


def generate_impl(aten_sig, overload, override_fn):
    code = '  m.impl("{}", static_cast<{}>(&{}));\n'.format(
        aten_sig.split("(")[0].split("::")[1], overload, override_fn
    )
    return code


def generate_dtype_macro(dtypes):
    def generate_line(dd_pairs, suffix=""):
        code = []
        for dd_pair in dd_pairs:
            dev_type, dtypes = dd_pair
            assert isinstance(dtypes, list)
            dtypes_set = set(dtypes)
            assert len(dtypes) == len(
                dtypes_set
            ), "Found same dtype defined more than once!"

            assert not any(x in dtypes_set for x in ["Double", "Long", "Bool"]), (
                "Double, Long and Bool are not natively supported, they are "
                "treated as Float, Int and Char respectively. For instance if "
                "Float is a supported dtype, Double is added as a supported dtype "
                "by the script."
            )

            # TODO: Workaround for Fp8r152 in upstream. Needs to be fixed elsewhere.
            if Version(torch.__version__) > Version("1.13") and "Fp8r152" in dtypes:
                dtypes.remove("Fp8r152")
            if "Float" in dtypes:
                dtypes.append("Double")
            if "Int" in dtypes:
                dtypes.append("Long")
            if "Char" in dtypes:
                dtypes.append("Bool")
            code.append(
                "{{{}, {{{}}}}}".format(
                    _DEVICE_STR_TO_ENUM[dev_type],
                    ", ".join(["at::k" + d for d in dtypes]),
                )
            )
        return "  HPU_SUPPORTED_DTYPES(({{{}}}){})\n".format(
            ",\n   ".join(code), ", " + suffix if suffix else ""
        )

    if isinstance(dtypes, list):
        return generate_line([(-1, dtypes)])
    elif isinstance(dtypes, dict) and not any(
        x in dtypes.keys() for x in _DEVICE_STR_TO_ENUM.keys()
    ):
        lines = ""
        for k, v in dtypes.items():
            lines += generate_line([(-1, v)], k)
        return lines
    else:
        assert isinstance(dtypes, dict)
        if all(isinstance(x, list) for x in dtypes.values()):
            return generate_line(dtypes.items())
        args = defaultdict(list)
        for k, v in dtypes.items():
            for suffix, dt in v.items():
                args[suffix].append((k, dt))
        lines = ""
        for suffix, arg in args.items():
            lines += generate_line(arg, suffix)
        return lines


def generate_all(fgen):
    dtype_defs = ""
    op_frontend_functions = ""
    op_backend = ""
    kr_regs = ""
    torch_regs = ""
    custom_schema_regs = ""

    # torch registrations
    mapsig_key = get_mapsig_key(fgen.mapsig)
    override_fn = "habana::{}".format(fgen.func)
    pos = fgen.funsig.find("(")
    overload = fgen.funsig[:pos] + " (*)" + fgen.funsig[pos:]
    impl = generate_impl(fgen.aten_sig, overload, override_fn)
    assert fgen.mapsig not in _FN_AUTOGRAD_HPU
    torch_regs += impl

    if fgen.op_frontend:
        # Lazy functions
        op_frontend_functions += "{}\n\n".format(fgen.op_frontend)

    # Lowering Kernel code
    if fgen.op_backend:
        op_backend += "{}\n".format(fgen.op_backend)
        op = fgen.aten_sig.split("(")[0].split("::")[1]
        ns = "hpu" if fgen.ctxop.custom_schema() else "aten"
        kr_regs += '.REGISTER_HPU_BACKEND("{}::{}", {})\n'.format(ns, op, fgen.cname)

    # Custom schema definitions
    if fgen.ctxop.custom_schema():
        custom_schema_regs += '  m.def("{}");\n'.format(fgen.ctxop.custom_schema())

    return (
        dtype_defs,
        op_frontend_functions,
        torch_regs,
        op_backend,
        kr_regs,
        custom_schema_regs,
    )


def generate_op_backend_hclasses(fgens, classes, header_file):
    code = ""
    for fgen in fgens:
        fclass = fgen.ctxop.get_op_backend_class()
        if fclass.endswith("Template"):
            continue
        if fclass != "OpBackend" and fclass not in classes.keys():
            code += "HPU_OP_BACKEND({})\n".format(fclass)
            classes[fclass] = header_file
    return code


def generate_op_frontend_hclasses(fgens, classes, header_file):
    code = ""
    for fgen in fgens:
        fclass = fgen.ctxop.get_op_frontend_class()
        if fclass == "LazyOp":
            continue
        if fclass.endswith("Template"):
            continue
        if fclass in classes:
            continue
        code += "HPU_OP_FRONTEND({})\n".format(fclass)
        classes[fclass] = header_file
    return code


def generate_header_decls(fgens):
    fill_params = set()
    outshape_fns = set()
    fc_fns = set()

    def build(fn, fns_set, macro, args=[]):
        if fn and fn not in fns_set:
            fns_set.add(fn)
            return "{}({});\n".format(macro, ", ".join([fn] + args))
        return ""

    reg_decls = ""
    outshape_decls = ""
    fill_params_decls = ""
    fallback_check_decls = ""
    for fgen in fgens:
        reg_decls += "{};\n".format(fgen.rwsig)
        outshape_decls += build(
            fgen.ctxop.get_custom_output_shape(), outshape_fns, "OUTSHAPE_DECL"
        )
        fill_params_decls += build(
            fgen.ctxop.get_custom_fill_params(), fill_params, "FILL_PARAMS_DECL"
        )

        fc = fgen.ctxop.get_fallback_check()
        if fc:
            fallback_check_decls += build(
                fc[0], fc_fns, "FALLBACK_CHECK", fgen.fc_params
            )

    return reg_decls + outshape_decls + fill_params_decls + fallback_check_decls


def gen_output_file(args, name):
    if not args.output_dir:
        return sys.stdout
    filename=os.path.join(args.output_dir, name)
    if not os.path.exists(os.path.dirname(filename)):
        os.makedirs(os.path.dirname(filename))
    return open(filename, "w")


def gen_h_output_file(args, opgroup):
    return gen_output_file(args, "{}.h".format(opgroup))


def gen_cpp_output_file(args, opgroup):
    return gen_output_file(args, "{}.cpp".format(opgroup))


def _ensure_no_registrations_are_present_in_both(overrides, pt_ver_overrides):
    intersection = set(overrides).intersection(pt_ver_overrides)
    if intersection:
        print("Same overloads present in core and version-specific kernel "
              "declarations: ")
        for elem in intersection:
            print(" *", elem)
        assert False


def _print_missed_override_error(overridden, mapsig, cpp_sig, mapsig_key):
    print("hpu_wrap function missed override: {}; // {}".format(cpp_sig, mapsig),
          file=sys.stderr)
    func_name = mapsig_key.split("(")[0]
    for o in overridden:
        if o.split("(")[0] == func_name:
            print("Note: override with same function name exists: ", o)


def gen_manual_op_registrations(fgens, args):
    overrides = parse_local_overrides(args.hputype)
    pt_ver_overrides = parse_local_overrides(args.pt_ver_hputype)
    _ensure_no_registrations_are_present_in_both(overrides, pt_ver_overrides)
    overrides.update(pt_ver_overrides)

    def check_overrides(overrides, overridden):
        misses = 0
        for mapsig, cpp_sig in overrides.items():
            mapsig_key = get_mapsig_key(mapsig)
            if mapsig_key not in overridden:
                # In eager flow, we skip non mandatory ops registration without asserting here
                if not _IS_EAGER:
                    misses += 1
                _print_missed_override_error(overridden, mapsig, cpp_sig, mapsig_key)
        return misses == 0

    aten_code = "TORCH_LIBRARY_IMPL(aten, HPU, m) {\n"
    autogradhpu_code = (
        "TORCH_LIBRARY_IMPL(aten, AutogradHPU, m) {\n  static_cast<void>(m);\n"
    )
    overridden = set()
    for fgen in fgens:
        if _IS_EAGER and not (fgen.dispatch and not fgen.default):
            continue

        mapsig_key = get_mapsig_key(fgen.mapsig)
        if mapsig_key in overrides:
            override_fn = "hpu_wrap::{}".format(fgen.func)
            overridden.add(mapsig_key)

            pos = fgen.funsig.find("(")
            overload = fgen.funsig[:pos] + " (*)" + fgen.funsig[pos:]
            impl = generate_impl(fgen.aten_sig, overload, override_fn)
            if fgen.mapsig in _FN_AUTOGRAD_HPU:
                autogradhpu_code += impl
            else:
                aten_code += impl

    assert check_overrides(overrides, overridden)
    print(
        "{} function manual overrides in {} and {}".format(len(overridden), args.hputype, args.pt_ver_hputype),
        file=sys.stdout,
    )

    _REGS = """// Autogenerated file by {gen}. Do not edit directly!
#include "habana_kernels/wrap_kernels_declarations.h"
#include "habana_kernels_ver/wrap_kernels_declarations.h"

namespace habana {{
{regs}
}}  // namespace habana
"""
    regs = aten_code + "\n}\n" + autogradhpu_code + "\n}\n"

    print(
        _REGS.format(
            gen=os.path.basename(sys.argv[0]),
            regs=regs,
        ),
        file=gen_cpp_output_file(args, "wrap_kernels_registrations"),
    )


# Generate file with all potential ops for autocast. The actual ops registered
# for autocast are based on the default lists in autocast_helpers.h file or
# on the external file provided via env.
def generate_autocast_ops(fgens, args):
    op_registration = '  KERNEL({function_name}, "{op_name}", {signature})\n'
    replacements = (
        ("::std::tuple<at::Tensor,at::Tensor>", "tuple_2_tensors"),
        ("::std::tuple<at::Tensor,at::Tensor,at::Tensor>", "tuple_3_tensors"),
        (
            "::std::tuple<at::Tensor,at::Tensor,at::Tensor,at::Tensor>",
            "tuple_4_tensors",
        ),
        (
            "::std::tuple<at::Tensor,at::Tensor,at::Tensor,at::Tensor,at::Tensor>",
            "tuple_5_tensors",
        ),
        (
            "::std::tuple<at::Tensor,at::Tensor,at::Tensor,at::Tensor,at::Tensor,at::Tensor>",
            "tuple_6_tensors",
        ),
        (
            "::std::tuple<at::Tensor,at::Tensor,at::Tensor,at::Tensor,int64_t>",
            "tuple_4_tensors_int64",
        ),
        (
            "::std::tuple<at::Tensor,at::Tensor,double,int64_t>",
            "tuple_2_tensors_double_int64",
        ),
        (
            "::std::tuple<at::Tensor,at::Tensor,at::Tensor,::std::vector<at::Tensor>>",
            "tuple_3_tensors_vector",
        ),
        ("::std::tuple<double,int64_t>", "tuple_double_int64"),
        ("::std::tuple<at::Tensor,::std::vector<at::Tensor>>", "tuple_tensor_vector"),
        ("::std::tuple<::std::vector<at::Tensor>,at::Tensor>", "tuple_vector_tensor"),
        (
            "::std::tuple<at::Tensor,::std::vector<at::Tensor>,::std::vector<at::Tensor>>",
            "tuple_tensor_2_vectors",
        ),
        ("SymIntArrayRef", "IntArrayRef"),
        ("c10::SymInt", "int64_t"),
    )

    blocklist = (
        "_cummax_helper",
        "_cummin_helper",
        "fused_moving_avg_obs_fake_quant",
        "_fused_moving_avg_obs_fq_helper",
        "_fused_adam",
    )

    def op_to_skip(function_name, op_name):
        return (
            function_name.endswith(("_out", "_"))
            or any(s in function_name for s in ("_.", "cuda", "cudn"))
            or op_name in blocklist
        )

    def get_registration(fgen, op_name):
        function_name = fgen.func
        signature = fgen.funsig
        if op_to_skip(function_name, op_name):
            return ""
        for r in replacements:
            signature = signature.replace(*r)
        return op_registration.format(
            function_name=function_name, op_name=op_name, signature=signature
        )

    # only ops defined in 'at' namespace are applicable for autocast
    ops_not_in_at = set()
    with open(args.native_functions, "r") as f:
        native_functions = yaml.load(f.read(), Loader=Loader)
    for function in native_functions:
        if "variants" in function and "function" not in function["variants"]:
            ops_not_in_at.add(re.search(r"(.*?)\(", function["func"]).group(1))

    ops_registrations = ""
    for fgen in fgens:
        op_name = re.search(r"aten::(.*?)\(", fgen.aten_sig).group(1)
        if op_name in ops_not_in_at:
            continue
        ops_registrations += get_registration(fgen, op_name)

    print(
        _AUTOCAST_TEMPLATE.format(
            gen=os.path.basename(sys.argv[0]),
            ops_registrations=ops_registrations,
        ),
        file=gen_cpp_output_file(args, "hpu_autocast_ops"),
    )


def generate(args):
    fndefs, errors = extract_functions(args.typedef)
    assert len(errors) == 0

    fgens = []
    fgens_manual = []
    fgen_files = defaultdict(list)
    ctx = Context(args.functions, args.yaml)

    for ts in fndefs:
        try:
            fgen = get_hpu_wrapper(ts, ctx)
            if fgen.ctxop:
                fgens.append(fgen)
                fgen_files[fgen.opgroup].append(fgen)
            else:
                fgens_manual.append(fgen)
        except Exception as e:
            print("Failed to generate op {}: {}".format(ts, e), file=sys.stderr)
            errors.append(e)

    gen_manual_op_registrations(fgens_manual, args)
    generate_autocast_ops(fgens + fgens_manual, args)

    print("Generated {} ops from {}".format(len(fgens), args.yaml), file=sys.stdout)
    assert len(errors) == 0, "Found {} errors: {}".format(len(errors), errors)

    if len(ctx.op_data) != len(fgens):
        fgen_data = [get_aten_opname(x.aten_sig) for x in fgens]
        for op in ctx.op_data.keys():
            if op not in fgen_data:
                print("Cannot generate {}, skipping it...".format(op), file=sys.stderr)

    if _IS_EAGER:
        fgens = [x for x in fgens if x.dispatch and not x.default]

    num_shards = 10
    num_fgens_per_shard = len(fgens) // num_shards
    gen_file_idx = 0
    dtype_defs = ""
    functions = ""
    torch_regs = ""
    op_backend = ""
    kr_regs = ""
    custom_schema_regs = ""
    header_inclusions = ""
    # TODO only iwyu
    for h in fgen_files.keys():
        header_inclusions += '#include "' + h + '.h"\n'
    for idx, fgen in enumerate(fgens):
        (
            _dtype_defs,
            _functions,
            _torch_regs,
            _op_backend,
            _kr_regs,
            _custom_schema_regs,
        ) = generate_all(fgen)
        dtype_defs += _dtype_defs
        functions += _functions
        torch_regs += _torch_regs
        op_backend += _op_backend
        kr_regs += _kr_regs
        custom_schema_regs += _custom_schema_regs

        if (
            (gen_file_idx + 1) < num_shards and (idx + 1) % num_fgens_per_shard == 0
        ) or (idx + 1) == len(fgens):
            lazy_inclusions = '\n' \
                              '#include "habana_kernels/lazy_kernels_declarations.h"\n' \
                              '#include "habana_kernels_ver/lazy_kernels_declarations.h"\n' \
                              '#include "hpu_ops/cpu_fallback.h"\n' \
                              '#include "hpu_ops/lazy/reduction_template.h"\n' \
                              '#include "hpu_ops/op_validator.h"\n'
            backend_inclusions = '\n' \
                              '#include "hpu_ops/backend/reduction_template.h"\n'

            print(
                _CPP_HEADER.format(
                    gen=os.path.basename(sys.argv[0]),
                    header_inclusions=lazy_inclusions + header_inclusions + ('#include "habana_kernels/eager_op.h"' if _IS_EAGER else ""),
                    dtype_defs=dtype_defs,
                    funcs=functions,
                    op_backend="",
                    kr_regs="",
                    torch_regs=torch_library_impl(torch_regs),
                    custom_schema_regs=torch_library_fragment(custom_schema_regs),
                    file_idx=gen_file_idx,
                ),
                file=gen_cpp_output_file(args, "lazy/hpu_op{}".format(gen_file_idx)),
            )
            print(
                _CPP_HEADER.format(
                    gen=os.path.basename(sys.argv[0]),
                    header_inclusions=backend_inclusions + header_inclusions,
                    dtype_defs=dtype_defs,
                    funcs="",
                    op_backend=op_backend,
                    kr_regs=kr_regs,
                    torch_regs="",
                    custom_schema_regs="",
                    file_idx=gen_file_idx,
                ),
                file=gen_cpp_output_file(args, "backend/hpu_op{}".format(gen_file_idx)),
            )
            gen_file_idx += 1
            dtype_defs = ""
            functions = ""
            torch_regs = ""
            op_backend = ""
            kr_regs = ""
            custom_schema_regs = ""

    frontend_class_headers = {}
    backend_class_headers = {}

    for fgen_file, ffgens in fgen_files.items():
        op_backend_classes = generate_op_backend_hclasses(
            ffgens, backend_class_headers, fgen_file
        )
        op_frontend_classes = generate_op_frontend_hclasses(
            ffgens, frontend_class_headers, fgen_file
        )

        header_decls = generate_header_decls(ffgens)

        # Create output files ...
        print(
            _H_HEADER.format(
                op=fgen_file,
                gen=os.path.basename(sys.argv[0]),
                op_backend_classes="",
                op_frontend_classes=op_frontend_classes,
                header_decls=header_decls,
            ),
            file=gen_h_output_file(args, "lazy/"+fgen_file),
        )
        print(
            _H_HEADER.format(
                op=fgen_file,
                gen=os.path.basename(sys.argv[0]),
                op_backend_classes=op_backend_classes,
                op_frontend_classes="",
                header_decls=header_decls,
            ),
            file=gen_h_output_file(args, "backend/"+fgen_file),
        )


if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("--output_dir", metavar="OUTPUT_DIR", type=str)
    arg_parser.add_argument(
        "--yaml",
        default=os.path.join(
            os.path.dirname(os.path.realpath(__file__)), "hpu_op.yaml"
        ),
        help="The path to the Hpu Op yaml file",
    )
    arg_parser.add_argument(
        "hputype",
        type=str,
        metavar="HPU_TYPE_FILE",
        help="The path to the HPU manual overrides file",
    )
    arg_parser.add_argument(
        "pt_ver_hputype",
        type=str,
        metavar="PT_VER_HPU_TYPE_FILE",
        help="The path to the HPU manual overrides file with functions specific"
        "to the current PT version",
    )
    arg_parser.add_argument(
        "typedef",
        type=str,
        metavar="TYPE_DEFAULT_FILE",
        help="The path to the TypeDefault.h file",
    )
    arg_parser.add_argument(
        "functions",
        type=str,
        metavar="FUNCTIONS_FILE",
        help="The path to the Functions.h file",
    )
    arg_parser.add_argument(
        "native_functions",
        type=str,
        metavar="NATIVE_FUNCTIONS_FILE",
        help="The path to the native_functions.yaml file",
    )
    args, files = arg_parser.parse_known_args()

    generate(args)
