from __future__ import print_function

import argparse
import collections.abc
import lark
import json
import os
import re
import sys
import yaml
from yaml import Loader


def namedtuple_with_defaults(typename, field_names, default_values=()):
    ntuple = collections.namedtuple(typename, field_names)
    ntuple.__new__.__defaults__ = (None,) * len(ntuple._fields)
    if isinstance(default_values, collections.abc.Mapping):
        prototype = ntuple(**default_values)
    else:
        prototype = ntuple(*default_values)
    ntuple.__new__.__defaults__ = tuple(prototype)
    return ntuple


FuncDef = namedtuple_with_defaults("FuncDef", "cpp_sig, aten_sig, dispatch, default")

OpGen = namedtuple_with_defaults(
    "OpGen",
    "tree, xtree, rwxtree, func, xfunc, op_frontend, op_backend, cname, sig, rwsig, cppsig, funsig, mapsig, aten_sig, dispatch, default, ctxop",
)

_GRAMMAR = r"""
    start: type fnname "(" params ")"
    type: CONST? core_type refspec?
    fnname: CNAME
    refspec: REF
           | PTR
    core_type: template
        | TNAME
    template: TNAME "<" typelist ">"
    typelist: type
            | type "," typelist
    REF: "&"
    PTR: "*"
    CONST: "const"
    TNAME: /[a-zA-Z0-9_:]+/
    HEXNUMBER: /0x[0-9a-fA-F]+/
    params: param
          | param "," params
    param: type param_name param_defval?
    param_name: CNAME

    param_defval: "=" init_value
    init_value: "true"
              | "false"
              | "{}"
              | NUMBER
              | SIGNED_NUMBER
              | HEXNUMBER
              | ESCAPED_STRING

    %import common.CNAME -> CNAME
    %import common.NUMBER -> NUMBER
    %import common.SIGNED_NUMBER -> SIGNED_NUMBER
    %import common.ESCAPED_STRING -> ESCAPED_STRING
    %import common.WS
    %ignore WS
    """

_PARSER = lark.Lark(_GRAMMAR, parser="lalr", propagate_positions=True)

_XPARSER = lark.Lark(
    _GRAMMAR, parser="lalr", propagate_positions=True, keep_all_tokens=True
)

_FN_AUTOGRAD_HPU = set([])

_TYPE_NSMAP = {
    "Tensor": "at::Tensor",
    "TensorList": "at::TensorList",
    "Scalar": "at::Scalar",
    "Storage": "at::Storage",
    "IntList": "at::IntList",
    "IntArrayRef": "at::IntArrayRef",
    "OptionalIntArrayRef" : "at::OptionalIntArrayRef",
    "ArrayRef": "at::ArrayRef",
    "Generator": "at::Generator",
    "Layout": "at::Layout",
    "ScalarType": "at::ScalarType",
    "TensorOptions": "at::TensorOptions",
    "SparseTensorRef": "at::SparseTensorRef",
    "Device": "c10::Device",
    "optional": "c10::optional",
    "MemoryFormat": "at::MemoryFormat",
    "QScheme": "at::QScheme",
    "ConstQuantizerPtr": "at::ConstQuantizerPtr",
    "Dimname": "at::Dimname",  # namedtensor-only
    "DimnameList": "at::DimnameList",  # namedtensor-only
}

_H_HEADER = """// Autogenerated file by {gen}. Do not edit directly!

#include <ATen/Tensor.h>
#include <c10/core/Stream.h>

#include "hpu_ops/hpu_op_helper.h"
#include "habana_kernels/lazy_kernels.h"

using c10::Stream;

namespace habana {{

class HpuOp{{
 public:
{hfuncs}
}};

{op_backend_classes}

{op_frontend_classes}

{fill_params_decls}

{outshapes_decls}
}}  // namespace habana
"""

_CPP_HEADER = """// Autogenerated file by {gen}. Do not edit directly!
#include "hpu_op.h"

#include <ATen/Context.h>
#include <ATen/CPUGeneratorImpl.h>
#include <torch/library.h>

#include "habana_helpers/tensor_utils.h"
#include "synapse_helpers/env_flags.h"
#include "habana_kernels/aten_hpu_type_default.h"
#include "habana_kernels/wrap_kernels_declarations.h" // Temporary: Remove when lazy=2 is default
#include "hpu_ops/reduction_template.h"

using habana_lazy::LazyOp;
using habana_lazy::LazyOpWithTypePromotion;
using habana_lazy::PromoteIntToFloat;
using synapse_helpers::graph;
using torch::jit::Stack;

namespace habana {{

{dtype_defs}

{funcs}

{op_backend}

{kr_regs}

{torch_regs}

{custom_schema_regs}
}}  // namespace habana
"""

_OPCLASS_HEADER = """struct {cname} : {op_backend_class} {{
  {cname}(int device_id, c10::ScalarType scalar_type) :
      {op_backend_class}(device_id, \"{guid}_\", scalar_type, {{{out_ids}}}, {{{inplace_ids}}}, {{{scalar_ids}}}, {is_out_fn}) {{{ctor_extra_calls}
  }}{custom_handler}
}};
"""

_CUSTOM_HANDLER = """

  void CustomHandler(graph &g, Stack& stack) override {{
    static_cast<void>(g);
    static_cast<void>(stack);
    {body}
  }}"""

_FILL_PARAMS = """[](const at::Stack& stack, size_t& size) {{
            using T = {ns_param};
            size = sizeof(T);
            return std::make_shared<T>(T{{{args}}});
        }}"""


class Op(object):
    def __init__(self, opname, op):
        self.op = op
        self.opname = opname

    def get_guid(self):
        return self.op.get("guid", None)

    def get_dtypes(self):
        return self.op.get("dtypes", None)

    def get_tpc_param(self):
        return self.op.get("tpc_param", None)

    def get_layouts(self):
        return self.op.get("layouts", [])

    def get_synapse_layouts(self):
        return self.op.get("synapse_layouts", [])

    def get_op_backend_class(self):
        if self.get_op_template():
            if self.get_op_template() == "reduction":
                return "ReductionBackendTemplate"
            assert "Unknown template: {}".format(self.get_op_template())
        return self.op.get("op_backend", "OpBackend")

    def get_op_frontend_class(self):
        op_frontend_class = self.op.get("op_frontend", None)
        if op_frontend_class:
            return op_frontend_class
        elif self.get_op_template():
            if self.get_op_template() == "reduction":
                return "ReductionFrontendTemplate"
            assert "Unknown template: {}".format(self.get_op_template())

        # TODO: Change type promotion classes to template class
        if self.supports_type_promotion():
            return "LazyOpWithTypePromotion"
        elif self.promote_int_to_float():
            return "PromoteIntToFloat"
        return "LazyOp"

    def get_op_template(self):
        return self.op.get("op_template", None)

    def get_custom_fill_params(self):
        return self.op.get("custom_fill_params", None)

    def get_custom_output_shape(self):
        if self.op.get("broadcast", False):
            assert (
                self.op.get("custom_output_shape", None) is None
            ), "broadcast will insert custom_output_shape, so no need to define it."
            return "BinaryOutputShape"

        return self.op.get("custom_output_shape", None)

    def get_inplace_ids(self):
        return self.op.get("inplace_ids", [])

    def get_out_ids(self):
        return self.op.get("out_ids", [])

    def get_scalar_ids(self):
        return self.op.get("scalar_ids", [])

    def is_legacy_reqd(self):
        return self.op.get("legacy_eager", False)

    def use_meta(self):
        return self.op.get("use_meta", False)

    def force_default(self):
        return self.op.get("force_default", None)

    def supports_type_promotion(self):
        return self.op.get("type_promotion", False)

    def promote_int_to_float(self):
        return self.op.get("promote_int_to_float", False)

    def custom_schema(self):
        args = self.op.get("schema_args", None)
        if args:
            return self.opname + args

    def get_fallback_check(self):
        return self.op.get("fallback_check", None)


class Context(object):
    def __init__(self, functions, yamlfile):
        with open(functions, "r") as ff:
            self.functions_data = ff.read()

        with open(yamlfile, "r") as ff:
            self.op_data = yaml.load(ff.read(), Loader=Loader)

    def get_function(self, name):
        if self.functions_data.find(" {}(".format(name)) >= 0:
            return "at::{}".format(name + "f" if is_out_fn(name) else name)

    def get_op(self, opname):
        return Op(opname, self.op_data[opname])


class StringEmit(object):
    def __init__(self, sref):
        self.sref = sref
        self.sval = ""
        self.pos = -1

    def __repr__(self):
        return self.sval

    def advance(self, t):
        start = t.column - 1
        end = t.end_column - 1
        pos = self.pos if self.pos >= 0 else start
        if start > pos:
            self.sval += self.sref[pos:start]
        self.sval += t.value
        self.pos = end

    def skip(self, t):
        self.pos = last_match(t) if self.pos >= 0 else -1

    def append(self, s):
        self.sval += s
        self.pos = -1


def first_match(t):
    if isinstance(t, lark.lexer.Token):
        return t.column - 1
    assert isinstance(t, lark.tree.Tree)
    return first_match(t.children[0])


def last_match(t):
    if isinstance(t, lark.lexer.Token):
        return t.end_column - 1
    assert isinstance(t, lark.tree.Tree)
    return last_match(t.children[-1])


def for_every_token(t, fn):
    if isinstance(t, lark.lexer.Token):
        fn(t)
    else:
        assert isinstance(t, lark.tree.Tree)
        for c in t.children:
            for_every_token(c, fn)


def emit_string(t, emit, emit_fn):
    status = emit_fn(t)
    if status > 0:

        def do_emit(tok):
            emit.advance(tok)

        for_every_token(t, do_emit)
    elif status == 0:
        if isinstance(t, lark.lexer.Token):
            emit.advance(t)
        else:
            assert isinstance(t, lark.tree.Tree)
            for c in t.children:
                emit_string(c, emit, emit_fn)
    else:
        emit.skip(t)


def typed_child(t, n, ttype):
    assert isinstance(t, lark.tree.Tree)
    assert n < len(t.children)
    c = t.children[n]
    assert isinstance(c, lark.tree.Tree)
    assert c.data == ttype, t.pretty()
    return c


def rewrite_sig(tree, orig_sig, emit_fn=lambda x: 0):
    emit = StringEmit(orig_sig)
    emit_string(tree, emit, emit_fn)
    return str(emit)


def rewrite_signature(sig, tmap):
    def rewrite(t):
        if t.type == "TNAME":
            new_type = tmap.get(t.value, None)
            if new_type is not None:
                t.value = new_type

    def emit_fn(t):
        if isinstance(t, lark.lexer.Token):
            return 0
        return -1 if t.data == "param_defval" else 0

    xtree = _XPARSER.parse(sig)
    for_every_token(xtree, rewrite)
    return rewrite_sig(xtree, sig, emit_fn=emit_fn)


def create_stdfunc_sig(tree, orig_sig):
    def emit_fn(t):
        if isinstance(t, lark.lexer.Token):
            return 0
        return -1 if t.data == "param_name" else 0

    emit = StringEmit(orig_sig)
    # Emit full function return type.
    emit_string(typed_child(tree, 0, "type"), emit, emit_fn)
    emit.append("(")
    # Emit parameter list w/out parameter names.
    emit_string(typed_child(tree, 3, "params"), emit, emit_fn)
    emit.append(")")
    return str(emit)


def create_map_sig(tree, orig_sig):
    def emit_fn(t):
        if isinstance(t, lark.lexer.Token):
            return -1 if t.type in ["CONST", "REF", "PTR"] else 0
        return -1 if t.data in ["param_name", "param_defval"] else 0

    emit = StringEmit(orig_sig)
    # Emit full function return type.
    emit_string(typed_child(tree, 1, "fnname"), emit, emit_fn)
    emit.append("(")
    # Emit parameter list w/out parameter names.
    emit_string(typed_child(tree, 3, "params"), emit, emit_fn)
    emit.append(") -> ")
    emit_string(typed_child(tree, 0, "type"), emit, emit_fn)
    return str(emit)


def type_core(t):
    assert isinstance(t, lark.tree.Tree)
    for c in t.children:
        if isinstance(c, lark.tree.Tree) and c.data == "core_type":
            c = c.children[0]
            if isinstance(c, lark.lexer.Token):
                return c.value
            assert isinstance(c, lark.tree.Tree) and c.data == "template"
            return c.children[0].value
    raise RuntimeError("Not a type tree: {}".format(t))


def type_is_const(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[0]
    return isinstance(c, lark.lexer.Token) and c.value == "const"


def type_is_refptr(t, kind):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[-1]
    if not isinstance(c, lark.tree.Tree) or c.data != "refspec":
        return False
    c = c.children[0]
    return isinstance(c, lark.lexer.Token) and c.value == kind


def extract_list(t, l):
    assert isinstance(t, lark.tree.Tree)
    l.append(t.children[0])
    if len(t.children) == 2:
        c = t.children[1]
        if isinstance(c, lark.tree.Tree) and c.data == t.data:
            extract_list(c, l)
    return l


def get_template_type_list(t):
    assert isinstance(t, lark.tree.Tree)
    # Skipping type qualifiers if exists.
    # E.g. const c10::optional<T>
    for c in t.children:
        if isinstance(c, lark.tree.Tree) and c.data == "core_type":
            break
    c = c.children[0]
    assert isinstance(c, lark.tree.Tree) and c.data == "template"
    types = []
    return extract_list(c.children[1], types)


def get_function_name(t):
    assert isinstance(t, lark.tree.Tree)
    fname = t.children[1]
    assert isinstance(fname, lark.tree.Tree)
    assert fname.data == "fnname"
    return fname.children[0].value


def is_out_fn(fname):
    return fname.endswith("_out")


def get_function_signature(t, orig_sig, namefn):
    emit = StringEmit(orig_sig)
    # Emit full function return type.
    emit_string(typed_child(t, 0, "type"), emit, lambda t: 0)
    fnname = typed_child(t, 1, "fnname").children[0]
    xfname = namefn(fnname.value)
    emit.append(" {}(".format(xfname))
    # Emit parameter list w/out parameter names.
    emit_string(typed_child(t, 3, "params"), emit, lambda t: 0)
    emit.append(")")
    return str(emit), fnname.value, xfname


def get_parameters(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[2]
    assert isinstance(c, lark.tree.Tree)
    assert c.data == "params"
    params = []
    extract_list(c, params)
    return params


def param_name(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[1]
    assert isinstance(c, lark.tree.Tree)
    assert c.data == "param_name"
    token = c.children[0]
    assert isinstance(token, lark.lexer.Token)
    return token.value


def param_type(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[0]
    assert isinstance(c, lark.tree.Tree)
    return c


def get_return_type_str(t, orig_sig):
    assert isinstance(t, lark.tree.Tree)
    fname = t.children[1]
    assert isinstance(fname, lark.tree.Tree)
    assert fname.data == "fnname"
    token = fname.children[0]
    assert isinstance(token, lark.lexer.Token)
    return orig_sig[0 : token.column - 2]


def generate_entry_debug_code(t, fname, params):
    # Emits debug code for a given intercepted function.
    code = "  PT_OP_TRACE;\n"
    code += '  PT_KERNEL_DEBUG("HpuOp {} :"'.format(fname)
    for p in params:
        ptype = param_type(p)
        pname = param_name(p)
        code += ', " {}=", to_string({})'.format(pname, pname)
    code += ");\n\n"
    return code


def lazyop(
    ctxop, tfetcher, fn, fname, aten_sig, rtype, param_vars, meta_vars, lazyop_call_args
):
    ns = "hpu" if ctxop.custom_schema() else "aten"
    aten_opname = get_aten_opname(aten_sig)
    opname = aten_opname.split(".")[0]
    overload = aten_opname.split(".")[1] if len(aten_opname.split(".")) > 1 else None
    schema_fn = ns + "::" + opname
    op_frontend_class = ctxop.get_op_frontend_class()
    code = ""

    dtypes = ctxop.get_dtypes()
    if dtypes:
        input_tensors = (
            tfetcher.get_tensors()[:-1]
            if is_out_fn(fname) and len(tfetcher.get_tensors()) > 1
            else tfetcher.get_tensors()
        )

        # Check the promoted input when type promotion applies
        if ctxop.supports_type_promotion():
            if overload:
                code += "  FALLBACK_IF_UNSUPPORTED_DTYPE2(at::result_type({}, {}), {}, {}, {})\n".format(
                    param_vars[0],
                    param_vars[1],
                    opname,
                    overload,
                    ", ".join(param_vars),
                )
            else:
                code += "  FALLBACK_IF_UNSUPPORTED_DTYPE(at::result_type({}, {}), {}, {})\n".format(
                    param_vars[0],
                    param_vars[1],
                    opname,
                    ", ".join(param_vars),
                )
        elif ctxop.get_op_template() == "reduction":
            # Here, check for self/dtype for fallback
            has_dtype = "dtype" in param_vars
            code += "  FALLBACK_IF_UNSUPPORTED_DTYPE{}{}(self, {}{}, {}{})\n".format(
                "_ARG" if has_dtype else "",
                "2" if overload else "",
                "dtype, " if has_dtype else "",
                opname,
                overload + ", " if overload else "",
                ", ".join(param_vars),
            )
        else:
            for t in input_tensors:
                if overload:
                    code += (
                        "  FALLBACK_IF_UNSUPPORTED_DTYPE{}2({}, {}, {}, {})\n".format(
                            "_PER_TENSOR" if isinstance(dtypes, dict) else "",
                            t,
                            opname,
                            overload,
                            ", ".join(param_vars),
                        )
                    )
                else:
                    code += "  FALLBACK_IF_UNSUPPORTED_DTYPE{}({}, {}, {})\n".format(
                        "_PER_TENSOR" if isinstance(dtypes, dict) else "",
                        t,
                        opname,
                        ", ".join(param_vars),
                    )
        code += "\n"

    fallback_check = ctxop.get_fallback_check()
    if fallback_check:
        # TODO: Absorb this inside the macro
        code += "  extern std::function<bool({})> {};\n".format(
            ", ".join(["decltype(" + p + ")" for p in param_vars]), fallback_check
        )
        if overload:
            code += "  FALLBACK_IF_UNSUPPORTED_INPUTS2({}, {}, {}, {})\n".format(
                fallback_check, opname, overload, ", ".join(param_vars)
            )
        else:
            code += "  FALLBACK_IF_UNSUPPORTED_INPUTS({}, {}, {})\n".format(
                fallback_check, opname, ", ".join(param_vars)
            )
        code += "\n"

    if ctxop.is_legacy_reqd():
        code += "  if (GET_ENV_FLAG_NEW(PT_HPU_LAZY_MODE) == 0) return hpu_wrap::{}({});\n".format(
            fname, ", ".join(param_vars)
        )
        code += "\n"

    if ctxop.use_meta():
        assert (
            ctxop.get_custom_output_shape() is None
        ), "Both use_meta and custom_output_shape are defined for {}".format(fname)

        assert fn, "{} does not exist in aten.".format(fname)

        code += tfetcher.generate_meta_fetches()
        code += "  at::TensorList metavar = {}({});\n".format(fn, ", ".join(meta_vars))
        code += '  {}<{}> hpu_op{{"{}", {{{}}}, metavar}};\n'.format(
            op_frontend_class, rtype, schema_fn, ", ".join(param_vars)
        )
    else:
        code += '  {}<{}> hpu_op{{"{}", {{{}}}'.format(
            op_frontend_class, rtype, schema_fn, ", ".join(param_vars)
        )
        output_shape_fn = ctxop.get_custom_output_shape()
        if output_shape_fn:
            code += ", {}".format(output_shape_fn)
        elif ctxop.get_op_template() == "reduction":
            dim = "dim" if "dim" in param_vars else "{}"
            keepdim = "keepdim" if "keepdim" in param_vars else "false"
            code += ", ReductionOutputShape(self, {}, {})".format(dim, keepdim)

        code += "};\n"

    if ctxop.get_op_template() == "reduction":
        code += "  hpu_op.SetReductionVarsIndices({});\n".format(
            ", ".join(extract_reduction_vars_indices(param_vars))
        )

    code += "  {}hpu_op.call({})".format(
        "" if rtype == "void" else "return ", lazyop_call_args
    )
    return code + ";\n}"


def bitwise_ops_alt_guid(guid):
    logical_guid = guid.replace("bitwise_", "")
    code = (
        "if (ScalarType() == at::kBool) {{\n"
        '      SetGuid("{}_i8");\n'
        "    }}".format(logical_guid)
    )

    return code


# HACK: Construct tensor from options
def tril_triu_without_tensor():
    # row, col, offset, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_mem
    code = (
        "auto options = at::TensorOptions(at::kHPU).dtype(stack[3].toOptional<c10::ScalarType>());\n"
        "    at::Tensor t = at::empty(ComputeOutputShapes(stack, true)[0], options);\n"
        "    stack.emplace_back(t);"
    )
    return code


def get_op_backend_class_impl(ctxop, fname, cname, num_out_tensors, param_vars):
    guid = ctxop.get_guid()
    out_ids = ctxop.get_out_ids()
    inplace_ids = ctxop.get_inplace_ids()
    scalar_ids = ctxop.get_scalar_ids()
    custom_fill_params = ctxop.get_custom_fill_params()
    tpc_param = ctxop.get_tpc_param()
    op_backend_class = ctxop.get_op_backend_class()
    output_shape_fn = ctxop.get_custom_output_shape()
    promote_type = ctxop.supports_type_promotion()
    promote_int_to_float = ctxop.promote_int_to_float()

    assert (not out_ids) ^ (not inplace_ids) ^ is_out_fn(fname), (
        "`out_ids` or `inplace_ids` should not be defined for {}".format(fname)
        if is_out_fn(fname)
        else "Either `out_ids` or `inplace_ids` should be defined for {}".format(fname)
    )

    scalar_ids_set = set(scalar_ids)
    err_ids = scalar_ids_set.intersection(out_ids if len(out_ids) else inplace_ids)
    assert (
        len(err_ids) == 0
    ), "Input(s) at {} cannot be both scalar and tensor for {}.".format(err_ids, fname)

    out_ids = ", ".join([str(o) for o in out_ids])
    inplace_ids = ", ".join([str(i) for i in inplace_ids])
    scalar_ids = ", ".join([str(s) for s in scalar_ids])

    if fname.startswith("bitwise_"):
        custom_handler = _CUSTOM_HANDLER.format(body=bitwise_ops_alt_guid(guid))
    elif fname == "tril_indices" or fname == "triu_indices":
        custom_handler = _CUSTOM_HANDLER.format(body=tril_triu_without_tensor())
    else:
        custom_handler = ""

    ctor_extra_calls = []
    layouts = ctxop.get_layouts()
    if len(layouts):
        assert len(layouts) == 2, "Define both input and output layouts."
        assert len(layouts[0]), "Input layouts size should be atleast 1."
        assert len(layouts[1]), "Output layouts size should be atleast 1."
        in_layouts = ", ".join(["LayoutFormat::" + l for l in layouts[0]])
        out_layouts = ", ".join(["LayoutFormat::" + l for l in layouts[1]])
        ctor_extra_calls.append(
            "SetLayouts({{{}}}, {{{}}});".format(in_layouts, out_layouts)
        )
    synapse_layouts = ctxop.get_synapse_layouts()
    if len(synapse_layouts):
        assert len(synapse_layouts) == 2, "Define both input and output layouts."
        assert len(synapse_layouts[0]), "Input layouts size should be atleast 1."
        assert len(synapse_layouts[1]), "Output layouts size should be atleast 1."
        in_layouts = ", ".join(
            [
                "synapse_helpers::layouts::SynapseLayoutFormat::" + l
                for l in synapse_layouts[0]
            ]
        )
        out_layouts = ", ".join(
            [
                "synapse_helpers::layouts::SynapseLayoutFormat::" + l
                for l in synapse_layouts[1]
            ]
        )
        ctor_extra_calls.append(
            "SetSynapseLayouts({{{}}}, {{{}}});".format(in_layouts, out_layouts)
        )

    if is_out_fn(fname) and num_out_tensors > 1:
        ctor_extra_calls.append("SetNumOutTensors({});".format(num_out_tensors))

    if output_shape_fn:
        ctor_extra_calls.append("SetComputeOutputShapes({});".format(output_shape_fn))

    if custom_fill_params:
        ctor_extra_calls.append("SetFillParams({});".format(custom_fill_params))

    if tpc_param:
        assert (
            custom_fill_params is None
        ), "Should not define both `tpc_param` and `custom_fill_params` for {}".format(
            fname
        )
        params = []
        for param_data in tpc_param["params"]:
            if len(param_data):
                idx, cast_type = param_data
                params.append("stack[{}].toScalar().to<{}>()".format(idx, cast_type))
            else:
                params.append("{}")
        fill_params = _FILL_PARAMS.format(
            ns_param=tpc_param["name"], args=", ".join(params)
        )
        ctor_extra_calls.append("SetFillParams({});".format(fill_params))

    if promote_type:
        ctor_extra_calls.append("EnableTypePromotion();")
    elif promote_int_to_float:
        ctor_extra_calls.append("PromoteIntToFloat();")

    if ctxop.get_op_template() == "reduction":
        ctor_extra_calls.append(
            "SetReductionVarsIndices({});".format(
                ", ".join(extract_reduction_vars_indices(param_vars))
            )
        )

    return _OPCLASS_HEADER.format(
        op_backend_class=op_backend_class,
        cname=cname,
        guid=guid,
        out_ids=out_ids,
        inplace_ids=inplace_ids,
        scalar_ids=scalar_ids,
        is_out_fn=str(is_out_fn(fname)).lower(),
        ctor_extra_calls="".join(["\n" + " " * 8 + c for c in ctor_extra_calls]),
        custom_handler=custom_handler,
    )


class TensorFetcher(object):
    def __init__(self, var_name):
        self.var_name = var_name
        self.tvar_name = "{}_tensors".format(self.var_name)
        self.optvar_name = "{}_opt".format(var_name)
        self.toptvar_name = "{}_tensors".format(self.optvar_name)
        self.tensors = []
        self.opt_tensors = []
        self.writeable = []

    def add(self, name, writeable):
        if writeable:
            self.writeable.append(len(self.tensors))
        self.tensors.append(name)
        return "{}[{}]".format(self.var_name, len(self.tensors) - 1)

    def add_opt(self, name):
        self.opt_tensors.append(name)
        return "{}[{}]".format(self.optvar_name, len(self.opt_tensors) - 1)

    def get_tensors(self):
        return self.tensors

    def get_opt_tensors(self):
        return self.opt_tensors

    def generate_meta_fetches(self):
        code = ""
        code += "  std::vector<at::Tensor> {} = {{{}}};\n".format(
            self.tvar_name, ", ".join(self.tensors)
        )
        code += ("  auto {} = habana::GetMetaTensorList({});\n").format(
            self.var_name, self.tvar_name
        )
        # Handles conversion of c10::optional<at::Tensor> if exists
        if self.opt_tensors:
            code += "  std::vector<c10::optional<at::Tensor>> {} = {{{}}};\n".format(
                self.toptvar_name, ", ".join(self.opt_tensors)
            )
            code += ("  auto {} = habana::GetMetaOptTensorList({});\n").format(
                self.optvar_name, self.toptvar_name
            )
        return code


def extract_reduction_vars_indices(param_vars):
    reduction_vars_indices = ["c10::nullopt", "c10::nullopt", "c10::nullopt"]
    for i, var in enumerate(param_vars):
        i = str(i)
        if var == "dim":
            reduction_vars_indices[0] = i
        elif var == "keepdim":
            reduction_vars_indices[1] = i
        elif var == "dtype":
            reduction_vars_indices[2] = i

    return reduction_vars_indices


def generate_code(ctx, tree, rwxtree, fname, aten_sig, sig, rwsig, params):
    op_frontend = "{} {{\n".format(sig)
    op_frontend += generate_entry_debug_code(tree, fname, params)

    tfetcher = TensorFetcher("metatens")
    rtype = get_return_type_str(rwxtree, rwsig)
    param_vars = []
    meta_param_vars = []
    call_args = []
    for p in params:
        ptype = param_type(p)
        cptype = type_core(ptype)
        pname = param_name(p)

        param_vars.append(pname)

        if cptype == "TensorList":
            xname = "l_{}".format(pname)
            meta_param_vars.append(xname)
        elif cptype == "TensorOptions":
            gcode, xname = rewrite_tensor_options(fname, pname)
            meta_param_vars.append(xname)
        elif cptype == "c10::optional":
            wrapped_type = type_core(get_template_type_list(ptype)[0])
            if wrapped_type == "Tensor":
                xname = tfetcher.add_opt(pname)
                meta_param_vars.append(xname)
            else:
                meta_param_vars.append(pname)
        elif cptype != "Tensor":
            meta_param_vars.append(pname)
        elif type_is_const(ptype):
            xname = tfetcher.add(pname, False)
            meta_param_vars.append(xname)
        else:
            assert cptype == "Tensor"
            xname = tfetcher.add(pname, True)
            meta_param_vars.append(xname)
            call_args.append(pname)

        if rtype == "void":
            if cptype == "TensorList" or cptype == "Tensor":
                call_args.append(pname)

    opname = get_aten_opname(aten_sig)
    ctxop = ctx.get_op(opname)
    fn = ctx.get_function(fname)

    lazyop_call_args = ""
    if len(call_args):
        lazyop_call_args = "{}".format(", ".join(call_args))
        if type_core(tree.children[0]) == "::std::tuple":
            lazyop_call_args = "{}({})".format(rtype, lazyop_call_args)

    op_frontend += lazyop(
        ctxop,
        tfetcher,
        fn,
        fname,
        aten_sig,
        rtype,
        param_vars,
        meta_param_vars,
        lazyop_call_args,
    )

    op_backend_class = opname.replace(".", "_")
    op_backend = get_op_backend_class_impl(
        ctxop, fname, op_backend_class, len(call_args), param_vars
    )

    return op_frontend, op_backend, op_backend_class, ctxop


def get_aten_opname(aten_sig):
    return aten_sig.split("(")[0].split("::")[1]


def get_hpu_wrapper(fndef, ctx):
    tree = _PARSER.parse(fndef.cpp_sig)
    xtree = _XPARSER.parse(fndef.cpp_sig)
    mapsig = create_map_sig(xtree, fndef.cpp_sig)
    rwsig = rewrite_signature(fndef.cpp_sig, _TYPE_NSMAP)
    rwxtree = _XPARSER.parse(rwsig)
    params = get_parameters(tree)
    aten_sig = fndef.aten_sig

    def gen_fnname(x):
        return "HpuOp::{}".format(x)

    sig, fname, xfname = get_function_signature(rwxtree, rwsig, gen_fnname)
    if get_aten_opname(aten_sig) in ctx.op_data:
        assert fndef.dispatch, "{} has dispatch=False".format(get_aten_opname(aten_sig))
        op_frontend, op_backend, cname, ctxop = generate_code(
            ctx, tree, rwxtree, fname, aten_sig, sig, rwsig, params
        )
        if ctxop.force_default() is not None:
            default = ctxop.force_default()
            assert (
                default != fndef.default
            ), "No need to force it to False for {}".format(get_aten_opname(aten_sig))
        else:
            default = fndef.default

        assert not default, "{} has default={}".format(
            get_aten_opname(aten_sig), default
        )

        return OpGen(
            tree=tree,
            xtree=xtree,
            rwxtree=rwxtree,
            func=fname,
            xfunc=xfname,
            op_frontend=op_frontend,
            op_backend=op_backend,
            cname=cname,
            sig=fndef.cpp_sig,
            rwsig=rwsig,
            cppsig=sig,
            mapsig=mapsig,
            funsig=create_stdfunc_sig(rwxtree, rwsig),
            aten_sig=aten_sig,
            dispatch=fndef.dispatch,
            default=fndef.default,
            ctxop=ctxop,
        )


def is_tensor_api(fndef):
    fndef = fndef.replace("at::", "")
    fndef = fndef.replace("c10::Device", "Device")
    m = re.search(r"\bTensor\b", fndef)
    return m is not None, fndef


def create_funcdef(fndef, jdata):
    fields = json.loads(jdata)
    return FuncDef(
        cpp_sig=fndef,
        aten_sig=fields["schema"],
        dispatch=fields.get("dispatch", "False") == "True",
        default=fields.get("default", "False") == "True",
    )


def extract_functions(path):
    functions = []
    errors = []

    for line in open(path, "r"):
        m = re.match(r"\s*([^\s].*); //\s+(.*)", line)
        if not m:
            continue
        fndef = m.group(1)
        try:
            _XPARSER.parse(fndef)
            functions.append(create_funcdef(fndef, m.group(2)))
        except Exception as e:
            if is_tensor_api(fndef)[0]:
                errors.append((fndef, str(e)))
                print('Error parsing "{}": {}'.format(fndef, e), file=sys.stderr)
    return functions, errors


def get_mapsig_key(mapsig):
    # PyTorch generates std::tuple<> without space among the tuple types,
    # which would require special understanding in the string rewriter.
    # Since we are using this as simple key, we can just string the spaces.
    return mapsig.replace(" ", "")


def parse_local_overrides(path):
    functions = []
    fndef = None
    for line in open(path, "r"):
        line = line.strip()
        if not fndef:
            m = re.match(r"static\s+(.*);", line)
            if m:
                functions.append(m.group(1))
                continue
            m = re.match(r"static\s+(.*)", line)
            if m:
                fndef = m.group(1)
        else:
            fndef = "{} {}".format(fndef, line)
            if fndef.endswith(";"):
                functions.append(fndef[:-1])
                fndef = None
    assert fndef is None

    overrides = {}
    for fndef in functions:
        # Discard static hpu_wrap functions which are not ATEN.
        is_tensor, fndef = is_tensor_api(fndef)
        if is_tensor:
            xtree = _XPARSER.parse(fndef)
            mapsig_key = get_mapsig_key(create_map_sig(xtree, fndef))
            overrides[mapsig_key] = fndef
    return overrides


def generate_impl(aten_sig, overload, override_fn):
    code = '  m.impl("{}", static_cast<{}>(&{}));\n'.format(
        aten_sig.split("(")[0].split("::")[1], overload, override_fn
    )
    return code


def generate_dtype_macro(ctxop, opname):
    def generate_line(dtypes, suffix):
        dtypes_set = set(dtypes)
        assert len(dtypes) == len(
            dtypes_set
        ), "Found same dtype defined more than once for {}".format(suffix)

        assert not any(x in dtypes_set for x in ["Double", "Long", "Bool"]), (
            "Double, Long and Bool are not natively supported, they are "
            "treated as Float, Int and Char respectively. For instance if "
            "Float is a supported dtype, Double is added as a supported dtype "
            "in the script."
        )

        if "Float" in dtypes:
            dtypes.append("Double")
        if "Int" in dtypes:
            dtypes.append("Long")
        if "Char" in dtypes:
            dtypes.append("Bool")

        return "HPU_SUPPORTED_DTYPES({}, ({{{}}}))".format(
            suffix.replace(".", "_"),
            ", ".join(["c10::ScalarType::" + d for d in dtypes]),
        )

    dtypes = ctxop.get_dtypes()
    if isinstance(dtypes, list):
        return generate_line(dtypes, opname)
    elif isinstance(dtypes, dict):
        lines = []
        for k, v in dtypes.items():
            lines.append(generate_line(v, "{}_{}".format(opname, k)))
        return "\n".join(lines)
    else:
        assert dtypes is None, "dtypes support list/dict only."


def generate_all(fgens):
    aten_code = "TORCH_LIBRARY_IMPL(aten, HPU, m) {\n"
    autogradhpu_code = None
    overridden = set()

    kr_code = "static const auto& kr = KernelRegistry()\n"
    krlines = []

    dtype_defs = ""
    op_frontend_hfunctions = ""
    op_frontend_functions = ""
    op_backend = ""

    custom_schema_def = []
    custom_schema_regs = ""

    for fgen in fgens:
        # torch registrations
        mapsig_key = get_mapsig_key(fgen.mapsig)
        override_fn = "HpuOp::{}".format(fgen.func)
        overridden.add(mapsig_key)
        pos = fgen.funsig.find("(")
        overload = fgen.funsig[:pos] + " (*)" + fgen.funsig[pos:]
        impl = generate_impl(fgen.aten_sig, overload, override_fn)
        if fgen.mapsig in _FN_AUTOGRAD_HPU:
            autogradhpu_code += impl
        else:
            aten_code += impl

        # KernelRegistry registrations
        op = fgen.aten_sig.split("(")[0].split("::")[1]
        ns = "hpu" if fgen.ctxop.custom_schema() else "aten"
        krlines.append(
            '  .add("{}::{}", [](const int device_id, c10::ScalarType node_type) {{\n'
            "      return std::make_shared<{}>(device_id, node_type);\n"
            "  }})".format(ns, op, fgen.cname)
        )

        # Dtype definitions
        if fgen.ctxop.get_dtypes():
            dtype_defs += "{}\n".format(
                generate_dtype_macro(fgen.ctxop, get_aten_opname(fgen.aten_sig))
            )

        if fgen.op_frontend:
            # Lazy function declarations
            op_frontend_hfunctions += "  static {};\n".format(fgen.rwsig)

            # Lazy functions
            op_frontend_functions += "{}\n\n".format(fgen.op_frontend)

        # Lowering Kernel code
        if fgen.op_backend:
            op_backend += "{}\n".format(fgen.op_backend)

        # Custom schema definitions
        if fgen.ctxop.custom_schema():
            custom_schema_def.append(
                '  m.def("{}");'.format(fgen.ctxop.custom_schema())
            )

    torch_regs = aten_code + "\n}\n"

    if autogradhpu_code:
        code += (
            "TORCH_LIBRARY_IMPL(aten, AutogradHPU, m) {\n" + autogradhpu_code + "\n}"
        )

    kr_regs = kr_code + "\n".join(krlines) + ";"

    if len(custom_schema_def):
        custom_schema_regs = (
            "TORCH_LIBRARY_FRAGMENT(hpu, m) {\n" + "\n".join(custom_schema_def) + "\n}"
        )
    return (
        dtype_defs,
        op_frontend_hfunctions,
        op_frontend_functions,
        torch_regs,
        overridden,
        op_backend,
        kr_regs,
        custom_schema_regs,
    )


def generate_op_backend_hclasses(fgens):
    code = ""
    classes = set()
    for fgen in fgens:
        fclass = fgen.ctxop.get_op_backend_class()
        if fclass.endswith("Template"):
            continue
        if fclass != "OpBackend" and fclass not in classes:
            code += "HPU_OP_BACKEND({})\n".format(fclass)
            classes.add(fclass)
    return code


def generate_op_frontend_hclasses(fgens):
    code = ""
    classes = set()
    for fgen in fgens:
        fclass = fgen.ctxop.get_op_frontend_class()
        if fclass in ["LazyOp", "LazyOpWithTypePromotion", "PromoteIntToFloat"]:
            continue
        if fclass.endswith("Template"):
            continue
        if fclass in classes:
            continue
        code += "HPU_OP_FRONTEND({})\n".format(fclass)
        classes.add(fclass)
    return code


def generate_fill_params_hdecls(fgens):
    code = ""
    fns = set()
    for fgen in fgens:
        fn = fgen.ctxop.get_custom_fill_params()
        if fn and fn not in fns:
            code += "FILL_PARAMS_DECL({})\n".format(fn)
            fns.add(fn)
    return code


def generate_outshapes_hdecls(fgens):
    code = ""
    fns = set()
    for fgen in fgens:
        fn = fgen.ctxop.get_custom_output_shape()
        if fn and fn not in fns:
            code += "OUTSHAPE_DECL({})\n".format(fn)
            fns.add(fn)
    return code


def gen_output_file(args, name):
    if not args.output_folder:
        return sys.stdout
    return open(os.path.join(args.output_folder, name), "w")


def gen_h_output_file(args):
    return gen_output_file(args, "hpu_op.h")


def gen_cpp_output_file(args):
    return gen_output_file(args, "hpu_op.cpp")


def generate(args):
    fndefs, errors = extract_functions(args.typedef)
    assert len(errors) == 0

    fgens = []
    ctx = Context(args.functions, args.yaml)
    for ts in fndefs:
        try:
            fgen = get_hpu_wrapper(ts, ctx)
            if fgen:
                fgens.append(fgen)
        except Exception as e:
            print("Failed to generate op {}: {}".format(ts, e), file=sys.stderr)
            errors.append(e)
    print("Generated {} ops from {}".format(len(fgens), args.yaml), file=sys.stdout)
    assert len(errors) == 0, "Found {} errors: {}".format(len(errors), errors)

    if len(ctx.op_data) != len(fgens):
        fgen_data = [get_aten_opname(x.aten_sig) for x in fgens]
        for op in ctx.op_data.keys():
            assert op in fgen_data, "Cannot generate {}".format(op)

    op_backend_classes = generate_op_backend_hclasses(fgens)
    op_frontend_classes = generate_op_frontend_hclasses(fgens)
    fill_params_decls = generate_fill_params_hdecls(fgens)
    outshapes_decls = generate_outshapes_hdecls(fgens)

    (
        dtype_defs,
        hfunctions,
        functions,
        torch_regs,
        overridden,
        op_backend,
        kr_regs,
        custom_schema_regs,
    ) = generate_all(fgens)

    # Create output files ...
    print(
        _H_HEADER.format(
            gen=os.path.basename(sys.argv[0]),
            hfuncs=hfunctions,
            op_backend_classes=op_backend_classes,
            op_frontend_classes=op_frontend_classes,
            fill_params_decls=fill_params_decls,
            outshapes_decls=outshapes_decls,
        ),
        file=gen_h_output_file(args),
    )
    print(
        _CPP_HEADER.format(
            gen=os.path.basename(sys.argv[0]),
            dtype_defs=dtype_defs,
            funcs=functions,
            op_backend=op_backend,
            kr_regs=kr_regs,
            torch_regs=torch_regs,
            custom_schema_regs=custom_schema_regs,
        ),
        file=gen_cpp_output_file(args),
    )


if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("--output_folder", type=str)
    arg_parser.add_argument(
        "--yaml",
        default=".",
        help="Where yaml file is",
    )
    arg_parser.add_argument(
        "typedef",
        type=str,
        metavar="TYPE_DEFAULT_FILE",
        help="The path to the TypeDefault.h file",
    )
    arg_parser.add_argument(
        "functions",
        type=str,
        metavar="FUNCTIONS_FILE",
        help="The path to the Functions.h file",
    )
    args, files = arg_parser.parse_known_args()
    generate(args)
