from __future__ import print_function

import argparse
import collections.abc
import lark
import json
import os
import re
import sys
import yaml
from yaml import Loader


def namedtuple_with_defaults(typename, field_names, default_values=()):
    ntuple = collections.namedtuple(typename, field_names)
    ntuple.__new__.__defaults__ = (None,) * len(ntuple._fields)
    if isinstance(default_values, collections.abc.Mapping):
        prototype = ntuple(**default_values)
    else:
        prototype = ntuple(*default_values)
    ntuple.__new__.__defaults__ = tuple(prototype)
    return ntuple


FuncDef = namedtuple_with_defaults("FuncDef", "cpp_sig, aten_sig, dispatch, default")

OpGen = namedtuple_with_defaults(
    "OpGen",
    "tree, xtree, rwxtree, func, xfunc, lazy_code, hpuop_code, dtype_def, cname, sig, rwsig, cppsig, funsig, mapsig, aten_sig, dispatch, default",
)

_GRAMMAR = r"""
    start: type fnname "(" params ")"
    type: CONST? core_type refspec?
    fnname: CNAME
    refspec: REF
           | PTR
    core_type: template
        | TNAME
    template: TNAME "<" typelist ">"
    typelist: type
            | type "," typelist
    REF: "&"
    PTR: "*"
    CONST: "const"
    TNAME: /[a-zA-Z0-9_:]+/
    HEXNUMBER: /0x[0-9a-fA-F]+/
    params: param
          | param "," params
    param: type param_name param_defval?
    param_name: CNAME

    param_defval: "=" init_value
    init_value: "true"
              | "false"
              | "{}"
              | NUMBER
              | SIGNED_NUMBER
              | HEXNUMBER
              | ESCAPED_STRING

    %import common.CNAME -> CNAME
    %import common.NUMBER -> NUMBER
    %import common.SIGNED_NUMBER -> SIGNED_NUMBER
    %import common.ESCAPED_STRING -> ESCAPED_STRING
    %import common.WS
    %ignore WS
    """

_PARSER = lark.Lark(_GRAMMAR, parser="lalr", propagate_positions=True)

_XPARSER = lark.Lark(
    _GRAMMAR, parser="lalr", propagate_positions=True, keep_all_tokens=True
)

_FN_AUTOGRAD_HPU = set([])

_TYPE_NSMAP = {
    "Tensor": "at::Tensor",
    "TensorList": "at::TensorList",
    "Scalar": "at::Scalar",
    "Storage": "at::Storage",
    "IntList": "at::IntList",
    "IntArrayRef": "at::IntArrayRef",
    "ArrayRef": "at::ArrayRef",
    "Generator": "at::Generator",
    "Layout": "at::Layout",
    "ScalarType": "at::ScalarType",
    "TensorOptions": "at::TensorOptions",
    "SparseTensorRef": "at::SparseTensorRef",
    "Device": "c10::Device",
    "optional": "c10::optional",
    "MemoryFormat": "at::MemoryFormat",
    "QScheme": "at::QScheme",
    "ConstQuantizerPtr": "at::ConstQuantizerPtr",
    "Dimname": "at::Dimname",  # namedtensor-only
    "DimnameList": "at::DimnameList",  # namedtensor-only
}

_H_HEADER = """// Autogenerated file by {gen}. Do not edit directly!

#include <ATen/Tensor.h>
#include <c10/core/Stream.h>

using c10::Stream;

namespace habana {{

class HpuOp{{
 public:
{hfuncs}
}};

}}  // namespace habana
"""

_CPP_HEADER = """// Autogenerated file by {gen}. Do not edit directly!
#include "hpu_op.h"

#include <ATen/Context.h>
#include <ATen/CPUGeneratorImpl.h>
#include <torch/library.h>

#include "habana_helpers/tensor_utils.h"
#include "habana_kernels/aten_hpu_type_default.h"
#include "habana_kernels/hpu_op_helper.h"
#include "habana_kernels/lazy_kernels.h"
#include "habana_kernels/wrap_kernels_declarations.h" // Temporary: Remove when lazy=2 is default

using habana_helpers::name_suffix_from_type;
using habana_lazy::LazyOp;
using synapse_helpers::graph;
using torch::jit::Stack;

namespace habana {{

{dtype_defs}

{funcs}

{hpuops}

{hpuop_regs}

{regs}
}}  // namespace habana
"""

_OPCLASS_HEADER = """struct {cname} : public HabanaOperatorHelper {{
  {cname}(int device_id, c10::ScalarType scalarType) :
        HabanaOperatorHelper(device_id, \"{guid}_\" + name_suffix_from_type(scalarType)) {{}}

  void AllocateAndAddSynapseNode(graph& graph, Stack& stack, bool is_output_persistent = false) override {{
    static_cast<void>(is_output_persistent);

    {node_code}
  }}
}};
"""


class Op(object):
    def __init__(self, op):
        self.op = op

    def get_guid(self):
        return self.op["guid"]

    def get_dtypes(self):
        return self.op.get("dtypes", None)

    def get_tpc_param(self):
        return self.op.get("tpc_param", None)

    def get_inplace_ids(self):
        return self.op.get("inplace_ids", None)

    def get_out_ids(self):
        return self.op.get("out_ids", None)

    def is_legacy_reqd(self):
        return self.op.get("legacy_eager", False)

    def use_meta(self):
        return self.op.get("use_meta", False)


class Context(object):
    def __init__(self, functions, yamlfile):
        with open(functions, "r") as ff:
            self.functions_data = ff.read()

        with open(yamlfile, "r") as ff:
            self.op_data = yaml.load(ff.read(), Loader=Loader)

    def get_function(self, name):
        if self.functions_data.find(" {}(".format(name)) >= 0:
            return "at::{}".format(name + "f" if is_out_fn(name) else name)

    def get_op(self, opname):
        return Op(self.op_data[opname])


class StringEmit(object):
    def __init__(self, sref):
        self.sref = sref
        self.sval = ""
        self.pos = -1

    def __repr__(self):
        return self.sval

    def advance(self, t):
        start = t.column - 1
        end = t.end_column - 1
        pos = self.pos if self.pos >= 0 else start
        if start > pos:
            self.sval += self.sref[pos:start]
        self.sval += t.value
        self.pos = end

    def skip(self, t):
        self.pos = last_match(t) if self.pos >= 0 else -1

    def append(self, s):
        self.sval += s
        self.pos = -1


def first_match(t):
    if isinstance(t, lark.lexer.Token):
        return t.column - 1
    assert isinstance(t, lark.tree.Tree)
    return first_match(t.children[0])


def last_match(t):
    if isinstance(t, lark.lexer.Token):
        return t.end_column - 1
    assert isinstance(t, lark.tree.Tree)
    return last_match(t.children[-1])


def for_every_token(t, fn):
    if isinstance(t, lark.lexer.Token):
        fn(t)
    else:
        assert isinstance(t, lark.tree.Tree)
        for c in t.children:
            for_every_token(c, fn)


def emit_string(t, emit, emit_fn):
    status = emit_fn(t)
    if status > 0:

        def do_emit(tok):
            emit.advance(tok)

        for_every_token(t, do_emit)
    elif status == 0:
        if isinstance(t, lark.lexer.Token):
            emit.advance(t)
        else:
            assert isinstance(t, lark.tree.Tree)
            for c in t.children:
                emit_string(c, emit, emit_fn)
    else:
        emit.skip(t)


def typed_child(t, n, ttype):
    assert isinstance(t, lark.tree.Tree)
    assert n < len(t.children)
    c = t.children[n]
    assert isinstance(c, lark.tree.Tree)
    assert c.data == ttype, t.pretty()
    return c


def rewrite_sig(tree, orig_sig, emit_fn=lambda x: 0):
    emit = StringEmit(orig_sig)
    emit_string(tree, emit, emit_fn)
    return str(emit)


def rewrite_signature(sig, tmap):
    def rewrite(t):
        if t.type == "TNAME":
            new_type = tmap.get(t.value, None)
            if new_type is not None:
                t.value = new_type

    def emit_fn(t):
        if isinstance(t, lark.lexer.Token):
            return 0
        return -1 if t.data == "param_defval" else 0

    xtree = _XPARSER.parse(sig)
    for_every_token(xtree, rewrite)
    return rewrite_sig(xtree, sig, emit_fn=emit_fn)


def create_stdfunc_sig(tree, orig_sig):
    def emit_fn(t):
        if isinstance(t, lark.lexer.Token):
            return 0
        return -1 if t.data == "param_name" else 0

    emit = StringEmit(orig_sig)
    # Emit full function return type.
    emit_string(typed_child(tree, 0, "type"), emit, emit_fn)
    emit.append("(")
    # Emit parameter list w/out parameter names.
    emit_string(typed_child(tree, 3, "params"), emit, emit_fn)
    emit.append(")")
    return str(emit)


def create_map_sig(tree, orig_sig):
    def emit_fn(t):
        if isinstance(t, lark.lexer.Token):
            return -1 if t.type in ["CONST", "REF", "PTR"] else 0
        return -1 if t.data in ["param_name", "param_defval"] else 0

    emit = StringEmit(orig_sig)
    # Emit full function return type.
    emit_string(typed_child(tree, 1, "fnname"), emit, emit_fn)
    emit.append("(")
    # Emit parameter list w/out parameter names.
    emit_string(typed_child(tree, 3, "params"), emit, emit_fn)
    emit.append(") -> ")
    emit_string(typed_child(tree, 0, "type"), emit, emit_fn)
    return str(emit)


def type_core(t):
    assert isinstance(t, lark.tree.Tree)
    for c in t.children:
        if isinstance(c, lark.tree.Tree) and c.data == "core_type":
            c = c.children[0]
            if isinstance(c, lark.lexer.Token):
                return c.value
            assert isinstance(c, lark.tree.Tree) and c.data == "template"
            return c.children[0].value
    raise RuntimeError("Not a type tree: {}".format(t))


def type_is_const(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[0]
    return isinstance(c, lark.lexer.Token) and c.value == "const"


def type_is_refptr(t, kind):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[-1]
    if not isinstance(c, lark.tree.Tree) or c.data != "refspec":
        return False
    c = c.children[0]
    return isinstance(c, lark.lexer.Token) and c.value == kind


def extract_list(t, l):
    assert isinstance(t, lark.tree.Tree)
    l.append(t.children[0])
    if len(t.children) == 2:
        c = t.children[1]
        if isinstance(c, lark.tree.Tree) and c.data == t.data:
            extract_list(c, l)
    return l


def get_template_type_list(t):
    assert isinstance(t, lark.tree.Tree)
    # Skipping type qualifiers if exists.
    # E.g. const c10::optional<T>
    for c in t.children:
        if isinstance(c, lark.tree.Tree) and c.data == "core_type":
            break
    c = c.children[0]
    assert isinstance(c, lark.tree.Tree) and c.data == "template"
    types = []
    return extract_list(c.children[1], types)


def get_function_name(t):
    assert isinstance(t, lark.tree.Tree)
    fname = t.children[1]
    assert isinstance(fname, lark.tree.Tree)
    assert fname.data == "fnname"
    return fname.children[0].value


def is_out_fn(fname):
    return fname.endswith("_out")


def get_function_signature(t, orig_sig, namefn):
    emit = StringEmit(orig_sig)
    # Emit full function return type.
    emit_string(typed_child(t, 0, "type"), emit, lambda t: 0)
    fnname = typed_child(t, 1, "fnname").children[0]
    xfname = namefn(fnname.value)
    emit.append(" {}(".format(xfname))
    # Emit parameter list w/out parameter names.
    emit_string(typed_child(t, 3, "params"), emit, lambda t: 0)
    emit.append(")")
    return str(emit), fnname.value, xfname


def get_parameters(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[2]
    assert isinstance(c, lark.tree.Tree)
    assert c.data == "params"
    params = []
    extract_list(c, params)
    return params


def param_name(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[1]
    assert isinstance(c, lark.tree.Tree)
    assert c.data == "param_name"
    token = c.children[0]
    assert isinstance(token, lark.lexer.Token)
    return token.value


def param_type(t):
    assert isinstance(t, lark.tree.Tree)
    c = t.children[0]
    assert isinstance(c, lark.tree.Tree)
    return c


def get_return_type_str(t, orig_sig):
    assert isinstance(t, lark.tree.Tree)
    fname = t.children[1]
    assert isinstance(fname, lark.tree.Tree)
    assert fname.data == "fnname"
    token = fname.children[0]
    assert isinstance(token, lark.lexer.Token)
    return orig_sig[0 : token.column - 2]


def generate_entry_debug_code(t, fname, params):
    # Emits debug code for a given intercepted function.
    code = "  PT_LAZY_TRACE;\n"
    code += '  PT_LAZY_DEBUG("LazyOp {} :"'.format(fname)
    for p in params:
        ptype = param_type(p)
        cptype = type_core(ptype)
        pname = param_name(p)
        if cptype == "Tensor":
            code += ', " {}=", {}.toString()'.format(pname, pname)
    code += ");\n\n"
    return code


def lazyop(
    ctxop, tfetcher, fn, fname, aten_sig, rtype, param_vars, meta_vars, ce_param_vars
):
    symbol = re.split(r"\(|\.", aten_sig)[0]
    code = ""

    if ctxop.get_dtypes():
        input_tensors = (
            tfetcher.get_tensors()[:-1] if is_out_fn(fname) else tfetcher.get_tensors()
        )
        for t in input_tensors:
            code += "  FALLBACK_IF_UNSUPPORTED_DTYPE({}, {}, {})\n".format(
                t, fname, ", ".join(param_vars)
            )
        code += "\n"

    if ctxop.is_legacy_reqd():
        code += (
            '  if (!std::getenv("PT_HPU_LAZY_MODE")) return hpu_wrap::{}({});\n'.format(
                fname, ", ".join(param_vars)
            )
        )
        code += "\n"

    if ctxop.use_meta():
        code += tfetcher.generate_meta_fetches()
        code += "  at::TensorList metavar = {}({});\n".format(fn, ", ".join(meta_vars))
        code += '  LazyOp<{}> hpu_op{{"{}", {{{}}}, metavar}};\n'.format(
            rtype, symbol, ", ".join(param_vars)
        )
    else:
        code += '  LazyOp<{}> hpu_op{{"{}", {{{}}}}};\n'.format(
            rtype, symbol, ", ".join(param_vars)
        )
    if len(ce_param_vars):
        code += "  return hpu_op.call({})".format(", ".join(ce_param_vars))
    else:
        code += "  return hpu_op.call()"
    return code + ";\n}"


def bitwise_ops_alt_guid(guid):
    logical_guid = guid.replace("bitwise_", "")
    code = (
        "if (stack[0].toTensor().scalar_type() == at::kBool) {{\n"
        '      SetGuid("{}_i8");\n'
        "    }}\n    ".format(logical_guid)
    )

    return code


def get_hpuop_class_impl(ctxop, fname, cname):
    guid = ctxop.get_guid()
    out_ids = ctxop.get_out_ids()
    inplace_ids = ctxop.get_inplace_ids()

    assert (
        (out_ids is None) ^ (inplace_ids is None) ^ is_out_fn(fname)
    ), "Either out_ids or inplace_ids should be defined for {}".format(fname)

    code = ""
    if fname.startswith("bitwise_"):
        code += bitwise_ops_alt_guid(guid)

    if inplace_ids:
        # TODO: What about multiple inplace tensors?
        assert len(inplace_ids) == 1

        code += (
            "p_context_->syn_outputs_.emplace_back(\n"
            "        habana_helpers::duplicate_tensor_in_memory_section(p_context_->syn_inputs_[{id}]));\n"
            "    p_context_->pt_outputs_.emplace_back(stack[{id}].toTensor());\n"
        ).format(id=inplace_ids[0])
    elif is_out_fn(fname):
        code += "p_context_->pt_outputs_.emplace_back(stack.back().toTensor());\n"
        code += "    p_context_->syn_outputs_.emplace_back(habana_helpers::duplicate_tensor_in_memory_section(p_context_->syn_inputs_.back()));\n"
        code += "    p_context_->syn_inputs_.pop_back();\n"
    else:
        code = "auto output = habana_helpers::createPTTensor(stack.at({id}).toTensor(), is_output_persistent);\n".format(
            id=out_ids[0]
        )

        code += "    AllocateSynapseOutput(graph, output, is_output_persistent);\n"

    tpc_param = ctxop.get_tpc_param()
    if tpc_param:
        code += "\n    {}::Params param {{".format(tpc_param["name"])
        params = []
        for param_data in tpc_param["params"]:
            if len(param_data):
                idx, cast_type = param_data
                params.append("stack[{}].toScalar().to<{}>()".format(idx, cast_type))
            else:
                params.append("{}")
        code += ", ".join(params) + "};\n"
        code += "    AddNodeToSynapseGraph(graph, &param, sizeof(param));"
    else:
        code += "    AddNodeToSynapseGraph(graph, nullptr, 0);"

    c_code = _OPCLASS_HEADER.format(cname=cname, guid=guid, node_code=code)

    return c_code


class TensorFetcher(object):
    def __init__(self, var_name):
        self.var_name = var_name
        self.tvar_name = "{}_tensors".format(self.var_name)
        self.optvar_name = "{}_opt".format(var_name)
        self.toptvar_name = "{}_tensors".format(self.optvar_name)
        self.tensors = []
        self.opt_tensors = []
        self.writeable = []

    def add(self, name, writeable):
        if writeable:
            self.writeable.append(len(self.tensors))
        self.tensors.append(name)
        return "{}[{}]".format(self.var_name, len(self.tensors) - 1)

    def add_opt(self, name):
        self.opt_tensors.append(name)
        return "{}[{}]".format(self.optvar_name, len(self.opt_tensors) - 1)

    def get_tensors(self):
        return self.tensors

    def get_opt_tensors(self):
        return self.opt_tensors

    def generate_meta_fetches(self):
        code = ""
        code += "  std::vector<at::Tensor> {} = {{{}}};\n".format(
            self.tvar_name, ", ".join(self.tensors)
        )
        code += ("  auto {} = habana::GetMetaTensorList({});\n").format(
            self.var_name, self.tvar_name
        )
        # Handles conversion of c10::optional<at::Tensor> if exists
        if self.opt_tensors:
            code += "  std::vector<c10::optional<at::Tensor>> {} = {{{}}};\n".format(
                self.toptvar_name, ", ".join(self.opt_tensors)
            )
            code += ("  auto {} = habana::GetMetaOptTensorList({});\n").format(
                self.optvar_name, self.toptvar_name
            )
        return code


def generate_code(ctx, tree, rwxtree, fname, aten_sig, sig, rwsig, params):
    lazy_code = "{} {{\n".format(sig)
    lazy_code += generate_entry_debug_code(tree, fname, params)

    tfetcher = TensorFetcher("metatens")
    param_vars = []
    meta_param_vars = []
    ce_param_vars = []
    for p in params:
        ptype = param_type(p)
        cptype = type_core(ptype)
        pname = param_name(p)

        param_vars.append(pname)

        if cptype == "TensorList":
            xname = "l_{}".format(pname)
            code += ("  auto {} = habana::GetMetaTensorList({}.vec());\n").format(
                xname, pname
            )
            meta_param_vars.append(xname)
        elif cptype == "TensorOptions":
            gcode, xname = rewrite_tensor_options(fname, pname)
            code += gcode
            meta_param_vars.append(xname)
        elif cptype == "c10::optional":
            wrapped_type = type_core(get_template_type_list(ptype)[0])
            if wrapped_type == "Tensor":
                xname = tfetcher.add_opt(pname)
                meta_param_vars.append(xname)
            else:
                meta_param_vars.append(pname)
        elif cptype != "Tensor":
            meta_param_vars.append(pname)
        elif type_is_const(ptype):
            xname = tfetcher.add(pname, False)
            meta_param_vars.append(xname)
        else:
            xname = tfetcher.add(pname, True)
            meta_param_vars.append(xname)
            ce_param_vars.append(pname)

    rtype = get_return_type_str(rwxtree, rwsig)
    opname = get_aten_opname(aten_sig)
    ctxop = ctx.get_op(opname)
    fn = ctx.get_function(fname)

    dtypes = ctxop.get_dtypes()
    if dtypes:
        if "Float" in dtypes:
            dtypes.append("Double")
        if "Int" in dtypes:
            dtypes.append("Long")
    dtype_def = (
        "HPU_SUPPORTED_DTYPES({}, ({{{}}}))".format(
            fname, ", ".join(["c10::ScalarType::" + d for d in dtypes])
        )
        if dtypes
        else None
    )

    lazy_code += lazyop(
        ctxop,
        tfetcher,
        fn,
        fname,
        aten_sig,
        rtype,
        param_vars,
        meta_param_vars,
        ce_param_vars,
    )

    hpuop_class = opname.replace(".", "_")
    hpuop_code = get_hpuop_class_impl(ctxop, fname, hpuop_class)

    return dtype_def, lazy_code, hpuop_code, hpuop_class


def requires_registration(fgen):
    return fgen.dispatch


def get_aten_opname(aten_sig):
    return aten_sig.split("(")[0].split("::")[1]


def get_hpu_wrapper(fndef, ctx):
    tree = _PARSER.parse(fndef.cpp_sig)
    xtree = _XPARSER.parse(fndef.cpp_sig)
    mapsig = create_map_sig(xtree, fndef.cpp_sig)
    rwsig = rewrite_signature(fndef.cpp_sig, _TYPE_NSMAP)
    rwxtree = _XPARSER.parse(rwsig)
    params = get_parameters(tree)
    aten_sig = fndef.aten_sig

    def gen_fnname(x):
        return "HpuOp::{}".format(x)

    sig, fname, xfname = get_function_signature(rwxtree, rwsig, gen_fnname)
    if requires_registration(fndef) and get_aten_opname(aten_sig) in ctx.op_data:
        dtype_def, lazy_code, hpuop_code, cname = generate_code(
            ctx, tree, rwxtree, fname, aten_sig, sig, rwsig, params
        )

        return OpGen(
            tree=tree,
            xtree=xtree,
            rwxtree=rwxtree,
            func=fname,
            xfunc=xfname,
            lazy_code=lazy_code,
            hpuop_code=hpuop_code,
            dtype_def=dtype_def,
            cname=cname,
            sig=fndef.cpp_sig,
            rwsig=rwsig,
            cppsig=sig,
            mapsig=mapsig,
            funsig=create_stdfunc_sig(rwxtree, rwsig),
            aten_sig=aten_sig,
            dispatch=fndef.dispatch,
            default=fndef.default,
        )


def is_tensor_api(fndef):
    fndef = fndef.replace("at::", "")
    fndef = fndef.replace("c10::Device", "Device")
    m = re.search(r"\bTensor\b", fndef)
    return m is not None, fndef


def create_funcdef(fndef, jdata):
    fields = json.loads(jdata)
    return FuncDef(
        cpp_sig=fndef,
        aten_sig=fields["schema"],
        dispatch=fields.get("dispatch", "False") == "True",
        default=fields.get("default", "False") == "True",
    )


def extract_functions(path):
    functions = []
    errors = []

    for line in open(path, "r"):
        m = re.match(r"\s*([^\s].*); //\s+(.*)", line)
        if not m:
            continue
        fndef = m.group(1)
        try:
            _XPARSER.parse(fndef)
            functions.append(create_funcdef(fndef, m.group(2)))
        except Exception as e:
            if is_tensor_api(fndef)[0]:
                errors.append((fndef, str(e)))
                print('Error parsing "{}": {}'.format(fndef, e), file=sys.stderr)
    return functions, errors


def get_mapsig_key(mapsig):
    # PyTorch generates std::tuple<> without space among the tuple types,
    # which would require special understanding in the string rewriter.
    # Since we are using this as simple key, we can just string the spaces.
    return mapsig.replace(" ", "")


def parse_local_overrides(path):
    functions = []
    fndef = None
    for line in open(path, "r"):
        line = line.strip()
        if not fndef:
            m = re.match(r"static\s+(.*);", line)
            if m:
                functions.append(m.group(1))
                continue
            m = re.match(r"static\s+(.*)", line)
            if m:
                fndef = m.group(1)
        else:
            fndef = "{} {}".format(fndef, line)
            if fndef.endswith(";"):
                functions.append(fndef[:-1])
                fndef = None
    assert fndef is None

    overrides = {}
    for fndef in functions:
        # Discard static hpu_wrap functions which are not ATEN.
        is_tensor, fndef = is_tensor_api(fndef)
        if is_tensor:
            xtree = _XPARSER.parse(fndef)
            mapsig_key = get_mapsig_key(create_map_sig(xtree, fndef))
            overrides[mapsig_key] = fndef
    return overrides


def generate_impl(aten_sig, overload, override_fn):
    code = '  m.impl("{}", static_cast<{}>(&{}));\n'.format(
        aten_sig.split("(")[0].split("::")[1], overload, override_fn
    )
    return code


def generate_registrations(fgens):
    aten_code = "TORCH_LIBRARY_IMPL(aten, HABANATensorId, m) {\n"
    autogradhpu_code = None
    overridden = set()
    for fgen in fgens:
        mapsig_key = get_mapsig_key(fgen.mapsig)
        override_fn = "HpuOp::{}".format(fgen.func)
        overridden.add(mapsig_key)
        pos = fgen.funsig.find("(")
        overload = fgen.funsig[:pos] + " (*)" + fgen.funsig[pos:]
        impl = generate_impl(fgen.aten_sig, overload, override_fn)
        if fgen.mapsig in _FN_AUTOGRAD_HPU:
            autogradhpu_code += impl
        else:
            aten_code += impl

    code = aten_code + "\n}\n"

    if autogradhpu_code:
        code += (
            "TORCH_LIBRARY_IMPL(aten, AutogradHABANA, m) {\n"
            + autogradhpu_code
            + "\n}\n"
        )

    return code, overridden


def generate_hpuop_registrations(fgens):
    code = "static const auto& kr = KernelRegistry()\n"

    lines = []
    for fgen in fgens:
        op = fgen.aten_sig.split("(")[0].split("::")[1]
        lines.append(
            '  .add("aten::{}", [](const int device_id, c10::ScalarType node_type) {{\n'
            "      return std::make_shared<{}>(device_id, node_type);\n"
            "  }})".format(op, fgen.cname)
        )

    return code + "\n".join(lines) + ";"


def generate_dtype_defs(fgens):
    code = ""
    for fgen in fgens:
        if fgen.dtype_def:
            code += "{}\n".format(fgen.dtype_def)
    return code


def generate_lazy_fns(fgens):
    code = ""
    for fgen in fgens:
        if fgen.lazy_code:
            code += "{}\n\n".format(fgen.lazy_code)
    return code


def generate_hpuop_class(fgens):
    code = ""
    for fgen in fgens:
        if fgen.hpuop_code:
            code += "{}\n".format(fgen.hpuop_code)
    return code


def generate_class_functions(fgens):
    code = ""
    for fgen in fgens:
        if fgen.lazy_code:
            code += "  static {};\n".format(fgen.rwsig)
    return code


def gen_output_file(args, name):
    if not args.output_folder:
        return sys.stdout
    return open(os.path.join(args.output_folder, name), "w")


def gen_h_output_file(args):
    return gen_output_file(args, "hpu_op.h")


def gen_cpp_output_file(args):
    return gen_output_file(args, "hpu_op.cpp")


def generate(args):
    fndefs, errors = extract_functions(args.typedef)
    assert len(errors) == 0

    fgens = []
    ctx = Context(args.functions, args.yaml)
    for ts in fndefs:
        try:
            fgen = get_hpu_wrapper(ts, ctx)
            if fgen:
                fgens.append(fgen)
        except Exception as e:
            print("Failed to generate op {}: {}".format(ts, e), file=sys.stdout)
            errors.append(e)
    print("Generated {} ops from {}".format(len(fgens), args.yaml), file=sys.stdout)
    assert len(errors) == 0, errors
    assert len(ctx.op_data) == len(
        fgens
    ), "Ops in yaml must conform to definitions in RegistrationDeclarations.h"

    dtype_defs = generate_dtype_defs(fgens)
    functions = generate_lazy_fns(fgens)
    hpuops = generate_hpuop_class(fgens)
    hfunctions = generate_class_functions(fgens)
    hpuop_regs = generate_hpuop_registrations(fgens)
    regs, overridden = generate_registrations(fgens)

    # Create output files ...
    print(
        _H_HEADER.format(gen=os.path.basename(sys.argv[0]), hfuncs=hfunctions),
        file=gen_h_output_file(args),
    )
    print(
        _CPP_HEADER.format(
            gen=os.path.basename(sys.argv[0]),
            dtype_defs=dtype_defs,
            funcs=functions,
            hpuops=hpuops,
            hpuop_regs=hpuop_regs,
            regs=regs,
        ),
        file=gen_cpp_output_file(args),
    )


if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("--output_folder", type=str)
    arg_parser.add_argument(
        "--yaml",
        default=".",
        help="Where yaml file is",
    )
    arg_parser.add_argument(
        "typedef",
        type=str,
        metavar="TYPE_DEFAULT_FILE",
        help="The path to the TypeDefault.h file",
    )
    arg_parser.add_argument(
        "functions",
        type=str,
        metavar="FUNCTIONS_FILE",
        help="The path to the Functions.h file",
    )
    args, files = arg_parser.parse_known_args()
    generate(args)
