// Autogenerated file by gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "hpu_ops/backend/reduction_template.h"
#include "elu.h"


using habana_helpers::DTypeHelper;
using synapse_helpers::graph;
using torch::jit::Stack;


namespace habana {





struct Genelu : OpBackend {
  Genelu(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "elu_fwd", scalar_type, {0}, {}, {}, false) {
        SetFillParams(FillEluParams);
  }
};



static const auto& kr_gen_5 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::elu", Genelu)
;




}  // namespace habana

