import torch
import torchvision

ops_dict = {
    # This dictionary contains the list of ops which can be considered for casting.
    # In general, each op can belong multiple modules. E.g. add belongs to torch
    # as well as torch.tensor.
    # conv
    "conv1d": [torch.nn.functional, torch],
    "conv2d": [torch.nn.functional, torch],
    "conv3d": [torch.nn.functional, torch],
    "conv_transpose1d": [torch.nn.functional, torch],
    "conv_transpose2d": [torch.nn.functional, torch],
    "conv_transpose3d": [torch.nn.functional, torch],
    # pool
    "avg_pool3d": [torch.nn.functional],
    "avg_pool2d": [torch.nn.functional],
    "max_pool2d": [torch.nn.functional],
    "max_pool2d_with_indices": [torch.nn.functional],
    # reductions
    "sum": [torch, torch.Tensor],
    "mean": [torch, torch.Tensor],
    "any": [torch, torch.Tensor],
    # GEMM
    "addmm": [torch, torch.Tensor],
    "bmm": [torch, torch.Tensor],
    "dot": [torch, torch.Tensor],
    "linear": [torch.nn.functional],
    "matmul": [torch, torch.Tensor],
    "mm": [torch, torch.Tensor],
    "mv": [torch, torch.Tensor],
    # Misc modules
    "acos": [torch, torch.Tensor],
    "addcdiv": [torch, torch.Tensor],
    "asin": [torch, torch.Tensor],
    "atan2": [torch, torch.Tensor],
    "batch_norm": [torch.nn.functional],
    "bilinear": [torch.nn.functional],
    "cdist": [torch],
    "cosh": [torch, torch.Tensor],
    "cosine_embedding_loss": [torch.nn.functional],
    "cosine_similarity": [torch.nn.functional],
    "dist": [torch, torch.Tensor],
    "dropout": [torch.nn.functional],
    "dropout1d": [torch.nn.functional],
    "dropout2d": [torch.nn.functional],
    "dropout3d": [torch.nn.functional],
    "einsum": [torch, torch.Tensor],
    "embedding_bag_sum_fwd": [torch],
    "embedding_bag_sum_bwd": [torch],
    "embedding_bag": [torch.nn.functional, torch],
    "embedding": [torch.nn.functional, torch],
    "erfinv": [torch, torch.Tensor],
    "exp": [torch, torch.Tensor],
    "expm1": [torch, torch.Tensor],
    "group_norm": [torch.nn.functional],
    "hinge_embedding_loss": [torch.nn.functional],
    "huber_loss": [torch.nn.functional],
    "kl_div": [torch.nn.functional],
    "l1_loss": [torch.nn.functional],
    "layer_norm": [torch.nn.functional],
    "log10": [torch, torch.Tensor],
    "log1p": [torch, torch.Tensor],
    "logsumexp": [torch, torch.Tensor],
    "instance_norm": [torch.nn.functional],
    "group_norm": [torch.nn.functional],
    "interpolate": [torch.nn.functional],
    "margin_ranking_loss": [torch.nn.functional],
    "mse_loss": [torch.nn.functional],
    "multi_margin_loss": [torch.nn.functional],
    "multilabel_margin_loss": [torch.nn.functional],
    "pdist": [torch.nn.functional],
    "poisson_nll_loss": [torch.nn.functional],
    "pow": [torch, torch.Tensor],
    "reciprocal": [torch, torch.Tensor],
    "renorm": [torch, torch.Tensor],
    "rsqrt": [torch, torch.Tensor],
    "sinh": [torch, torch.Tensor],
    "smooth_l1_loss": [torch.nn.functional],
    "soft_margin_loss": [torch.nn.functional],
    "softplus": [torch.nn.functional],
    "sort": [torch, torch.Tensor],
    "tan": [torch, torch.Tensor],
    "triplet_margin_loss": [torch.nn.functional],
    # Classifiers and loss metrics
    "binary_cross_entropy": [torch.nn.functional],
    "binary_cross_entropy_with_logits": [torch.nn.functional],
    "cross_entropy": [torch.nn.functional],
    "log_softmax": [torch.nn.functional],
    "softmax": [torch.nn.functional],
    "topk": [torch, torch.Tensor],
    "sort": [torch, torch.Tensor],
    "nll_loss": [torch.nn.functional],
    "mse_loss": [torch.nn.functional],
    "smooth_l1_loss": [torch.nn.functional],
    "l1_loss": [torch.nn.functional],
    # Binary
    "add": [torch, torch.Tensor],
    "addcmul": [torch, torch.Tensor],
    "addcdiv": [torch, torch.Tensor],
    "div": [torch, torch.Tensor],
    "divide": [torch, torch.Tensor],
    "exp": [torch, torch.Tensor],
    "iadd": [torch.Tensor],
    "idiv": [torch.Tensor],
    "imul": [torch.Tensor],
    "ipow": [torch.Tensor],
    "isub": [torch.Tensor],
    "itruediv": [torch.Tensor],
    "mul": [torch, torch.Tensor],
    "pow": [torch, torch.Tensor],
    "rsub": [torch, torch.Tensor],
    "rsqrt": [torch, torch.Tensor],
    "sqrt": [torch, torch.Tensor],
    "sub": [torch, torch.Tensor],
    "max": [torch, torch.Tensor],
    "min": [torch, torch.Tensor],
    "truediv": [torch.Tensor],
    "eq": [torch, torch.Tensor],
    "ge": [torch, torch.Tensor],
    "gt": [torch, torch.Tensor],
    "ne": [torch, torch.Tensor],
    # Unary
    "log": [torch, torch.Tensor],
    "log2": [torch, torch.Tensor],
    # Activations
    "gelu": [torch.nn.functional],
    "relu": [torch.nn.functional],
    "leaky_relu": [torch.nn.functional],
    "relu6": [torch.nn.functional],
    "hardtanh": [torch.nn.functional],
    "tanh": [torch.nn.functional],
    "sigmoid": [torch, torch.Tensor],
    # Shapes
    "t": [torch, torch.Tensor],
    "flatten": [torch, torch.Tensor],
    "view": [torch.Tensor],
    "cat": [torch],
    "index_put": [torch, torch.Tensor],
    "index_fill": [torch, torch.Tensor],
    "nonzero": [torch, torch.Tensor],
    "stack": [torch, torch.Tensor],
    # Torchvision ops
    "nms": [torchvision.ops],
    "batched_nms": [torchvision.ops],
    "roi_align": [torchvision.ops],
}
