// Autogenerated file by gen_op.py. Do not edit directly!

#include <torch/extension.h>
#include <pybind11/stl.h>
#include <pybind11/pybind11.h>
#include <torch/csrc/jit/tensorexpr/tensorexpr_init.h>
#include <torch/csrc/jit/python/pybind_utils.h>
#include "cpu_fallback.h"

using habana_helpers::DTypeHelper;
using namespace torch::jit;


namespace habana {



struct shared_layer___ilshift__ : SharedLayerOp {
bool func(torch::jit::Stack &stack, bool is_dynamic) {
  if (stack.size() == 2) {
    auto ivalue_arr = torch::jit::last(stack, 2);
    if (ivalue_arr[0].isTensor() && ivalue_arr[1].isScalar() ) {

      c10::IValue self = std::move(peek(stack, 0, 2));
      c10::IValue other = std::move(peek(stack, 1, 2));

      at::Tensor self_base = self.to<at::Tensor>();
      at::Scalar other_base = other.to<at::Scalar>();
      auto is_supported = impl(self_base, other_base, is_dynamic);
      return is_supported;
    }
  }
  return false;
}
private:
bool impl(at::Tensor & self, const at::Scalar & other, bool is_dynamic) {
  HPU_SUPPORTED_DTYPES(({{-1, {at::kInt, at::kChar, at::kByte, at::kShort, at::kBool}}}))
  RETURN_IF_UNSUPPORTED_DTYPE2(self, __ilshift__, is_dynamic, Scalar, self, other)

  return true;
}

};

struct shared_layer__foreach_add_ : SharedLayerOp {
bool func(torch::jit::Stack &stack, bool is_dynamic) {
  if (stack.size() == 2) {
    auto ivalue_arr = torch::jit::last(stack, 2);
    if (ivalue_arr[0].isTensorList() && ivalue_arr[1].isScalar() ) {

      c10::IValue self = std::move(peek(stack, 0, 2));
      c10::IValue scalar = std::move(peek(stack, 1, 2));

      std::vector<at::Tensor> self_vec;
      const c10::List<c10::IValue> self_list_in = self.toList();

      for (c10::IValue self_elem: self_list_in) {
          at::Tensor self_elem_base = self_elem.to<at::Tensor>();
          self_vec.push_back(self_elem_base);
      }
      at::TensorList self_list_out(self_vec);

      at::Scalar scalar_base = scalar.to<at::Scalar>();
      auto is_supported = impl(self_list_out, scalar_base, is_dynamic);
      return is_supported;
    }
  }
  return false;
}
private:
bool impl(at::TensorList self, const at::Scalar & scalar, bool is_dynamic) {
  HPU_SUPPORTED_DTYPES(({{synDeviceGaudi, {at::kBFloat16, at::kFloat, at::kLong, at::kInt, at::kShort, at::kChar, at::kDouble, at::kBool}},
   {synDeviceGaudi2, {at::kBFloat16, at::kFloat, at::kLong, at::kInt, at::kShort, at::kChar, at::kHalf, at::kDouble, at::kBool}},
   {synDeviceGaudi3, {at::kBFloat16, at::kFloat, at::kLong, at::kInt, at::kShort, at::kChar, at::kHalf, at::kDouble, at::kBool}}}))

  return true;
}

};

struct shared_layer__fused_dropout : SharedLayerOp {
bool func(torch::jit::Stack &stack, bool is_dynamic) {
  if (stack.size() == 3) {
    auto ivalue_arr = torch::jit::last(stack, 3);
    if (ivalue_arr[0].isTensor() && ivalue_arr[1].isDouble() ) {

      c10::IValue self = std::move(peek(stack, 0, 3));
      c10::IValue p = std::move(peek(stack, 1, 3));
      c10::IValue generator = std::move(peek(stack, 2, 3));

      at::Tensor self_base = self.to<at::Tensor>();
      double p_base = p.to<double>();

      auto generator_opt = generator.toOptional<c10::IValue>();
      ::std::optional<at::Generator> generator_opt_out;
      if (generator_opt.has_value()) {
          const c10::IValue generator_opt_in = generator_opt.value();
          at::Generator generator_opt_in_base = generator_opt_in.to<at::Generator>();
          generator_opt_out = ::std::optional<at::Generator>(generator_opt_in_base);
      } else {
          generator_opt_out = ::std::optional<at::Generator>();
      }

      auto is_supported = impl(self_base, p_base, generator_opt_out, is_dynamic);
      return is_supported;
    }
  }
  return false;
}
private:
bool impl(const at::Tensor & self, double p, c10::optional<at::Generator> generator, bool is_dynamic) {
  HPU_SUPPORTED_DTYPES(({{synDeviceGaudi, {at::kBFloat16, at::kFloat, at::kDouble}},
   {synDeviceGaudi2, {at::kBFloat16, at::kFloat, at::kHalf, at::kDouble}},
   {synDeviceGaudi3, {at::kBFloat16, at::kFloat, at::kHalf, at::kDouble}}}))
  RETURN_IF_UNSUPPORTED_DTYPE(self, _fused_dropout, is_dynamic, self, p, generator)

  return true;
}

};





}  // namespace habana

