###############################################################################
#
#  Copyright (c) 2021-2025 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
###############################################################################


# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


def swig_import_helper():
    import importlib

    pkg = __name__.rpartition(".")[0]
    mname = ".".join((pkg, "_py_synapse_logger")).lstrip(".")
    try:
        return importlib.import_module(mname)
    except ImportError:
        return importlib.import_module("_py_synapse_logger")


_py_synapse_logger = swig_import_helper()
del swig_import_helper

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == "SwigPyObject":
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to {self}")


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'{class_type.__name__}' object has no attribute '{name}'")


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return f"<{self.__class__.__module__}.{self.__class__.__name__}; {strthis} >"


try:
    _object = object
    _newclass = 1
except __builtin__.Exception:

    class _object:
        pass

    _newclass = 0


def dump_reference(ref, ref_type, vec):
    return _py_synapse_logger.dump_reference(ref, ref_type, vec)


dump_reference = _py_synapse_logger.dump_reference


def command(x):
    return _py_synapse_logger.command(x)


command = _py_synapse_logger.command


def put_log(what):
    return _py_synapse_logger.put_log(what)


put_log = _py_synapse_logger.put_log


def start_hw_profile():
    return _py_synapse_logger.start_hw_profile()


start_hw_profile = _py_synapse_logger.start_hw_profile


def stop_hw_profile():
    return _py_synapse_logger.stop_hw_profile()


stop_hw_profile = _py_synapse_logger.stop_hw_profile
# This file is compatible with both classic and new-style classes.
