###############################################################################
#
#  Copyright (c) 2025 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
###############################################################################

include_guard(DIRECTORY)

include(FetchContent)

find_program(CLANG_TIDY clang-tidy-20)

if(CLANG_TIDY)
  message(STATUS "Enabling Clang-Tidy. ${CLANG_TIDY} --version:")
  execute_process(COMMAND ${CLANG_TIDY} --version OUTPUT_VARIABLE CLANG_TIDY_VERSION)
  message(${CLANG_TIDY_VERSION})

  execute_process(
    COMMAND dpkg -s libomp-20-dev
    RESULT_VARIABLE LIBOMP20_INSTALLED
    OUTPUT_QUIET ERROR_QUIET)
  if(NOT LIBOMP20_INSTALLED EQUAL 0)
    message(FATAL_ERROR "libomp-20-dev not found! Install it with: sudo apt install libomp-20-dev")
  endif()

  # make clang-tidy work correctly with autogenerated files
  configure_file(.clang-tidy ${PROJECT_BINARY_DIR}/.clang-tidy COPYONLY)

  # Set up Clang-Tidy cache
  FetchContent_Declare(
    ctcache
    GIT_REPOSITORY https://github.com/matus-chochlik/ctcache.git
    GIT_TAG b54f74807fc02c8897247fda6229aabbac78a560
    GIT_SHALLOW TRUE
    EXCLUDE_FROM_ALL SYSTEM)
  FetchContent_MakeAvailable(ctcache)

  message(STATUS "Enabling Clang-Tidy cache")
  list(PREPEND CLANG_TIDY ${Python_EXECUTABLE} ${ctcache_SOURCE_DIR}/src/ctcache/clang_tidy_cache.py)

  if(CLANG_TIDY_FIX)
    message(STATUS "Enabling Clang-Tidy autofixes")
    list(APPEND CLANG_TIDY --fix-errors --fix-notes)
  endif()

  set(CMAKE_CXX_CLANG_TIDY "${CLANG_TIDY}")
else()
  message(STATUS "Clang-Tidy-20 not detected or disabled")
endif()
