orchestratorConfig:
  cron: "H H/3 * * *"
  testConfig:
  - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_greco_sim_cpp_suite
    silentMode: true
  - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_cpp_suite
    runInSanitizer: true
  - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_cpp_suite
    silentMode: true
# PyTorch full graph tests
  - testToLaunch: asic_gaudi_pytorch_perf_tests---t-dg
  - testToLaunch: asic_gaudi_pytorch_sbs_tests---t-dg
  - testToLaunch: asic_gaudi_pytorch_topology_tests---t-dg
  - testToLaunch: Test_pytorch_gaudi2_asic_smoke_topology
  - testToLaunch: Test_pytorch_gaudi2_asic_perf
  - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_distributed
# PyTorch Operators and feature validation <Start>
  - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_single_op
    runInSanitizer: true
  - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_single_op_dynamic
    runInSanitizer: true
  - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_promote_training_suite
  - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_greco_sim_promote_training_suite
    runInSanitizer: true
  - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_promote_training_suite
# Dtype validation <Start>
  - testToLaunch:  pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_promote_training_suite_dtype
  - testToLaunch:  pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_sim_promote_training_suite_dtype
# Dtype validation <End>
# Forward hashing feature <Start>
  - testToLaunch:  pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_fwd_hashing
    silentMode: true
# Forward hashing feature <End>
# PyTorch Operators and feature validation <End>
# deepspeed-fork <Start>
  - testToLaunch:  deepspeed_fork/Tests/Test_deepspeed_fork_gaudi2_sim_test
    silentMode: true
# deepspeed-fork <End>
# Run only in sanitizer
  - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_sim_single_op_dynamic
    silentMode: true
    runInSanitizer: true
stepConfig:
  jobTimeout: '300'
