orchestratorConfig:
  cron: "H H/3 * * *"
  testConfig:
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_cpp_suite
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_py_suite_lazy
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_py_suite_compile
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_py_suite_eager
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_sim_cpp_suite
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_sim_py_suite_lazy
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_sim_py_suite_compile
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_sim_py_suite_eager
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi3_sim_cpp_suite
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi3_sim_py_suite_compile
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi3_sim_py_suite_eager
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi2_asic_topology_group_1
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_topology_group_2
    - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi3_asic_topology_group_1
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_asic_topology_group_2
    - testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi2_sim_pt_distributed
    - testToLaunch: fairseq_fork/Tests/Test_fairseq_fork_gaudi_hls_asic_pytorch_fairseq_topology
    - testToLaunch: model_garden/Tests/Test_model_garden_gaudi2_asic_pytorch_perf_singlenode
    # PyTorch full graph tests
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_hls_asic_perf
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_perf
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_topology_sbs
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_asic_topology_functionality
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_topology_functionality
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_distributed
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_8cards_performance_8x_promote
    - testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi_sim_pt_distributed
    - testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi_sim_pt_small_models_test
    - testToLaunch: multinode_tests/Tests/Test_multinode_tests_gaudi2_sim_pt_small_models_test
    - testToLaunch: fairseq_fork/Tests/Test_fairseq_fork_gaudi2_asic_pytorch_fairseq_topology
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_8cards_short_accuracy_promote
    # PyTorch Operators and feature validation <Start>
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_asic_promote_training_suite
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_promote_pt_perf
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_promote_training_suite_compile
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_promote_training_suite_compile_dynamic
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_promote_training_suite_eager
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_promote_training_suite_lazy
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_asic_promote_training_suite
    # Dtype validation <Start>
    - testToLaunch:  pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_promote_training_suite_dtype
    # Dtype validation <End>
    # Subgraph validation <Start>
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_promote_training_suite_sub_graph_other
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi3_sim_promote_training_suite_sub_graph_other
    # PT perf 8 card jobs in K8S container mode <Start>
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi_asic_8cards_performance_8x_promote
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_8cards_performance_8cards_promote
    # PT perf 8 card jobs in K8S container mode <End>
    - testToLaunch: pytorch_training_tests/Tests/Test_pytorch_training_tests_gaudi2_asic_8cards_topology_8cards
    # deepspeed-fork <Start>
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi2_sim_test
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi_sim_test
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi_hls_asic_unit_tests_promote
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi2_asic_unit_tests_promote
    - testToLaunch: deepspeed_fork/Tests/Test_deepspeed_fork_gaudi2_asic_8cards_test
    - testToLaunch: deepspeed_examples_fork/Tests/Test_deepspeed_examples_fork_gaudi2_asic_8cards_test
    # deepspeed-fork <End>
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_bert_suite
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_unet_suite
    # Quantization toolkit topologies
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_8cards_llama70b_hqt_ptq_4096t_suite
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_8cards_llama70b_hqt_pcq_4096t_suite
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_llama7b_hqt_ptq_4096t_suite
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi2_asic_llama7b_hqt_pcq_4096t_suite
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi3_asic_llama7b_hqt_ptq_4096t_suite
    - testToLaunch: habanaqa_inference/Tests/Test_habanaqa_inference_gaudi3_asic_llama7b_hqt_pcq_4096t_suite
    # Quantization toolkit tests
    - testToLaunch: habana_quantization_toolkit/Tests/Test_habana_quantization_toolkit_gaudi2_asic_test
  codeCoverageConfig:
  - testToLaunch: pytorch_modules/Tests/Test_pytorch_modules_gaudi_sim_cpp_suite
  coverityConfig:
  - exclude: Promote
stepConfig:
  jobTimeout: '300'
