// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "eq.h"
#include "isfinite.h"


using habana_helpers::DTypeHelper; // NOLINT(misc-unused-using-decls)
using synapse_helpers::graph; // NOLINT(misc-unused-using-decls)
using torch::jit::Stack;


namespace habana {





struct Gen_eq_Tensor_out : OpBackend {
  Gen_eq_Tensor_out(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "equal_fwd", scalar_type, {}, {}, {}, true) {
        SetOutputMetaFn(CompareMeta);
        EnableTypePromotion();
        HandleBoolInputs();
  }
};

struct Gen_isfinite : _IsFiniteInfNan {
  Gen_isfinite(int device_id, c10::ScalarType scalar_type) :
      _IsFiniteInfNan(device_id, "isfinite_fwd", scalar_type, {0}, {}, {}, false) {
  }
};



static const auto& kr_gen_7 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::eq.Tensor_out", Gen_eq_Tensor_out)
.REGISTER_HPU_BACKEND("aten::isfinite", Gen_isfinite)
;




}  // namespace habana

