// Autogenerated file by run_gen_op.py. Do not edit directly!

#include "hpu_ops/op_validator.h"
#include "clone.h"
#include "prod.h"


using habana_helpers::DTypeHelper; // NOLINT(misc-unused-using-decls)
using synapse_helpers::graph; // NOLINT(misc-unused-using-decls)
using torch::jit::Stack;


namespace habana {





struct Gen_prod_int_out : OpBackend {
  Gen_prod_int_out(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "reduce_prod_multi_dim_fwd", scalar_type, {}, {}, {}, true) {
  }
};

struct Gen_clone : OpBackend {
  Gen_clone(int device_id, c10::ScalarType scalar_type) :
      OpBackend(device_id, "identity", scalar_type, {0}, {}, {}, false) {
        setNoComputeFlag();
        SetOutputMetaFn(CloneMeta);
  }
};



static const auto& kr_gen_4 = KernelRegistry()
.REGISTER_HPU_BACKEND("aten::prod.int_out", Gen_prod_int_out)
.REGISTER_HPU_BACKEND("aten::clone", Gen_clone)
;




}  // namespace habana

